### ISSUE TITLE
ConcurrentModificationException when refreshing DSLD scripts

### ISSUE THREAD

**Issue by twwwt** [groovy/groovy-eclipse#1016]
When starting Eclipse, I get the following exception, sometimes just once, sometimes multiple times:

```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1139)
	at org.codehaus.groovy.eclipse.dsl.DSLDStoreManager.getDSLDStore(DSLDStoreManager.java:46)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob.refreshProject(RefreshDSLDJob.java:170)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob.run(RefreshDSLDJob.java:123)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

 Eclipse's error log further contains the message
 ```
An internal error occurred during: "Refresh DSLD scripts"
```

Observed at least with Groovy Eclipse plugin 3.5.0, 3.6.0, 3.7.0 and the following environment:
```
eclipse.buildId=4.14.0.I20191210-0610
java.version=13.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=de_CH
```

**Comment by eric-milles** [comment]
ready to test
