### ISSUE TITLE
NPE sometimes when on save on JavaEditor.getBreadcrumbPreferenceKey

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#1040]
I recently switched to Eclipse 2019-12 and the "latest" Greclipse (3.7.0.v202002112302-e1912).

A couple of times something went really bad and Eclipse prompted me to restart the workbench. The Eclipse main menu disappeared (the first element in the Eclipse main window was the toolbar, instead of the main menu).
This is reported in the error log: I see there's Greclipse in the stack trace, so I suspect it may be its fault. Last time I was certainly working on a Java file though.

```
eclipse.buildId=4.14.0.I20191210-0610
java.version=1.8.0_202
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=it_IT
Command-line arguments:  -os win32 -ws win32 -arch x86_64

This is a continuation of log file D:\ws\rolling\DCS-SHOP-trunk\.metadata\.bak_4.log
Created Time: 2020-02-21 18:19:12.686

org.eclipse.ui.workbench
Error
Fri Feb 21 18:19:12 CET 2020
Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".

java.lang.NullPointerException
	at org.eclipse.jdt.internal.ui.javaeditor.JavaEditor.getBreadcrumbPreferenceKey(JavaEditor.java:1947)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaEditor.handlePreferenceStoreChanged(JavaEditor.java:2897)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor.handlePreferenceStoreChanged(CompilationUnitEditor.java:1649)
	at org.codehaus.groovy.eclipse.editor.GroovyEditor.handlePreferenceStoreChanged(GroovyEditor.java:914)
	at org.eclipse.ui.texteditor.AbstractTextEditor$PropertyChangeListener.propertyChange(AbstractTextEditor.java:701)
	at org.eclipse.ui.texteditor.ChainedPreferenceStore.firePropertyChangeEvent(ChainedPreferenceStore.java:156)
	at org.eclipse.ui.texteditor.ChainedPreferenceStore.handlePropertyChangeEvent(ChainedPreferenceStore.java:368)
	at org.eclipse.ui.texteditor.ChainedPreferenceStore.access$0(ChainedPreferenceStore.java:345)
	at org.eclipse.ui.texteditor.ChainedPreferenceStore$PropertyChangeListener.propertyChange(ChainedPreferenceStore.java:70)
	at org.eclipse.ui.texteditor.ChainedPreferenceStore.firePropertyChangeEvent(ChainedPreferenceStore.java:156)
	at org.eclipse.ui.texteditor.ChainedPreferenceStore.handlePropertyChangeEvent(ChainedPreferenceStore.java:368)
	at org.eclipse.ui.texteditor.ChainedPreferenceStore.access$0(ChainedPreferenceStore.java:345)
	at org.eclipse.ui.texteditor.ChainedPreferenceStore$PropertyChangeListener.propertyChange(ChainedPreferenceStore.java:70)
	at org.eclipse.ui.preferences.ScopedPreferenceStore$2.run(ScopedPreferenceStore.java:325)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.firePropertyChangeEvent(ScopedPreferenceStore.java:322)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.lambda$0(ScopedPreferenceStore.java:171)
	at org.eclipse.core.internal.preferences.EclipsePreferences$2.run(EclipsePreferences.java:851)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.preferences.EclipsePreferences.firePreferenceEvent(EclipsePreferences.java:854)
	at org.eclipse.core.internal.preferences.EclipsePreferences.remove(EclipsePreferences.java:961)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$StylingPreferencesHandler.resetOverriddenPreferences(PartRenderingEngine.java:1458)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$StylingPreferencesHandler.resetOverriddenPreferences(PartRenderingEngine.java:1452)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$StylingPreferencesHandler.lambda$0(PartRenderingEngine.java:1441)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4167)
	at org.eclipse.swt.widgets.Display.release(Display.java:3634)
	at org.eclipse.swt.graphics.Device.dispose(Device.java:277)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:166)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
```

**Comment by eric-milles** [comment]
```java
	/**
	 * Returns the preference key for the breadcrumb. The
	 * value depends on the current perspective.
	 *
	 * @return the preference key or <code>null</code> if there's no perspective
	 * @since 3.4
	 */
	String getBreadcrumbPreferenceKey() {
		IPerspectiveDescriptor perspective= getSite().getPage().getPerspective();
		if (perspective == null)
			return null;
		return JavaEditor.EDITOR_SHOW_BREADCRUMB + "." + perspective.getId(); //$NON-NLS-1$
	}
```

**Comment by eric-milles** [comment]
https://git.eclipse.org/r/158122

**Comment by iloveeclipse** [comment]
This is most likely a symptom of another problem: a groovy editor that does not properly disconnect preference listener on dispose() and so the listener is working with the disposed editor.

**Comment by eric-milles** [comment]
@mauromol Do you have any log snippets that can describe what "something went really bad" refers to.  It sounds like workbench is in a bad state and so normal disposal/shutdown is not happening.

@iloveeclipse Is there any harm in adding defensive checks to getBreadcrumbPreferenceKey?

**Comment by iloveeclipse** [comment]
No, but fixing not properly disconnected listener is better.

**Comment by mauromol** [comment]
@eric-milles by "something went really bad", I mean that this error started to appear dozen times very fast in the log and Eclipse popped up a confirm dialog suggesting to close the workbench because it was in a corrupted state and, as I said above, the main menu at the top of the Eclipse main window had disappeared as well.
I'll try to look better at the logs to see if something else appeared BEFORE the machine-gun fire of these errors.

**Comment by mauromol** [comment]
Unfortunately right now I can't find any log entry before the first NPE reported above, logs have rotated and nothing older is available any more in my workbench `.metadata` directory.
If it happens again I will try to better look at the logs. It is not easy because, as I said, these NPEs are repeated dozen times.
