### ISSUE TITLE
Confusing events resulting in NoClassDefFoundError for LanguageSupportFactory

### ISSUE THREAD

**Issue by davidmichaelkarr** [groovy/groovy-eclipse#1062]
Weird events this morning.  I'm trying to remember everything that happened. It does involve GroovyEclipse, but I'm not sure of the relationships between the issues.

I was running Eclipse 2019-12.  I believe I had EclipseGroovy v3.7.0.  I have "https://dist.springsource.org/snapshot/GRECLIPSE/e4.14" in my update sites.

At some point this morning I noticed that 2020-03 was available, so I downloaded the installer.  Past downloading the installer, I have not touched it or run it.

I also noticed some plugin updates more than the usual almost daily updates to the GroovyEclipse plugin. I don't remember what plugins they were for, but it wasn't extensive.

I've rebooted a few times to deal with unrelated issues. I noticed one curious dialog from Eclipse on a restart, saying something about my workspace was "intended for an older release". This was very odd, since I've used the same workspace since the day I installed 2019-12, and I strictly use only a single workspace with each Eclipse version.

After another restart, I noticed that the Eclipse splash screen said it was 2020-03, and then I looked at the About listing, and it showed the platform version was 4.15.  I still have not touched the 2020-03 installer.

Along with all of this, I discovered that our applications are not building, presenting an odd error dialog from GroovyEclipse, giving me a dialog saying:
```Errors occurred during the build.
Errors running builder 'Java Builder' on project 'cartms'.
org/codehaus/jdt/groovy/integration/LanguageSupportFactory
```
I then looked in the error log, and I saw this:
```java.lang.NoClassDefFoundError: org/codehaus/jdt/groovy/integration/LanguageSupportFactory
	at org.codehaus.groovy.eclipse.core.compiler.CompilerCleanerParticipant.isActive(CompilerCleanerParticipant.java:37)
	at org.eclipse.jdt.internal.core.JavaModelManager$CompilationParticipants.getCompilationParticipants(JavaModelManager.java:473)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.initializeBuilder(JavaBuilder.java:635)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:181)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
I then went back to the About listing to verify my GroovyEclipse version is "3.7.0.v202003162158-e1912".

Any ideas?

**Comment by eric-milles** [comment]
If you have moved from Eclipse 2019-12 (4.14) to 2020-03 (4.15), the warning about a workspace "intended for an older release" is normal.  You can usually click to ignore and continue.  I have been able to go back and forth with eclipse versions safely since Neon or even earlier.

If you have installed 2020-03, you need to change the Groovy-Eclipse update site that you are using.  Each update site is designed to be paired with the matching eclipse version.  This is so the JDT patch works properly.

It is a sign that the JDT patch is not working properly when the class org/codehaus/jdt/groovy/integration/LanguageSupportFactory cannot be found.  This class is part of the patch of the org.eclipse.jdt.core bundle.

**Comment by davidmichaelkarr** [comment]
Ok, we'll ignore the fact that I appear to be running 2020-03 even though I didn't install it. All the signs seem to indicate that I'm running 2020-03. I have no clue how this happened.

I just tried looking at my installation history in what I thought was the 2019-12 distribution, clicking on each entry to see what version of the Eclipse platform it showed.  The "Current" was 4.15, including one from earlier this morning.  The only one from yesterday was 4.14.  I've reverted to that, and now my build problems do not occur.

So what update site do I have to set to for 2020-03?  There is no entry in the table for it.

**Comment by eric-milles** [comment]
From the snapshots table (https://github.com/groovy/groovy-eclipse/wiki#snapshots):
https://dist.springsource.org/snapshot/GRECLIPSE/e4.15

There will be a release update site on March 31st when [3.7.0](https://github.com/groovy/groovy-eclipse/milestone/8) is released.

**Comment by kenwdelong** [comment]
I had the same issue, but updating the snapshot location fixed it!
