### ISSUE TITLE
Groovy plugin not working in Oxygen Eclipse IDE ? show below error on my first hello world code 

### ISSUE THREAD

**Issue by SatishSPP** [groovy/groovy-eclipse#1156]
java.lang.ClassNotFoundException: groovy.ui.Console
	at org.codehaus.groovy.tools.RootLoader.findClass(RootLoader.java:178)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.codehaus.groovy.tools.RootLoader.loadClass(RootLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:104)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:128)

**Comment by eric-milles** [comment]
If you are trying "Run As > Groovy Console" under Eclipse Oxygen, you will need to do one of the following:
1. switch compiler to Groovy 2.4
1. switch to Eclipse 2018-09 or newer
1. add `groovy-console.jar` and its dependencies to `~/.groovy/lib`
1. add `groovy-console.jar` and its dependencies to your project classpath
1. add `groovy-console.jar` and its dependencies to `<eclipse dir>/plugins/org.codehaus.groovy_i.j.k.yyyymmddhhmm/lib`

After Groovy 2.4, the necessary dependencies were split out -- groovy-all.jar was no longer available.  There was an enhancement to Groovy-Eclipse to include the necessary dependencies, but this fix applies to Eclipse 2018-09 and forward.
