### ISSUE TITLE
Fix code hover for type disjunction

### ISSUE THREAD

**Issue by eric-milles** [groovy/groovy-eclipse#1170]
Consider the following:
```groovy
@groovy.transform.CompileStatic
void test(CharSequence cs) {
  if (cs instanceof Serializable) {
    cs
  }
}
```

The inferred type for "cs" within the if block is the type disjunction "CharSequence+Serializable".  Hovering over "cs" produces an error:
```
java.lang.IllegalArgumentException: <UnionType:java.lang.CharSequence+java.io.Serializable>
	at org.eclipse.jdt.core.Signature.encodeQualifiedName(Signature.java:1373)
	at org.eclipse.jdt.core.Signature.encodeTypeSignature(Signature.java:1495)
	at org.eclipse.jdt.core.Signature.createCharArrayTypeSignature(Signature.java:1095)
	at org.eclipse.jdt.core.Signature.createTypeSignature(Signature.java:1293)
	at org.eclipse.jdt.core.Signature.createTypeSignature(Signature.java:1320)
	at org.eclipse.jdt.groovy.core.util.GroovyUtils.getTypeSignatureWithoutGenerics(GroovyUtils.java:259)
	at org.eclipse.jdt.groovy.core.util.GroovyUtils.getTypeSignature(GroovyUtils.java:202)
	at org.codehaus.groovy.eclipse.codebrowsing.requestor.CodeSelectRequestor.handleMatch(CodeSelectRequestor.java:254)
	at org.codehaus.groovy.eclipse.codebrowsing.requestor.CodeSelectRequestor.acceptASTNode(CodeSelectRequestor.java:144)
```

**Comment by eric-milles** [comment]
![image](https://user-images.githubusercontent.com/18193802/95516935-acd6f100-0985-11eb-848b-54f193a162d1.png)
