### ISSUE TITLE
The latest release has broken the Eclipse New Class Wizard

### ISSUE THREAD

**Issue by DJViking** [groovy/groovy-eclipse#1203]
The plugin is causing an error with Eclipse when trying to create new Java files.
It will not open the New Java Class Wizard Dialog.

The Eclipse log has the following Error:
```
!ENTRY org.eclipse.ui 4 0 2020-11-26 12:25:16.077
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NoSuchFieldError: sourceName
        at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyParser.isGroovyParserEligible(GroovyParser.java:105)
        at org.codehaus.jdt.groovy.integration.internal.MultiplexingCommentRecorderParser.dietParse(MultiplexingCommentRecorderParser.java:46)
        at org.eclipse.jdt.core.dom.CompilationUnitResolver.parse(CompilationUnitResolver.java:556)
        at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1224)
        at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:820)
        at org.eclipse.jdt.internal.corext.refactoring.TypeContextChecker.parseSuperType(TypeContextChecker.java:747)
        at org.eclipse.jdt.internal.corext.refactoring.TypeContextChecker.parseSuperClass(TypeContextChecker.java:722)
        at org.eclipse.jdt.ui.wizards.NewTypeWizardPage.superClassChanged(NewTypeWizardPage.java:1950)
        at org.eclipse.jdt.ui.wizards.NewTypeWizardPage.typePageDialogFieldChanged(NewTypeWizardPage.java:1232)
        at org.eclipse.jdt.ui.wizards.NewTypeWizardPage.access$2(NewTypeWizardPage.java:1196)
        at org.eclipse.jdt.ui.wizards.NewTypeWizardPage$TypeFieldsAdapter.dialogFieldChanged(NewTypeWizardPage.java:1131)
        at org.eclipse.jdt.internal.ui.wizards.dialogfields.DialogField.dialogFieldChanged(DialogField.java:78)
        at org.eclipse.jdt.internal.ui.wizards.dialogfields.StringDialogField.setText(StringDialogField.java:195)
        at org.eclipse.jdt.ui.wizards.NewTypeWizardPage.setSuperClass(NewTypeWizardPage.java:1480)
        at org.eclipse.jdt.ui.wizards.NewTypeWizardPage.initTypePage(NewTypeWizardPage.java:646)
        at org.eclipse.jdt.ui.wizards.NewClassWizardPage.init(NewClassWizardPage.java:94)
        at org.eclipse.jdt.internal.ui.wizards.NewClassCreationWizard.addPages(NewClassCreationWizard.java:56)
        at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:632)
        at org.eclipse.jface.window.Window.create(Window.java:431)
        at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
        at org.eclipse.ui.internal.navigator.wizards.WizardShortcutAction.run(WizardShortcutAction.java:99)
        at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
        at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
        at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
```

This is caused when installing the GRECLIPSE v4.17 3.9.0 Release.
Uninstalling the Groovy Eclipse plugin is the only way to get it working again.

Instead installing the GRECLIPSE v4.17 Snapshot does not cause this problem.

**Comment by eric-milles** [comment]
`org.codehaus.jdt.groovy.internal.compiler.ast.GroovyParser#isGroovyParserEligible` does not exist in [3.9.0.RELEASE](https://github.com/groovy/groovy-eclipse/blob/3_9_maintenance/base/org.eclipse.jdt.groovy.core/src/org/codehaus/jdt/groovy/internal/compiler/ast/GroovyParser.java).  It is part of a change in 4.0.0.SNAPSHOT, which is where the `sourceName` field was added to `BasicCompilationUnit`.
