### ISSUE TITLE
Framework error in Eclipse

### ISSUE THREAD

**Issue by twwwt** [groovy/groovy-eclipse#1227]
Using recent versions of the plugin, I get the following error on Eclipse startup:

```
org.osgi.framework.BundleException: Could not resolve module: org.codehaus.groovy.eclipse.astviews [1528]
  Another singleton bundle selected: osgi.identity; osgi.identity="org.codehaus.groovy.eclipse.astviews"; type="osgi.bundle"; version:Version="4.1.0.v202102071658-e2009"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

My config:
```
eclipse.buildId=4.18.0.I20201202-1800
java.version=15
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=de_CH
```

**Comment by eric-milles** [comment]
Do you have multiple versions of the `org.codehaus.groovy.eclipse.astviews` bundle in your plugins directory?

**Comment by twwwt** [comment]
Yes, there were multiple versions of `org.codehaus.groovy.eclipse.astviews`. I have uninstalled the plugin (Groovy Eclipse), removed _all_ plugins that match `org.codehaus.groovy.*` manually, and reinstalled Groovy Eclipse. This seemed to have resolve the error.

Still, I have the impression that whenever I update the plugin using a newer update site, the error reoccurs. Could it be that plugins are not correctly cleaned up on update?

**Comment by eric-milles** [comment]
When plugins are updated, the old ones are typically retained to support rollback.  You can flush them from the UI using _Help > About Eclipse ... > Installation Details > Installation History_
