### ISSUE TITLE
Unable to install groovy-eclipse 4.1 with Eclipse Oomph

### ISSUE THREAD

**Issue by kwin** [groovy/groovy-eclipse#1239]
In my [custom Eclipse installer](https://projects.eclipse.org/projects/tools.oomph) I added the section: 

```
<setupTask
          xsi:type="setup.p2:P2Task"
          label="Groovy Eclipse">
        <requirement
            name="org.codehaus.groovy.jdt.patch.feature.group"/>
        <requirement
            name="org.codehaus.groovy25.feature.feature.group"/>
        <requirement
            name="org.codehaus.groovy30.feature.feature.group"/>
        <requirement
            name="org.codehaus.groovy.m2eclipse.feature.feature.group"/>
        <requirement
            name="org.codehaus.groovy.eclipse.feature.feature.group"/>
        <repository
            url="https://dist.springsource.org/release/GRECLIPSE/e4.19"/>
        <description></description>
      </setupTask>
```

When installing this Eclipse product with Eclipse Installer 1.18.0 I run into the following exception:

```
Collecting 2 artifacts from https://dist.springsource.org/release/GRECLIPSE/e4.19
Downloading org.codehaus.groovy.eclipse.ant
Downloading org.codehaus.groovy.eclipse.dsl
Mirrored 2 artifacts from https://dist.springsource.org/release/GRECLIPSE/4.1.0/e4.19/ at 0kb/s with 2 failures
Collected 2 artifacts for https://dist.springsource.org/release/GRECLIPSE/e4.19 in 120.685s
...
An error was detected while performing the engine operation and the changes are being rolled back. See the log for details.
ERROR: org.eclipse.equinox.p2.engine code=4 An error occurred while collecting items to be installed
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:291)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$3.commit(ProfileTransactionImpl.java:551)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:343)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:899)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3828)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3756)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3737)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3630)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:593)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:720)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.engine code=0 session context was:(profile=_Users_konradwindszus_eclipse_aem-2021-03_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
  ERROR: org.eclipse.equinox.p2.transport.ecf code=1002 Unable to read repository at https://dist.springsource.org/release/GRECLIPSE/4.1.0/e4.19/plugins/org.codehaus.groovy.eclipse.ant_4.1.0.v202103311613-e2103-RELEASE.jar.
  org.apache.http.NoHttpResponseException: dist.springsource.org:443 failed to respond
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
    at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
    at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
    at org.eclipse.ecf.provider.filetransfer.httpclient45.HttpClientRetrieveFileTransfer.performConnect(HttpClientRetrieveFileTransfer.java:1003)
    at org.eclipse.ecf.provider.filetransfer.httpclient45.HttpClientRetrieveFileTransfer.access$0(HttpClientRetrieveFileTransfer.java:995)
    at org.eclipse.ecf.provider.filetransfer.httpclient45.HttpClientRetrieveFileTransfer$1.performFileTransfer(HttpClientRetrieveFileTransfer.java:991)
    at org.eclipse.ecf.filetransfer.FileTransferJob.run(FileTransferJob.java:76)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.transport.ecf code=1002 Unable to read repository at https://dist.springsource.org/release/GRECLIPSE/4.1.0/e4.19/plugins/org.codehaus.groovy.eclipse.dsl_4.1.0.v202103311613-e2103-RELEASE.jar.
  org.apache.http.NoHttpResponseException: dist.springsource.org:443 failed to respond
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
    at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
    at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
    at org.eclipse.ecf.provider.filetransfer.httpclient45.HttpClientRetrieveFileTransfer.performConnect(HttpClientRetrieveFileTransfer.java:1003)
    at org.eclipse.ecf.provider.filetransfer.httpclient45.HttpClientRetrieveFileTransfer.access$0(HttpClientRetrieveFileTransfer.java:995)
    at org.eclipse.ecf.provider.filetransfer.httpclient45.HttpClientRetrieveFileTransfer$1.performFileTransfer(HttpClientRetrieveFileTransfer.java:991)
    at org.eclipse.ecf.filetransfer.FileTransferJob.run(FileTransferJob.java:76)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

For all previous versions of groovy-eclipse this worked without any flaws. Are there any known issues with the infrastructure?

Downloading https://dist.springsource.org/release/GRECLIPSE/4.1.0/e4.19/plugins/org.codehaus.groovy.eclipse.dsl_4.1.0.v202103311613-e2103-RELEASE.jar with a browser works fine. I am not behind any proxy. Could it be that the Oomph agent is blocked?

**Comment by kwin** [comment]
I got it to work after upgrading the Eclipse Installer to version 1.20.0 Build 5032 but I would still suspect that something related to connection pooling has been changed (https://stackoverflow.com/a/10600762).
