### ISSUE TITLE
ArrayIndexOutOfBoundsException for method call with too few type arguments

### ISSUE THREAD

**Issue by eric-milles** [groovy/groovy-eclipse#1249]
Consider the following:
```groovy
void test(Type[] array) {
  array.sort(true, Comparator.<Type>comparing({ it.foo }).reversed())
}
```

Type inferencing and syntax highlighting break down at "comparing" due to supplying one type argument for a method that expects two.

![image](https://user-images.githubusercontent.com/18193802/115283298-c9ac6800-a110-11eb-82bb-841b7d88b98f.png)

```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.eclipse.jdt.groovy.search.GenericsMapper.gatherGenerics(GenericsMapper.java:127)
	at org.eclipse.jdt.groovy.search.TypeLookupResult.resolveTypeParameterization(TypeLookupResult.java:248)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.lookupExpressionType(TypeInferencingVisitorWithRequestor.java:2750)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.handleSimpleExpression(TypeInferencingVisitorWithRequestor.java:2023)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.handleSimpleExpression(TypeInferencingVisitorWithRequestor.java:2028)
```

**Comment by eric-milles** [comment]
![image](https://user-images.githubusercontent.com/18193802/115299154-10578d80-a124-11eb-8408-fb5ff27c8046.png)
