### ISSUE TITLE
ClassCastException in groovy editor for dynamic property syntax

### ISSUE THREAD

**Issue by gtchaboussie** [groovy/groovy-eclipse#1253]
Hi, when opening a file i get an error. here is the log : 
```
java.lang.ClassCastException: class org.codehaus.groovy.ast.expr.PropertyExpression cannot be cast to class org.codehaus.groovy.ast.expr.MethodCallExpression (org.codehaus.groovy.ast.expr.PropertyExpression and org.codehaus.groovy.ast.expr.MethodCallExpression are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1b6a1841)
	at org.codehaus.groovy.eclipse.codebrowsing.fragments.ASTFragmentFactory.createPropertyBasedFragment(ASTFragmentFactory.java:161)
	at org.codehaus.groovy.eclipse.codebrowsing.fragments.ASTFragmentFactory.createFragment(ASTFragmentFactory.java:83)
	at org.codehaus.groovy.eclipse.codebrowsing.fragments.ASTFragmentFactory.createFragment(ASTFragmentFactory.java:50)
	at org.codehaus.groovy.eclipse.codebrowsing.selection.FindSurroundingNode.visitPropertyExpression(FindSurroundingNode.java:462)
	at org.codehaus.groovy.ast.expr.PropertyExpression.visit(PropertyExpression.java:55)
	at org.eclipse.jdt.groovy.core.util.DepthFirstVisitor.visitBinaryExpression(DepthFirstVisitor.java:407)
	at org.codehaus.groovy.eclipse.codebrowsing.selection.FindSurroundingNode.visitBinaryExpression(FindSurroundingNode.java:329)
	at org.codehaus.groovy.ast.expr.BinaryExpression.visit(BinaryExpression.java:49)
	at org.eclipse.jdt.groovy.core.util.DepthFirstVisitor.visitIfPresent(DepthFirstVisitor.java:716)
	at org.eclipse.jdt.groovy.core.util.DepthFirstVisitor.visitReturnStatement(DepthFirstVisitor.java:336)
	at org.codehaus.groovy.eclipse.codebrowsing.selection.FindSurroundingNode.visitReturnStatement(FindSurroundingNode.java:274)
	at org.codehaus.groovy.ast.stmt.ReturnStatement.visit(ReturnStatement.java:49)
	at org.eclipse.jdt.groovy.core.util.DepthFirstVisitor.visitBlockStatement(DepthFirstVisitor.java:268)
	at org.codehaus.groovy.eclipse.codebrowsing.selection.FindSurroundingNode.visitBlockStatement(FindSurroundingNode.java:205)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
	at org.eclipse.jdt.groovy.core.util.DepthFirstVisitor.visitIfPresent(DepthFirstVisitor.java:716)
	at org.eclipse.jdt.groovy.core.util.DepthFirstVisitor.visitIfElse(DepthFirstVisitor.java:325)
	at org.codehaus.groovy.eclipse.codebrowsing.selection.FindSurroundingNode.visitIfElse(FindSurroundingNode.java:267)
	at org.codehaus.groovy.ast.stmt.IfStatement.visit(IfStatement.java:41)
	at org.eclipse.jdt.groovy.core.util.DepthFirstVisitor.visitBlockStatement(DepthFirstVisitor.java:268)
	at org.codehaus.groovy.eclipse.codebrowsing.selection.FindSurroundingNode.visitBlockStatement(FindSurroundingNode.java:205)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
	at org.eclipse.jdt.groovy.core.util.DepthFirstVisitor.visitClosureExpression(DepthFirstVisitor.java:448)
	at org.codehaus.groovy.eclipse.codebrowsing.selection.FindSurroundingNode.visitClosureExpression(FindSurroundingNode.java:364)
	at org.codehaus.groovy.ast.expr.ClosureExpression.visit(ClosureExpression.java:46)
	at org.codehaus.groovy.eclipse.codebrowsing.requestor.ASTNodeFinder.visitArgumentlistExpression(ASTNodeFinder.java:283)
	at org.codehaus.groovy.ast.expr.ArgumentListExpression.visit(ArgumentListExpression.java:74)
	at org.eclipse.jdt.groovy.core.util.DepthFirstVisitor.visitMethodCallExpression(DepthFirstVisitor.java:525)
	at org.codehaus.groovy.eclipse.codebrowsing.requestor.ASTNodeFinder.visitMethodCallExpression(ASTNodeFinder.java:260)
	at org.codehaus.groovy.eclipse.codebrowsing.selection.FindSurroundingNode.visitMethodCallExpression(FindSurroundingNode.java:431)
	at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:72)
	at org.eclipse.jdt.groovy.core.util.DepthFirstVisitor.visitExpressionStatement(DepthFirstVisitor.java:310)
	at org.codehaus.groovy.eclipse.codebrowsing.selection.FindSurroundingNode.visitExpressionStatement(FindSurroundingNode.java:253)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
	at org.eclipse.jdt.groovy.core.util.DepthFirstVisitor.visitBlockStatement(DepthFirstVisitor.java:268)
	at org.codehaus.groovy.eclipse.codebrowsing.selection.FindSurroundingNode.visitBlockStatement(FindSurroundingNode.java:205)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
	at org.eclipse.jdt.groovy.core.util.DepthFirstVisitor.visitIfPresent(DepthFirstVisitor.java:716)
	at org.eclipse.jdt.groovy.core.util.DepthFirstVisitor.visitMethod(DepthFirstVisitor.java:253)
	at org.codehaus.groovy.eclipse.codebrowsing.requestor.ASTNodeFinder.visitMethod(ASTNodeFinder.java:169)
	at org.codehaus.groovy.eclipse.codebrowsing.selection.FindSurroundingNode.visitMethod(FindSurroundingNode.java:188)
	at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1207)
	at org.eclipse.jdt.groovy.core.util.DepthFirstVisitor.visitClass(DepthFirstVisitor.java:169)
	at org.codehaus.groovy.eclipse.codebrowsing.requestor.ASTNodeFinder.visitClass(ASTNodeFinder.java:102)
	at org.codehaus.groovy.eclipse.codebrowsing.selection.FindSurroundingNode.visitClass(FindSurroundingNode.java:162)
	at org.eclipse.jdt.groovy.core.util.DepthFirstVisitor.visitModule(DepthFirstVisitor.java:135)
	at org.codehaus.groovy.eclipse.codebrowsing.requestor.ASTNodeFinder.doVisit(ASTNodeFinder.java:73)
	at org.codehaus.groovy.eclipse.codebrowsing.selection.FindSurroundingNode.doVisitSurroundingNode(FindSurroundingNode.java:113)
	at org.codehaus.groovy.eclipse.editor.GroovyAwareFoldingStructureProvider.isScriptMethodElement(GroovyAwareFoldingStructureProvider.java:195)
	at org.codehaus.groovy.eclipse.editor.GroovyAwareFoldingStructureProvider.computeCommentFoldingStructure(GroovyAwareFoldingStructureProvider.java:126)
	at org.codehaus.groovy.eclipse.editor.GroovyAwareFoldingStructureProvider.computeFoldingStructure(GroovyAwareFoldingStructureProvider.java:81)
	at org.eclipse.jdt.ui.text.folding.DefaultJavaFoldingStructureProvider.computeFoldingStructure(DefaultJavaFoldingStructureProvider.java:988)
	at org.eclipse.jdt.ui.text.folding.DefaultJavaFoldingStructureProvider.computeFoldingStructure(DefaultJavaFoldingStructureProvider.java:992)
	at org.eclipse.jdt.ui.text.folding.DefaultJavaFoldingStructureProvider.computeFoldingStructure(DefaultJavaFoldingStructureProvider.java:981)
	at org.eclipse.jdt.ui.text.folding.DefaultJavaFoldingStructureProvider.update(DefaultJavaFoldingStructureProvider.java:898)
	at org.eclipse.jdt.ui.text.folding.DefaultJavaFoldingStructureProvider.initialize(DefaultJavaFoldingStructureProvider.java:843)
	at org.eclipse.jdt.ui.text.folding.DefaultJavaFoldingStructureProvider.handleProjectionEnabled(DefaultJavaFoldingStructureProvider.java:813)
	at org.eclipse.jdt.ui.text.folding.DefaultJavaFoldingStructureProvider$ProjectionListener.projectionEnabled(DefaultJavaFoldingStructureProvider.java:691)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.fireProjectionEnabled(ProjectionViewer.java:475)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.enableProjection(ProjectionViewer.java:523)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaSourceViewer.setVisibleDocument(JavaSourceViewer.java:636)
	at org.eclipse.jface.text.TextViewer.setDocument(TextViewer.java:2805)
	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:663)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.setDocument(ProjectionViewer.java:368)
	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:613)
	at org.eclipse.ui.texteditor.AbstractTextEditor.initializeSourceViewer(AbstractTextEditor.java:3985)
	at org.eclipse.ui.texteditor.AbstractTextEditor.createPartControl(AbstractTextEditor.java:3477)
	at org.eclipse.ui.texteditor.StatusTextEditor.createPartControl(StatusTextEditor.java:64)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.createPartControl(AbstractDecoratedTextEditor.java:454)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaEditor.createPartControl(JavaEditor.java:3079)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor.createPartControl(CompilationUnitEditor.java:1521)
	at org.codehaus.groovy.eclipse.editor.GroovyEditor.createPartControl(GroovyEditor.java:809)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:158)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:96)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:365)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:999)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:964)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:140)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:405)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:332)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:91)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:132)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:999)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:765)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:730)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:714)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.lambda$0(PartServiceImpl.java:104)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5941)
	at org.eclipse.e4.ui.workbench.swt.DisplayUISynchronize.syncExec(DisplayUISynchronize.java:34)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:205)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:203)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:133)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:63)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElementGen(ElementContainerImpl.java:170)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:188)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:660)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:624)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:786)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:400)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1260)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3195)
	at org.eclipse.ui.internal.WorkbenchPage.lambda$9(WorkbenchPage.java:3100)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3098)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3068)
	at org.eclipse.ui.actions.OpenWithMenu.openEditor(OpenWithMenu.java:324)
	at org.eclipse.ui.actions.OpenWithMenu.lambda$0(OpenWithMenu.java:181)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5831)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5092)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4570)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1434)
```
Eclipse :
Version: 2021-03 (4.19.0)
Build id: 20210312-0638

OS Ubuntu 20.04.2 LTS
I'm using Groovy compiler 2.5.14, i tried with 3.0.7, and 4.0.0, and got the same error.
And i use the groovy development tools 4.2.0

Any clues on what is going wrong ? Thanks in advance guys

**Comment by gtchaboussie** [comment]
After doing some more investigating, it seems that the problem comes from the calculTotal function.
With this syntax : 
```groovy
def calculTotals(List purchaseOrdeMaps) {
    //Create the total Quantity/Amount map with currencyUom as key
    HashMap<String, HashMap<String, BigDecimal>> totalMap = [:]

    purchaseOrdeMaps.forEach() {
        Map purchaseOrderMap ->
            if (!('ORDER_CANCELLED' != parameters.statusId && 'ORDER_CANCELLED' == purchaseOrderMap.statusId)) {
                Map<String, BigDecimal> total = totalMap.get(purchaseOrderMap.currencyUom)
                BigDecimal searchTotalQuantity
                BigDecimal searchTotalAmount
                if (total) {
                    searchTotalQuantity = purchaseOrderMap.totalQuantity.add(total.quantity)
                    searchTotalAmount = purchaseOrderMap.grandTotal.add(total.amount)
                } else {
                    total = [:]
                    searchTotalQuantity = (BigDecimal) purchaseOrderMap.totalQuantity
                    searchTotalAmount = (BigDecimal) purchaseOrderMap.grandTotal
                }
                total.quantity = searchTotalQuantity
                total.amount = searchTotalAmount
                String test = purchaseOrderMap.currencyUom.toString()
                totalMap.(test) = total
            }
    }
    return totalMap
}
```
of this syntax :
```groovy
def calculTotals(List purchaseOrdeMaps) {
    //Create the total Quantity/Amount map with currencyUom as key
    HashMap<String, HashMap<String, BigDecimal>> totalMap = [:]

    purchaseOrdeMaps.forEach() {
        Map purchaseOrderMap()
        { ->
            if (!('ORDER_CANCELLED' != parameters.statusId && 'ORDER_CANCELLED' == purchaseOrderMap.statusId)) {
                Map<String, BigDecimal> total = totalMap.get(purchaseOrderMap.currencyUom)
                BigDecimal searchTotalQuantity
                BigDecimal searchTotalAmount
                if (total) {
                    searchTotalQuantity = purchaseOrderMap.totalQuantity.add(total.quantity)
                    searchTotalAmount = purchaseOrderMap.grandTotal.add(total.amount)
                } else {
                    total = [:]
                    searchTotalQuantity = (BigDecimal) purchaseOrderMap.totalQuantity
                    searchTotalAmount = (BigDecimal) purchaseOrderMap.grandTotal
                }
                total.quantity = searchTotalQuantity
                total.amount = searchTotalAmount
                totalMap.(purchaseOrderMap.currencyUom.toString()) = total
            }
        } as Map
    }
    return totalMap
}
```
The groovy editor works.
The difference is between the declaration of purchaseOrderMap and the totalMap inside of it.

**Comment by eric-milles** [comment]
I'm guessing it has something to do with your use of dynamic property syntax.  I do not see this too often in practice.  I have seen it in the grammar though.
```groovy
String test = purchaseOrderMap.currencyUom.toString()
totalMap.(test) = total
  // or
totalMap.(purchaseOrderMap.currencyUom.toString()) = total
```

Could you try re-writing these lines like this to see if the error goes away?
```groovy
totalMap.put(purchaseOrderMap.currencyUom.toString(), total)
  // or
totalMap[purchaseOrderMap.currencyUom.toString()] = total
```


Also, I do not understand this part:
```groovy
purchaseOrdeMaps.forEach() {
        Map purchaseOrderMap()
        { ->
```

It looks like you are running a closure but the argument is followed by parens and then another closure.

**Comment by gtchaboussie** [comment]
Hi, thanks for the response 
```groovy
totalMap.put(purchaseOrderMap.currencyUom.toString(), total)
  // or
totalMap[purchaseOrderMap.currencyUom.toString()] = total
```
Both works, and fot the last item, it's a syntax a coworker found

**Comment by gtchaboussie** [comment]
And the update seems to have solved the issue, thanks a lot !

**Comment by eric-milles** [comment]
Glad to hear it is working now.  If you don't mind, do you have any more examples of the ".forEach() { Map purchaseOrderMap() { ->" style?

Also, instead of ".forEach() {", you can use ".each {" which is more direct in terms of using your closure instead of adapting your closure to a functional interface.

**Comment by gtchaboussie** [comment]
Sadly i don't have other examples. We found the syntax here though:
https://stackoverflow.com/questions/26457622/groovy-equivalent-for-java-8-lambda-expression

And thanks for the advice. We will let our team know !

**Comment by eric-milles** [comment]
In your case, you do not appear to be creating a "function" to return, but are populating a map.  One suggestion I can make for clarity is to use "inject" when building up a map where you appear to be grouping.  There is a "groupBy" by it creates a list of values.  Also you can leverage `Map#getOrDefault` to replace the if/else.

```groovy
Map<String, Map<String, BigDecimal>> calculateTotals(List<Map> purchaseOrders) {
  purchaseOrders.inject([:]) { totals, purchaseOrder ->
    if (!('ORDER_CANCELLED' != parameters.statusId && 'ORDER_CANCELLED' == purchaseOrder.statusId)) {
      String key = purchaseOrder.currencyUom
      Map<String, BigDecimal> total = totals.getOrDefault(key, [quantity: 0g, amount: 0g])
      total.quantity += purchaseOrder.totalQuantity
      total.amount += purchaseOrder.grandTotal
    }
    totals
  }
}
```
