### ISSUE TITLE
java.lang.NoClassDefFoundError: org/codehaus/jdt/groovy/integration/LanguageSupportFactory

### ISSUE THREAD

**Issue by felixdo** [groovy/groovy-eclipse#1264]
Hi, when I clean my projects, I get a builder error:

java.lang.NoClassDefFoundError: org/codehaus/jdt/groovy/integration/LanguageSupportFactory
	at org.codehaus.groovy.eclipse.core.compiler.CompilerCleanerParticipant.isActive(CompilerCleanerParticipant.java:36)
	at org.eclipse.jdt.internal.core.JavaModelManager$CompilationParticipants.getCompilationParticipants(JavaModelManager.java:473)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.initializeBuilder(JavaBuilder.java:628)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:181)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:846)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:229)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:277)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:330)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)

This is using the latest release/snapshots for e4.19

**Comment by felixdo** [comment]
Sorry, I fixed it by installing the latest snapshot. When I update to a new eclipse, I leave the old update sites for groovy-eclipse and just add the new one. This doesn't seem to work well, I had to remove the old update sites and only add the correct one.
