### ISSUE TITLE
can't install Groovy Eclipse 4.2.0.SNAPSHOT even on Eclipse 4.19. (2021-03) Build  20210312-0638

### ISSUE THREAD

**Issue by vnayfeld** [groovy/groovy-eclipse#1271]
Hello, 
I am stuck in Installation of Groovy causes Eclipse to throw exception, while it is provisioning operation.

Attached are Screenshots of 
1. Eclipse is running provisioning
2. Message pop-up
3. Event Details

Just copying stack trace of the 3rd Screenshot in the text form

java.lang.IllegalStateException: operation plan must be resolved
	at org.eclipse.equinox.internal.p2.ui.ProvUI.toCurrentJREOperation(ProvUI.java:338)
	at org.eclipse.equinox.internal.p2.ui.ProvUI.toCompabilityWithCurrentJREProvisioningPlan(ProvUI.java:325)
	at org.eclipse.epp.internal.mpc.ui.wizards.MarketplaceWizard.lambda$5(MarketplaceWizard.java:876)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

Thank you in advance for any suggestions.

![Eclipse_Provisioning_ScreenShot](https://user-images.githubusercontent.com/22331711/122657894-67360f00-d135-11eb-8119-c61f5578d704.png)

![Problem_Message_Screenshot](https://user-images.githubusercontent.com/22331711/122657897-6bfac300-d135-11eb-8ac8-dff91d7dab24.png)

![Event_Details_Screenshot](https://user-images.githubusercontent.com/22331711/122657899-7026e080-d135-11eb-89fb-0a2e044d1cde.png)

**Comment by vnayfeld** [comment]
Actually, a problem is less severe than I thought first.
Provisioning did throw an exception,  but after that a screen described by an issue
[https://github.com/groovy/groovy-eclipse/issues/1237#issuecomment-822766264]
has been produced and I was able to install a feature.
If it Is it a normal behavior to throw an exception it is better to be documented.
