### ISSUE TITLE
Eclipse 2020-06 hangs on every modification of code in groovy editor 

### ISSUE THREAD

**Issue by godfuture** [groovy/groovy-eclipse#1279]
I am writing a script with project references to our companys business objects. When doing code changes or switching tab, Eclipse is freezing for many seconds.

This is logged many times a second:
```
java.lang.NullPointerException
	at org.codehaus.jdt.groovy.internal.compiler.ast.JDTAnnotationNode.<init>(JDTAnnotationNode.java:51)
	at org.codehaus.jdt.groovy.internal.compiler.ast.JDTClassNode.getAnnotations(JDTClassNode.java:497)
	at org.codehaus.groovy.ast.ClassNode.getAnnotations(ClassNode.java:1530)
	at org.codehaus.groovy.eclipse.dsl.pointcuts.impl.FindAnnotationPointcut.explodeObject(FindAnnotationPointcut.java:68)
	at org.codehaus.groovy.eclipse.dsl.pointcuts.impl.FindAnnotationPointcut.explodeObject(FindAnnotationPointcut.java:47)
	at org.codehaus.groovy.eclipse.dsl.pointcuts.impl.FilteringPointcut.matches(FilteringPointcut.java:48)
	at org.codehaus.groovy.eclipse.dsl.pointcuts.AbstractPointcut.matchOnPointcutArgument(AbstractPointcut.java:124)
	at org.codehaus.groovy.eclipse.dsl.pointcuts.impl.CurrentTypePointcut.matches(CurrentTypePointcut.java:64)
	at org.codehaus.groovy.eclipse.dsl.DSLDStore.findContributions(DSLDStore.java:146)
	at org.codehaus.groovy.eclipse.dsl.lookup.DSLDTypeLookup.lookupTypeAndDeclaration(DSLDTypeLookup.java:86)
	at org.eclipse.jdt.groovy.search.AbstractSimplifiedTypeLookup.lookupType(AbstractSimplifiedTypeLookup.java:144)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.lookupExpressionType(TypeInferencingVisitorWithRequestor.java:2759)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.getMethodCallArgumentTypes(TypeInferencingVisitorWithRequestor.java:2366)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.getMethodCallArgumentTypes(TypeInferencingVisitorWithRequestor.java:2364)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.lambda$27(TypeInferencingVisitorWithRequestor.java:2350)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.getMethodCallArgumentTypes(TypeInferencingVisitorWithRequestor.java:2363)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.handleSimpleExpression(TypeInferencingVisitorWithRequestor.java:2018)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.handleSimpleExpression(TypeInferencingVisitorWithRequestor.java:2029)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitConstantExpression(TypeInferencingVisitorWithRequestor.java:1004)
	at org.codehaus.groovy.ast.expr.ConstantExpression.visit(ConstantExpression.java:86)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitMethodCallExpression(TypeInferencingVisitorWithRequestor.java:1484)
	at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:77)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:117)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitExpressionStatement(ClassCodeVisitorSupport.java:252)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitExpressionStatement(TypeInferencingVisitorWithRequestor.java:1141)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:86)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:216)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitBlockStatement(TypeInferencingVisitorWithRequestor.java:870)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitForLoop(TypeInferencingVisitorWithRequestor.java:1249)
	at org.codehaus.groovy.ast.stmt.ForStatement.visit(ForStatement.java:47)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:86)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:216)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitBlockStatement(TypeInferencingVisitorWithRequestor.java:870)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:165)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitConstructorOrMethod(TypeInferencingVisitorWithRequestor.java:1111)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitMethodInternal(TypeInferencingVisitorWithRequestor.java:658)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitJDT(TypeInferencingVisitorWithRequestor.java:466)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitJDT(TypeInferencingVisitorWithRequestor.java:375)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitCompilationUnit(TypeInferencingVisitorWithRequestor.java:255)
	at org.codehaus.groovy.eclipse.editor.highlighting.GatherSemanticReferences.findSemanticHighlightingReferences(GatherSemanticReferences.java:43)
	at org.codehaus.groovy.eclipse.editor.highlighting.GroovySemanticReconciler.reconciled(GroovySemanticReconciler.java:288)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor.reconciled(CompilationUnitEditor.java:1691)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconciled(JavaReconcilingStrategy.java:222)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconciled(JavaCompositeReconcilingStrategy.java:167)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconcile(JavaCompositeReconcilingStrategy.java:115)
	at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:76)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:210)
```

**Comment by eric-milles** [comment]
Could you please update to the latest release or snapshot?  There is null handling in the current codebase for this case:
https://github.com/groovy/groovy-eclipse/blob/v4.2.0/base/org.eclipse.jdt.groovy.core/src/org/codehaus/jdt/groovy/internal/compiler/ast/JDTClassNode.java#L498
https://github.com/groovy/groovy-eclipse/blob/ad5c02e81d40ba2b6dc57574dcaec590767afaae/base/org.eclipse.jdt.groovy.core/src/org/codehaus/jdt/groovy/internal/compiler/ast/JDTResolver.java#L471
https://github.com/groovy/groovy-eclipse/blob/ad5c02e81d40ba2b6dc57574dcaec590767afaae/base/org.codehaus.groovy25/src/org/codehaus/groovy/ast/AnnotatedNode.java#L55
