### ISSUE TITLE
Eclipse marketplace error

### ISSUE THREAD

**Issue by venushka** [groovy/groovy-eclipse#1284]
Seems like Eclipse marketplace reporting an error for all the update sites: https://www.eclipse.org/setups/marketplace/?id=321859

I've tried installing 2020-03 and 2021-03, both throw the following error (and its the same reported in the marketplace)

```
            Cannot complete the install because one or more required items could not be found.
              - Software being installed: artificial_root 1.0.0.v1627091378307
              - Missing requirement: Eclipse JDT Core patch for Groovy 4.2.0.v202106301418-e2103-RELEASE (org.codehaus.groovy.jdt.patch.feature.group 4.2.0.v202106301418-e2103-RELEASE) requires 'org.eclipse.equinox.p2.iu; org.eclipse.jdt.feature.group [3.18.700.v20210303-1800,3.18.700.v20210303-1800]' but it could not be found
              - Cannot satisfy dependency:
                - From: artificial_root 1.0.0.v1627091378307
                - To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.eclipse.feature.feature.group [4.2.0.v202106301418-e2103-RELEASE,4.2.0.v202106301418-e2103-RELEASE]
              - Cannot satisfy dependency:
                - From: Groovy-Eclipse Compilerless feature 4.2.0.v202106301418-e2103-RELEASE (org.codehaus.groovy.compilerless.feature.feature.group 4.2.0.v202106301418-e2103-RELEASE)
                - To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.headless.feature.feature.group [4.2.0.v202106301418-e2103-RELEASE,4.2.0.v202106301418-e2103-RELEASE]
              - Cannot satisfy dependency:
                - From: Eclipse Groovy Development Tools 4.2.0.v202106301418-e2103-RELEASE (org.codehaus.groovy.eclipse.feature.feature.group 4.2.0.v202106301418-e2103-RELEASE)
                - To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.compilerless.feature.feature.group [4.2.0.v202106301418-e2103-RELEASE,4.2.0.v202106301418-e2103-RELEASE]
              - Cannot satisfy dependency:
                - From: Groovy-Eclipse Headless feature 4.2.0.v202106301418-e2103-RELEASE (org.codehaus.groovy.headless.feature.feature.group 4.2.0.v202106301418-e2103-RELEASE)
                - To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.jdt.patch.feature.group [4.2.0.v202106301418-e2103-RELEASE,4.2.0.v202106301418-e2103-RELEASE]

            org.eclipse.core.runtime.CoreException: Cannot complete the install because one or more required items could not be found.
            	at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:291)
            	at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:430)
            	at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:899)
            	at org.eclipse.oomph.setup.internal.installer.MarketplaceCatalogGenerator$3.run(MarketplaceCatalogGenerator.java:1073)
            	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
            	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            	at java.base/java.lang.Thread.run(Thread.java:834)
            Contains: Software being installed: artificial_root 1.0.0.v1627091378307
            Contains: Missing requirement: Eclipse JDT Core patch for Groovy 4.2.0.v202106301418-e2103-RELEASE (org.codehaus.groovy.jdt.patch.feature.group 4.2.0.v202106301418-e2103-RELEASE) requires 'org.eclipse.equinox.p2.iu; org.eclipse.jdt.feature.group [3.18.700.v20210303-1800,3.18.700.v20210303-1800]' but it could not be found
            Contains: Cannot satisfy dependency:
            Contains: From: artificial_root 1.0.0.v1627091378307
            Contains: To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.eclipse.feature.feature.group [4.2.0.v202106301418-e2103-RELEASE,4.2.0.v202106301418-e2103-RELEASE]
            Contains: Cannot satisfy dependency:
            Contains: From: Groovy-Eclipse Compilerless feature 4.2.0.v202106301418-e2103-RELEASE (org.codehaus.groovy.compilerless.feature.feature.group 4.2.0.v202106301418-e2103-RELEASE)
            Contains: To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.headless.feature.feature.group [4.2.0.v202106301418-e2103-RELEASE,4.2.0.v202106301418-e2103-RELEASE]
            Contains: Cannot satisfy dependency:
            Contains: From: Eclipse Groovy Development Tools 4.2.0.v202106301418-e2103-RELEASE (org.codehaus.groovy.eclipse.feature.feature.group 4.2.0.v202106301418-e2103-RELEASE)
            Contains: To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.compilerless.feature.feature.group [4.2.0.v202106301418-e2103-RELEASE,4.2.0.v202106301418-e2103-RELEASE]
            Contains: Cannot satisfy dependency:
            Contains: From: Groovy-Eclipse Headless feature 4.2.0.v202106301418-e2103-RELEASE (org.codehaus.groovy.headless.feature.feature.group 4.2.0.v202106301418-e2103-RELEASE)
            Contains: To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.jdt.patch.feature.group [4.2.0.v202106301418-e2103-RELEASE,4.2.0.v202106301418-e2103-RELEASE]
```

Some screenshots from the marketplace for reference:

![errors-listing](https://user-images.githubusercontent.com/4840772/126880152-44f669a6-53ea-4b49-9502-5e4a0da16b94.png)

![error-detail](https://user-images.githubusercontent.com/4840772/126880181-b2cf4786-3089-4178-b56c-f45cf0ae0bab.png)

**Comment by jeacott1** [comment]
yeah my entire eclipse went pearshaped today and after trying everything I could think of I started from a fresh new eclipse install.
groovy development tools will not install.
```
Cannot complete the install because some dependencies are not satisfiable
  Software being installed: Eclipse Groovy Development Tools 4.2.0.v202106301814-e2106-RELEASE (org.codehaus.groovy.eclipse.feature.feature.group 4.2.0.v202106301814-e2106-RELEASE)
  Software currently installed: m2e - slf4j over logback logging (Optional) 1.17.1.20210603-1006 (org.eclipse.m2e.logback.feature.feature.group 1.17.1.20210603-1006)
  Cannot satisfy dependency:
    From: Groovy-Eclipse Compilerless feature 4.2.0.v202106301814-e2106-RELEASE (org.codehaus.groovy.compilerless.feature.feature.group 4.2.0.v202106301814-e2106-RELEASE)
    To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.headless.feature.feature.group [4.2.0.v202106301814-e2106-RELEASE,4.2.0.v202106301814-e2106-RELEASE]
  Cannot satisfy dependency:
    From: Groovy Compiler Resolver 4.2.0.v202106301814-e2106-RELEASE (org.codehaus.groovy.eclipse.compilerResolver 4.2.0.v202106301814-e2106-RELEASE)
    To: org.eclipse.equinox.p2.iu; ch.qos.logback.classic 0.0.0
  Cannot satisfy dependency:
    From: Eclipse Groovy Development Tools 4.2.0.v202106301814-e2106-RELEASE (org.codehaus.groovy.eclipse.feature.feature.group 4.2.0.v202106301814-e2106-RELEASE)
    To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.compilerless.feature.feature.group [4.2.0.v202106301814-e2106-RELEASE,4.2.0.v202106301814-e2106-RELEASE]
  Cannot satisfy dependency:
    From: Groovy-Eclipse Headless feature 4.2.0.v202106301814-e2106-RELEASE (org.codehaus.groovy.headless.feature.feature.group 4.2.0.v202106301814-e2106-RELEASE)
    To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.eclipse.compilerResolver [4.2.0.v202106301814-e2106-RELEASE,4.2.0.v202106301814-e2106-RELEASE]
  Cannot satisfy dependency:
    From: m2e logback configuration 1.16.1.20210603-1006 (org.eclipse.m2e.logback.configuration 1.16.1.20210603-1006)
    To: osgi.bundle; ch.qos.logback.classic 0.9.24
  Cannot satisfy dependency:
    From: m2e - slf4j over logback logging (Optional) 1.17.1.20210603-1006 (org.eclipse.m2e.logback.feature.feature.group 1.17.1.20210603-1006)
    To: org.eclipse.equinox.p2.iu; org.eclipse.m2e.logback.configuration [1.16.1.20210603-1006,1.16.1.20210603-1006]
```

**Comment by eric-milles** [comment]
The marketplace self-test has been in this state for a while now (#1218).  They are not including JDT even though the patch feature declares a dependency.

I'm unclear from your description if you have JDT installed.  Which eclipse package did you start from?  A quick screenshot of your installed features would be helpful for me.

**Comment by venushka** [comment]
Hi @eric-milles, thanks for getting back so quickly.

The installation we use is an Oomph setup file we've maintained over the years, which includes all the plugins we need, code templates, JRE configurations, etc. for developers. The install was working till quite recently and then stopped working.

This is a screenshot of installed features from an instance of Eclipse when it worked using the same installer.
<img width="997" alt="eclipse-installed-features" src="https://user-images.githubusercontent.com/4840772/127009576-f9feaf1a-d92c-4d33-ba99-9cc5417c9fd3.png">

Please let me know if there's anything else I can do to help, or anything I can try out.

**Comment by eric-milles** [comment]
In this instance, you have both JDT and GDT installed.  When you were running into errors, what did you start from?  I'm not sure how Oomph handles installing a feature (JDT) and a patch for that feature at the same time.  That may be what keeps the update site health checks from working.

**Comment by venushka** [comment]
I've started from standard installer, using our own catalog setup file, which is has been evolved over time. The P2 Directory installs the features.

As you mentioned JDT dependency, thought I might be able to figure it out by trying to update Groovy Development Tools in the working install and I got these options.

<img width="1189" alt="install-error" src="https://user-images.githubusercontent.com/4840772/127013979-a224d83f-e67c-432c-80c4-fc2746ab3c65.png">
<img width="1187" alt="install-fix-forward" src="https://user-images.githubusercontent.com/4840772/127013981-01ce57c7-ff00-46b9-8916-4230fae0162d.png">
<img width="1187" alt="install-keep" src="https://user-images.githubusercontent.com/4840772/127013982-fe8ab83a-e5d9-4156-807b-e4faec65a2c6.png">

Looks like logback in m2e was the thing that was causing the issue. I've continued the update selecting the option that uninstalled logback and installation went fine.

Now the features looks like this.
<img width="1152" alt="eclipse-features-post-install" src="https://user-images.githubusercontent.com/4840772/127015573-c4e3173f-48a8-4483-b20b-2c8000c43e05.png">

Seems all groovy features works fine. I've removed the logback feature from our Oomph setup file and a fresh install went through as well.

Thanks for your help!

This could be the issue with Eclipse marketplace as well, they might be installing logback for m2e by default.

**Comment by eric-milles** [comment]
There are some discussions of the `logback-classic` compatibility in other issue tickets.  I had hoped the dialog choices would be self-explanatory; the "Update my installation to be compatible ..." should be the safest choice.  I have some experiments in progress that could mitigate logback's optional groovy usage.

**Comment by jeacott1** [comment]
I started from a brand new eclipse java for web install. same issue. but then I found the instruction to abandon m2e.
not ideal, but better than utterly broken.
