### ISSUE TITLE
groovy-eclipse-batch 4.0.5-02 issues

### ISSUE THREAD

**Issue by cstamas** [groovy/groovy-eclipse#1390]
Howdy, my project (uses groovy-eclipse-batch + groovy-eclipse-compiler) from Maven only (no Eclipse IDE involved) had following versions set, and project was all fine:
* groovy 4.0.5
* groovy-eclipse-compiler 3.7.1
* groovy-eclipse-batch 4.0.4-01

Java 17 Temurin on Linux.

As groovy-eclipse-batch 4.0.5-02 popped up as release, went to update it (so that was the ONLY change in project, again, before this change all was fine). With this change, project got several issues:

1) source that was previously okay, suddenly was broken with new compiler:
```
[INFO] --- maven-compiler-plugin:3.10.1:testCompile (default-testCompile) @ px-modern-testsuite ---
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
[INFO] incorrect classpath: /XXXX/px-modern-testsuite/target/classes
[INFO] 2 problems (2 errors)
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /XXX.groovy:[384,13] 
1. ERROR in /XXX (at line 384)
	@QueryParam('q') String query)
	            ^^^
Type mismatch: cannot convert from char to String
[ERROR] /YYYY.groovy:[315,7] 
2. ERROR in /YYYY.groovy (at line 315)
	@Path('/')
	      ^^^
Type mismatch: cannot convert from char to String
[ERROR] Found 2 errors and 0 warnings.
[INFO] 3 errors 

```

So, compiler 4.0.4-01 was fine with `@Path('/')`, but now it considers as Java char. Is this Groovy or compiler change?

2) maven-compiler-plugin phase emits errors (originating from groovy compiler), does not fail build but pollutes console output, example:
```
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ px-zum-plugin ---
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
Failed to init Classpath for jar file /XXX/.m2/repository/org/apache/groovy/groovy-all/4.0.5/groovy-all-4.0.5.pom
java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at org.eclipse.jdt.internal.compiler.batch.ClasspathJar.initialize(ClasspathJar.java:204)
	at org.eclipse.jdt.internal.compiler.batch.ClasspathMultiReleaseJar.initialize(ClasspathMultiReleaseJar.java:38)
	at org.eclipse.jdt.internal.compiler.batch.FileSystem.<init>(FileSystem.java:235)
	at org.eclipse.jdt.internal.compiler.batch.Main.getLibraryAccess(Main.java:3545)
	at org.eclipse.jdt.internal.compiler.batch.Main.performCompilation(Main.java:4791)
	at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1809)
	at org.codehaus.groovy.eclipse.compiler.InternalCompiler.doCompile(InternalCompiler.java:84)
	at org.codehaus.groovy.eclipse.compiler.GroovyEclipseCompiler.performCompile(GroovyEclipseCompiler.java:123)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1209)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:198)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] 
```

Is 4.0.5-02 planned to have successor?

TIA

**Comment by eric-milles** [comment]
[GROOVY-9206](https://issues.apache.org/jira/browse/GROOVY-9206) was the reason for the change to single-character, single-quotes string literals.  Here is the commit: https://github.com/groovy/groovy-eclipse/commit/6d80c05befec9aa5a1863d4cdb4f5387c1823d41.  When generating "stub" information for joint compilation, the annotation type is not yet resolved so there is no way to disambiguate char and string targets.  You can use double-quotes in these cases.

As for the classpath treating pom as zip, I don't know what your project's classpath looks like in maven.  I'm guessing you have a `dependency` declared for groovy-all with packaging `pom`.  I'd have to check with `groovy-eclipse-compiler` to see how this gets represented to the batch compiler.

**Comment by cstamas** [comment]
Roger that, but one interesting thing: Project _did use 4.0.4_, but it worked okay, so JIRA might have wrong FixFor assigned? As my issues as in description started happening when I updated to 4.0.5 compiler...

**Comment by eric-milles** [comment]
It wasn't until post-4.0.4 when this was tested and an adjustment was required on the groovy-eclipse side.

**Comment by eric-milles** [comment]
Sorry for the trouble with the annotations.  I was left with a choice of not supporting `char` attributes as the vanilla compiler does or using a heuristic to detect "chars".  I'll be sure to add something to the 4.7.0 release notes for this.

`groovy-eclipse-compiler` 3.8.0 excludes the pom file(s) from your classpath, so you should not see the zip file errors any longer.

**Comment by cstamas** [comment]
Howdy, thanks for new release! (both 4.0.5-02 and 3.8.0).

With these changes all is cool.

1. Our annotations with plain `'a'` strings changed to `"a"` GStrings and is ok
2. The warning from maven-compiler-plugin is gone.
