### ISSUE TITLE
Several issues with import statements

### ISSUE THREAD

**Issue by eric-milles** [groovy/groovy-eclipse#1391]
A few items to clean up:

1. Alias imports do not show alias name in Outline view
    ```groovy
    import java.util.regex.Pattern as Regexp
    ```
    ![image](https://user-images.githubusercontent.com/18193802/190927853-cef66f87-37df-4957-a574-34d397c90fb3.png)
    
2. Static imports highlight "static " in editor when selected from Outline view
    ```groovy
    import static java.util.regex.Pattern.compile
    ```
    ![image](https://user-images.githubusercontent.com/18193802/191061592-3fe30c53-ad98-4f0c-99bb-e4236b2a97a1.png)
    
3. Static method imports with multiple overloads display last overload in hover and navigate to first overload
    Groovy editor:
    ![image](https://user-images.githubusercontent.com/18193802/191062452-842f551b-f2bf-4751-9e57-3af642785ba0.png)
    Java editor:
    ![image](https://user-images.githubusercontent.com/18193802/191062499-b7e3660a-7561-41d8-b161-f2a7d8c0318b.png)
    
4. Static imports with an alias display improper first line in hover
    With an alias:
    ![image](https://user-images.githubusercontent.com/18193802/191065119-a1ae9a3f-6702-4be6-b662-6dafc86ec9ef.png)
    Without an alias:
    ![image](https://user-images.githubusercontent.com/18193802/191065183-e6a21adb-93de-40a9-ba91-81c16e3bc0f2.png)
    
5. When adding imports using compiler config script, "import declarations" shows up before package in Outline view (with or without import statements, which come after the package statement)
    ```groovy
    withConfig(configuration) {
      imports {
        star 'java.util.function'
      }
    }
    ```
    ![image](https://user-images.githubusercontent.com/18193802/190927958-0f61572b-4537-4f46-8ef1-49ce2f32509e.png)
    
6. When adding imports using compiler config script, import statements lack collapse region
    no implicit imports:
    ![image](https://user-images.githubusercontent.com/18193802/190928158-16ce0227-b043-41bb-b6f1-df1c4242c104.png)
    with implicit imports:
    ![image](https://user-images.githubusercontent.com/18193802/190928175-f93badd6-3cdd-409c-aa07-b3588875cb59.png)
    
7. When adding imports using compiler config script, Organize Imports (Ctrl+Shift+O) fails for source unit in default package
    ```
    org.eclipse.core.runtime.AssertionFailedException: assertion failed: 
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:113)
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:99)
	at org.eclipse.text.edits.TextEdit.<init>(TextEdit.java:153)
	at org.eclipse.text.edits.ReplaceEdit.<init>(ReplaceEdit.java:39)
	at org.eclipse.jdt.internal.core.dom.rewrite.imports.ImportEditor.createTextEdit(ImportEditor.java:200)
	at org.eclipse.jdt.internal.core.dom.rewrite.imports.ImportRewriteAnalyzer.analyzeRewrite(ImportRewriteAnalyzer.java:568)
	at org.eclipse.jdt.core.dom.rewrite.ImportRewrite.rewriteImports(ImportRewrite.java:1359)
	at org.codehaus.groovy.eclipse.refactoring.actions.OrganizeGroovyImports.calculateMissingImports(OrganizeGroovyImports.java:258)
	at org.codehaus.groovy.eclipse.refactoring.actions.OrganizeGroovyImports.calculateAndApplyMissingImports(OrganizeGroovyImports.java:112)
	at org.codehaus.groovy.eclipse.refactoring.actions.OrganizeGroovyImportsAction.run(OrganizeGroovyImportsAction.java:68)
	at org.eclipse.jdt.ui.actions.OrganizeImportsAction.run(OrganizeImportsAction.java:206)
    ```

**Comment by eric-milles** [comment]
![image](https://user-images.githubusercontent.com/18193802/191156525-353fd086-8e48-4111-972a-a1bfb9e767e6.png)
