### ISSUE TITLE
Editor doesn't add import statements

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#1410]
I am using Eclipse 4.24. I updated from the 2022-10-14 snapshot to the 2022-10-17 today, and it appears that imports are no longer added. This happens whether I use autocomplete, Organize Imports, or Quick Fix a red line—all of them behave normally (the usual popups or whatever), but the import statement isn't added to the code.

Build version: 4.8.0.v202210172215-e2206

**Edit**: This appears to be intermittent in that it only applies to certain files, but it's reliable in applying to those files. The presence of closures (maybe nested closures?) seems to be involved.

**Comment by eric-milles** [comment]
Are there any entries in the Error Log view or the Groovy Event Console?  Can you break it down to a small sample?

**Comment by chrylis** [comment]
I'm not certain if these are causally related, but I'm getting two errors spammed into the log. One is ostensibly an error in _Lombok_, which is not used in the project being compiled, but I'm wondering if there's something going on with the Core JDT Patch:
```
!ENTRY org.eclipse.jdt.core.manipulation 4 0 2022-10-18 17:39:08.858
!MESSAGE Error in JDT Core during AST creation
!STACK 0
java.lang.IllegalArgumentException: startPos = -2 and length is 1.
This breaks the rule that length must be 0 if startPosition is negative. Affected Node:
class org.eclipse.jdt.core.dom.Block: {
}

	at lombok.eclipse.agent.PatchDiagnostics.setSourceRangeCheck(PatchDiagnostics.java:43)
	at org.eclipse.jdt.core.dom.ASTNode.setSourceRange(ASTNode.java)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:845)
	at org.eclipse.jdt.core.dom.ASTConverter.buildBodyDeclarations(ASTConverter.java:218)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:3461)
	at org.eclipse.jdt.core.dom.ASTConverter.buildBodyDeclarations(ASTConverter.java:228)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:3461)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:1596)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.convert(CompilationUnitResolver.java:347)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1272)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:868)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider$1.run(CoreASTProvider.java:294)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.createAST(CoreASTProvider.java:286)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.getAST(CoreASTProvider.java:199)
	at org.eclipse.jdt.core.manipulation.SharedASTProviderCore.getAST(SharedASTProviderCore.java:138)
	at org.eclipse.jdt.ui.OverrideIndicatorLabelDecorator.getOverrideIndicators(OverrideIndicatorLabelDecorator.java:161)
	at org.eclipse.jdt.ui.OverrideIndicatorLabelDecorator.computeAdornmentFlags(OverrideIndicatorLabelDecorator.java:136)
	at org.eclipse.jdt.ui.OverrideIndicatorLabelDecorator.decorate(OverrideIndicatorLabelDecorator.java:263)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition.decorate(LightweightDecoratorDefinition.java:254)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager$LightweightRunnable.run(LightweightDecoratorManager.java:105)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.decorate(LightweightDecoratorManager.java:360)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.getDecorations(LightweightDecoratorManager.java:346)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.queue(DecorationScheduler.java:419)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.run(DecorationScheduler.java:397)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I'm also getting this, which may be unrelated (but "background indexer" smells like the sort of thing that could be involved in import manipulation); I recently changed an annotation collector to use `PREFER_EXPLICIT_MERGED` but am getting an error that suggests it's not being observed by GRECLIPSE:
```
!ENTRY org.eclipse.jdt.core 4 4 2022-10-19 11:14:15.220
!MESSAGE Background Indexer Crash Recovery
!STACK 0
BUG! Annotation member defaults has already been added
	at org.codehaus.groovy.ast.AnnotationNode.addMember(AnnotationNode.java:93)
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitDeclaration$UnitPopulator.lambda$9(GroovyCompilationUnitDeclaration.java:2960)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitDeclaration$UnitPopulator.getDeclaredAndGeneratedConstructors(GroovyCompilationUnitDeclaration.java:2960)
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitDeclaration$UnitPopulator.createConstructorDeclarations(GroovyCompilationUnitDeclaration.java:1377)
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitDeclaration$UnitPopulator.createConstructorAndMethodDeclarations(GroovyCompilationUnitDeclaration.java:1368)
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitDeclaration$UnitPopulator.createTypeDeclarations(GroovyCompilationUnitDeclaration.java:1155)
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitDeclaration$UnitPopulator.populate(GroovyCompilationUnitDeclaration.java:926)
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitDeclaration.populateCompilationUnitDeclaration(GroovyCompilationUnitDeclaration.java:312)
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyParser.dietParse(GroovyParser.java:257)
	at org.codehaus.jdt.groovy.integration.internal.MultiplexingIndexingParser.parseCompilationUnit(MultiplexingIndexingParser.java:63)
	at org.eclipse.jdt.internal.core.search.indexing.SourceIndexer.indexDocument(SourceIndexer.java:115)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.indexDocument(JavaSearchParticipant.java:83)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.indexDocument(IndexManager.java:670)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager$2.execute(IndexManager.java:1304)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.run(JobManager.java:446)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by eric-milles** [comment]
The second error comes from the recent change to apply `TupleConstructorASTTransformation` early.  You must be using `@Immutable`.  Here is the bit circa line 2960:
```java
                        AnnotationNode anno = new AnnotationNode(ClassHelper.make(groovy.transform.TupleConstructor.class));
                        if (isType("groovy.transform.Immutable", annotationType))
                            anno.addMember("defaults", ConstantExpression.FALSE);
                        attributes.forEach((name, value) -> anno.addMember(name, value));
```

**Comment by eric-milles** [comment]
The first error is one of source offsets and is usually what stops things like import edits from working properly.  Start -2 indicates a hidden element, usually a generated one.

Fix for second error is building.

**Comment by eric-milles** [comment]
It would be helpful if you could grab the latest snapshot and let me know if the "defaults" problem is fixed.  Then I would just need you to comment out members of an affected class until it is reduced to minimal elements.

**Comment by chrylis** [comment]
On 4.8.0.v202211022217-e2206 (Eclipse 4.24), `@Canonical` by itself appears sufficient to trigger the bug, which also seems to squash most syntax highlighting (the stuff dependent on linking, looks like).

**Comment by chrylis** [comment]
```
Exception occurred during compilation unit conversion:
----------------------------------- SOURCE BEGIN -------------------------------------
package com.example.scaffold

import groovy.transform.Canonical

@Canonical
class EclipseJdt {
}

----------------------------------- SOURCE END -------------------------------------
```

```
java.lang.IllegalArgumentException: startPos = -2 and length is 1.
This breaks the rule that length must be 0 if startPosition is negative. Affected Node:
class org.eclipse.jdt.core.dom.Block: {
}

	at lombok.eclipse.agent.PatchDiagnostics.setSourceRangeCheck(PatchDiagnostics.java:43)
	at org.eclipse.jdt.core.dom.ASTNode.setSourceRange(ASTNode.java)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:845)
	at org.eclipse.jdt.core.dom.ASTConverter.buildBodyDeclarations(ASTConverter.java:218)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:3461)
	at org.eclipse.jdt.core.dom.ASTConverter.convert(ASTConverter.java:1596)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.convert(CompilationUnitResolver.java:347)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1272)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:868)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider$1.run(CoreASTProvider.java:294)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.createAST(CoreASTProvider.java:286)
	at org.eclipse.jdt.core.manipulation.CoreASTProvider.getAST(CoreASTProvider.java:199)
	at org.eclipse.jdt.core.manipulation.SharedASTProviderCore.getAST(SharedASTProviderCore.java:138)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup.calculateASTandInform(SelectionListenerWithASTManager.java:166)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup$1.run(SelectionListenerWithASTManager.java:151)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by eric-milles** [comment]
It is the _Lombok Agent_ that modifies the behavior of `ASTScanner`.  I'll see what I can do -- conversion works fine without it.

**Comment by chrylis** [comment]
Oh, I figured it was most probably a bug in Lombok itself, but between GRECLIPSE getting out of Lombok's way and Lombok getting fixed...

**Comment by eric-milles** [comment]
Should be fixed with latest snapshot

**Comment by chrylis** [comment]
I will look at this as soon as I can upgrade, but a team member reported #1415 as a compilation blocker, and I'm holding the update.
