### ISSUE TITLE
Compile cancel request not honored

### ISSUE THREAD

**Issue by efc-mw** [groovy/groovy-eclipse#1414]
Canceling a running build seems not possible. For example when closing Eclipse during compile run, pressing the red button has no effect, the groovy compiler still compiles new classes... But it seems not correct, there are lot of exceptions like:
```
!ENTRY org.eclipse.jdt.groovy.core 4 0 2022-10-31 14:19:13.993
!MESSAGE Groovy compiler error
!STACK 0
BUG! exception in phase 'semantic analysis' in source unit 'E:\projects\wug\server_env_actual\efc_server\src\groovy\de\effectivecompany\app\app\serviceimpl\SvEFCReportImpl.groovy' commencingResolution failed: no declaration found for class de.effectivecompany.app.app.serviceimpl.SvEFCReportImpl
	at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:935)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:707)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:681)
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitDeclaration.processToPhase(GroovyCompilationUnitDeclaration.java:232)
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitDeclaration.resolve(GroovyCompilationUnitDeclaration.java:615)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:918)
	at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.codehaus.jdt.groovy.internal.compiler.ast.GroovyEclipseBug: commencingResolution failed: no declaration found for class de.effectivecompany.app.app.serviceimpl.SvEFCReportImpl
	at org.codehaus.jdt.groovy.internal.compiler.ast.JDTResolver.commencingResolution(JDTResolver.java:227)
	at org.codehaus.groovy.control.ResolveVisitor.visitClass(ResolveVisitor.java:1376)
	at org.codehaus.groovy.control.ResolveVisitor.startResolving(ResolveVisitor.java:266)
	at org.codehaus.jdt.groovy.internal.compiler.ast.JDTResolver.startResolving(JDTResolver.java:197)
	at org.codehaus.groovy.control.CompilationUnit.lambda$4(CompilationUnit.java:215)
	at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:926)
	... 7 more
```

**Comment by eric-milles** [comment]
For each compilation unit (source file) the `ProcessTaskManager` reports progress, which includes checking for cancellation.
```java
				this.compiler.reportProgress(Messages.bind(Messages.compilation_processing, new String(this.unitToProcess.getFileName())));
				if (this.compiler.options.verbose)
					this.compiler.out.println(
						Messages.bind(Messages.compilation_process,
						new String[] {
							String.valueOf(index + 1),
							String.valueOf(this.compiler.totalUnits),
							new String(this.unitToProcess.getFileName())
						}));
				this.compiler.process(this.unitToProcess, index); // line 145

```

The progress monitor is `null` but that is a JDT issue that needs to be investigated.  You can revert to the old inline compilation by adding `-Djdt.compiler.useSingleThread=true` to your _eclipse.ini_
