### ISSUE TITLE
Index out of bounds in ScriptFolderSelector

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#1415]
In 4.8.0.v202211062218-e2206, the following error occurs on build ("error occured invoking Java Builder"):

```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.eclipse.jdt.core.compiler.CharOperation.pathMatch(CharOperation.java:3161)
	at org.eclipse.jdt.groovy.core.util.ScriptFolderSelector.getFileKind(ScriptFolderSelector.java:134)
	at org.eclipse.jdt.groovy.core.util.ScriptFolderSelector.isScript(ScriptFolderSelector.java:165)
	at org.eclipse.jdt.groovy.core.util.ScriptFolderSelector.isScript(ScriptFolderSelector.java:177)
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyParser.dietParse(GroovyParser.java:204)
	at org.codehaus.jdt.groovy.integration.internal.MultiplexingCommentRecorderParser.dietParse(MultiplexingCommentRecorderParser.java:51)
	at org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(Compiler.java:864)
	at org.eclipse.jdt.internal.compiler.Compiler.beginToCompile(Compiler.java:404)
	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1054)
	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1127)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:290)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:357)
	at org.codehaus.jdt.groovy.model.GroovyReconcileWorkingCopyOperation.makeConsistent(GroovyReconcileWorkingCopyOperation.java:80)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:94)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:740)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:806)
	at org.codehaus.jdt.groovy.model.GroovyCompilationUnit.reconcile(GroovyCompilationUnit.java:391)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:132)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:94)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:91)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:158)
	at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.reconcile(CompositeReconcilingStrategy.java:94)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconcile(JavaCompositeReconcilingStrategy.java:107)
	at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:76)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:207)
```

This occurs on a project with no DSLD folders.

**Comment by eric-milles** [comment]
What do your script filters look like?  You can check Groovy Compiler under project and global preferences.

**Comment by chrylis** [comment]
Screenshot from colleague with the problem: 
<img width="1210" alt="Screen Shot 2022-11-08 at 2 00 11 PM" src="https://user-images.githubusercontent.com/2394512/200700051-6f78cb16-3822-486b-929e-306f96e2878a.png">

**Comment by eric-milles** [comment]
What does the project's `.settings/org.eclipse.jdt.groovy.core.prefs` look like for the dev that is getting the error?

**Comment by chrylis** [comment]
```
eclipse.preferences.version=1
groovy.compiler.level=40
groovy.script.filters=,y,src/main/resources/**/*.groovy,y,src/test/resources/**/*.groovy,y
org.codehaus.groovy.eclipse.preferences.compiler.project=true
```

**Comment by eric-milles** [comment]
This is the source of the empty filter:

groovy.script.filters=,y
