### ISSUE TITLE
groovy-eclipse does not work on Mars SR1

### ISSUE THREAD

**Issue by seldor** [groovy/groovy-eclipse#143]
Hi

I've just installed groovy-eclipse from the snapshot update site in a fresh Mars SR1 installation.
However, upon restarting, I get a lot of errors in Eclipse, preventing compilation:

```
------
STATUS
------
pluginId            org.eclipse.jdt.ui
pluginVersion       3.11.1.v20150827-1306
code                2
severity            4
message             Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ui".
fingerprint         dd336c12

Exception:java.lang.ClassCastException: org.eclipse.jdt.internal.compiler.lookup.MethodBinding cannot be cast to org.eclipse.jdt.internal.compiler.lookup.SyntheticMethodBinding
     at org.eclipse.jdt.internal.compiler.lookup.ClassScope.buildMethods(ClassScope.java:405)
     at org.eclipse.jdt.internal.compiler.lookup.ClassScope.buildFieldsAndMethods(ClassScope.java:185)
     at HIDDEN.HIDDEN(HIDDEN:-1)
     at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.buildFieldsAndMethods(CompilationUnitScope.java:84)
     at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:253)
     at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:278)
     at org.eclipse.jdt.internal.compiler.Compiler.accept(Compiler.java:348)
     at org.eclipse.jdt.core.dom.CompilationUnitResolver.accept(CompilationUnitResolver.java:183)
     at org.eclipse.jdt.core.dom.CompilationUnitResolver.accept(CompilationUnitResolver.java:179)
     at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:186)
     at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:201)
     at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3239)
     at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:2946)
     at org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.getTypeBinding(SingleTypeReference.java:51)
     at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:496)
     at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:595)
     at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:591)
     at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:199)
     at org.eclipse.jdt.internal.compiler.ast.ForeachStatement.resolve(ForeachStatement.java:419)
     at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:641)
     at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:309)
     at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:551)
     at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1188)
     at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1301)
     at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:591)
     at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1242)
     at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:719)
     at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1190)
     at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:812)
     at org.eclipse.jdt.internal.ui.javaeditor.ASTProvider$1.run(ASTProvider.java:535)
     at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
     at org.eclipse.jdt.internal.ui.javaeditor.ASTProvider.createAST(ASTProvider.java:528)
     at org.eclipse.jdt.internal.ui.javaeditor.ASTProvider.getAST(ASTProvider.java:471)
     at org.eclipse.jdt.ui.SharedASTProvider.getAST(SharedASTProvider.java:128)
     at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup.calculateASTandInform(SelectionListenerWithASTManager.java:170)
     at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup$3.run(SelectionListenerWithASTManager.java:155)
     at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

------
REPORT
------
anonymousId         5bf4a57d-7abb-44ee-aa26-7a0cd9658d32
name                
email               
comment             
eclipseBuildId      4.5.1.M20150904-0015
eclipseProduct      org.eclipse.epp.package.jee.product
javaRuntimeVersion  1.8.0_60-b27
osgiWs              win32
osgiOs              Windows7
osgiOsVersion       6.1.0
osgiArch            x86_64
logMessage          false
ignoreSimilar       false

-------
BUNDLES
-------
name                org.eclipse.core.jobs
version             3.7.0.v20150330-2103

name                org.eclipse.core.runtime
version             3.11.1.v20150903-1804

name                org.eclipse.jdt
version             3.11.1.v20150904-0015

name                org.eclipse.jdt.core
version             3.11.0.xx-201508121448-e45

name                org.eclipse.jdt.ui
version             3.11.1.v20150827-1306

```

**Comment by clintshank** [comment]
I've been able to reproduce this with the simple groovy code below:

    class MainClass {
    }

    // commenting this out gets rid of the error
    enum EmptyEnum {
    }

It has to do with the enumeration declared in the same file.

I'm not sure if there are other cases that cause the problem.

**Comment by eric-milles** [comment]
Groovy-Eclipse was updated to match Mars SR2 WRT JDT patching.
