### ISSUE TITLE
StackOverflowError during: "Fetching children of findById"

### ISSUE THREAD

**Issue by jochenberger** [groovy/groovy-eclipse#1500]
I'm getting this error quite regularly in Eclipse 2023-06 with Groovy Eclipse 5.0.0:

```
!ENTRY org.eclipse.core.jobs 4 2 2023-08-14 08:04:33.010
!MESSAGE An internal error occurred during: "Fetching children of findById".
!STACK 0
java.lang.StackOverflowError
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:526)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
        at org.codehaus.groovy.ast.ClassNode.<init>(ClassNode.java:398)
        at org.codehaus.groovy.ast.tools.WideningCategories$LowestUpperBoundClassNode.<init>(WideningCategories.java:534)
        at org.codehaus.groovy.ast.tools.WideningCategories.buildTypeWithInterfaces(WideningCategories.java:512)
        at org.codehaus.groovy.ast.tools.WideningCategories.lowestUpperBound(WideningCategories.java:372)
        at org.codehaus.groovy.ast.tools.WideningCategories.lowestUpperBound(WideningCategories.java:197)
        at org.codehaus.groovy.ast.tools.WideningCategories.parameterizeLowestUpperBound(WideningCategories.java:263)
        at org.codehaus.groovy.ast.tools.WideningCategories.lowestUpperBound(WideningCategories.java:225)
        at org.codehaus.groovy.ast.tools.WideningCategories.parameterizeLowestUpperBound(WideningCategories.java:263)
        at org.codehaus.groovy.ast.tools.WideningCategories.lowestUpperBound(WideningCategories.java:219)
        at org.codehaus.groovy.ast.tools.WideningCategories.parameterizeLowestUpperBound(WideningCategories.java:263)
        at org.codehaus.groovy.ast.tools.WideningCategories.lowestUpperBound(WideningCategories.java:225)
        at org.codehaus.groovy.ast.tools.WideningCategories.parameterizeLowestUpperBound(WideningCategories.java:263)
...
```

**Comment by eric-milles** [comment]
Can you provide a small code sample that recreates this condition?  What version of the groovy compiler are you using?

**Comment by jochenberger** [comment]
The project uses Groovy 4.0.12.
I'm not sure how to find out which file causes the error. Any suggestions how to debug this?

**Comment by eric-milles** [comment]
You can open the Console view and from its toolbar open the Groovy Event Console.  Then when you compile or open a file in the editor you will get some extra output, including the file names as they are processed.

**Comment by jochenberger** [comment]
I'm having a hard time reproducing this and having the Event Console open at that time. Unfortunately, if it does happen, I can no longer interact with the UI because it keeps producing modal windows.

**Comment by eric-milles** [comment]
Does this occur when you open a specific file in the editor?

**Comment by jochenberger** [comment]
No, it seems to happen in some kind of background compilation task.
Those also block the complete UI from time to time.
I have a fair amount of Spock tests in multiple projects in the workspace but I couldn't pin it down to a specific code fragment yet.
