### ISSUE TITLE
NoSuchMethodError when using m2e snapshot version 2.4.300.20240204-1616

### ISSUE THREAD

**Issue by papegaaij** [groovy/groovy-eclipse#1544]
We are having issues with missing file in our builds and therefore switched to a snapshot version of m2e, which contains a fix for this. However, since a few days, this version of m2e has become incompatible with Groovy-Eclipse. I've traced the cause of the error to this change in m2e: https://github.com/eclipse-m2e/m2e-core/commit/60e66fffd0758c4e94c49c0b7e0a2951582d44b3#diff-d508f90e90eb0690e45ca9862654e04141c34013525229cf1fa13162347909d5L867

The signature of the `getFolder` method has changed. This now results in the exception below. I'm not sure how you plan to deal with this, but I guess it is very likely that this change will make it into Eclipse 2024-03.

```
java.lang.NoSuchMethodError: 'org.eclipse.core.resources.IFolder org.codehaus.groovy.m2eclipse.GroovyProjectConfigurator.getFolder(org.eclipse.core.resources.IProject, java.lang.String)'
	at org.codehaus.groovy.m2eclipse.GroovyProjectConfigurator.configureRawClasspath(GroovyProjectConfigurator.java:111)
	at org.eclipse.m2e.jdt.internal.AbstractJavaProjectConfigurator.invokeJavaProjectConfigurators(AbstractJavaProjectConfigurator.java:220)
	at org.eclipse.m2e.jdt.internal.AbstractJavaProjectConfigurator.configure(AbstractJavaProjectConfigurator.java:178)
	at org.codehaus.groovy.m2eclipse.GroovyProjectConfigurator.configure(GroovyProjectConfigurator.java:53)
	at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:123)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$6(ProjectConfigurationManager.java:503)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:402)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:283)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:497)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$4(ProjectConfigurationManager.java:425)
	at java.base/java.util.Collection.removeIf(Collection.java:576)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:413)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$3(ProjectConfigurationManager.java:339)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:402)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:283)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:222)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1097)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:338)
	at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:80)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by eric-milles** [comment]
Groovy Maven configurator delegates to the Java Maven configurator and then adds Groovy-specific configuration.  I reworked it to use much less of the Java component's interface (since it is internal).

You can build just the `org.codehaus.groovy.m2eclipse` plugin and add it to your `dropins` folder to test.  I'll deploy a new snapshot in the next few days.

**Comment by papegaaij** [comment]
That's great news. I'll wait until the new snapshot is available. For now, we're working with a snapshot build of m2e a couple of days old, which does not yet have the change.

**Comment by cquoss** [comment]
When will this reach GA?

**Comment by eric-milles** [comment]
You can get it in a snapshot build today.  The next release is March 31st.
