### ISSUE TITLE
Compute hover fails for member of type variable element

### ISSUE THREAD

**Issue by eric-milles** [groovy/groovy-eclipse#1563]
Consider the following:
```groovy
class C<T extends Thread> {
  def m(T thread) {
    thread.name
  }
}
```

Hovering over "name" produced the following error -- same for "getName()"
```
java.lang.IllegalArgumentException: TT;
	at org.eclipse.jdt.core.Signature.getReturnType(Signature.java:1872)
	at org.eclipse.jdt.core.Signature.getReturnType(Signature.java:1889)
	at org.eclipse.jdt.internal.core.manipulation.JavaElementLabelComposerCore.appendMethodLabel(JavaElementLabelComposerCore.java:277)
	at org.eclipse.jdt.internal.core.manipulation.JavaElementLabelComposerCore.appendElementLabel(JavaElementLabelComposerCore.java:174)
	at org.eclipse.jdt.internal.ui.viewsupport.JavaElementLinks.getElementLabel(JavaElementLinks.java:761)
	at org.eclipse.jdt.internal.ui.viewsupport.JavaElementLinks.getElementLabel(JavaElementLinks.java:743)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavadocHover.getInfoText(JavadocHover.java:806)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavadocHover.getHoverInfo(JavadocHover.java:743)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavadocHover.internalGetHoverInfo(JavadocHover.java:666)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavadocHover.getHoverInfo2(JavadocHover.java:658)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:163)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:130)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavaEditorTextHoverProxy.getHoverInfo2(JavaEditorTextHoverProxy.java:89)
	at org.eclipse.jface.text.TextViewerHoverManager$1.run(TextViewerHoverManager.java:155)
```

**Comment by eric-milles** [comment]
![image](https://github.com/groovy/groovy-eclipse/assets/18193802/9073cd37-56d1-4895-a3ae-98bc62b177eb)
