### ISSUE TITLE
Groovy Eclipse 5.5.0 unable to open .groovy files

### ISSUE THREAD

**Issue by pavelhoral** [groovy/groovy-eclipse#1600]
I am getting the following error when opening groovy files in Eclipse:

![image](https://github.com/user-attachments/assets/6cc9e339-a3c5-4a5a-825a-79cd287c3ae9)

<details><summary>Stack trace</summary>

```
java.lang.NoClassDefFoundError: org/codehaus/groovy/eclipse/refactoring/formatter/GroovyIndentationService
	at org.codehaus.groovy.eclipse.editor.GroovyAutoIndentStrategy.<init>(GroovyAutoIndentStrategy.java:44)
	at org.codehaus.groovy.eclipse.editor.GroovyConfiguration.getAutoEditStrategies(GroovyConfiguration.java:101)
	at org.eclipse.jface.text.source.SourceViewer.configure(SourceViewer.java:546)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaSourceViewer.configure(JavaSourceViewer.java:224)
	at org.eclipse.ui.texteditor.AbstractTextEditor.createPartControl(AbstractTextEditor.java:3381)
	at org.eclipse.ui.texteditor.StatusTextEditor.createPartControl(StatusTextEditor.java:64)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.createPartControl(AbstractDecoratedTextEditor.java:466)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaEditor.createPartControl(JavaEditor.java:3105)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor.createPartControl(CompilationUnitEditor.java:1526)
	at org.codehaus.groovy.eclipse.editor.GroovyEditor.createPartControl(GroovyEditor.java:754)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:158)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:96)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:365)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:977)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:939)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:139)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:386)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:312)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:203)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:90)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:59)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:132)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:991)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:658)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:762)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:727)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:711)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.lambda$0(PartServiceImpl.java:105)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5960)
	at org.eclipse.e4.ui.workbench.swt.DisplayUISynchronize.syncExec(DisplayUISynchronize.java:34)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:206)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:201)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:131)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:73)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:60)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElementGen(ElementContainerImpl.java:168)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:187)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:654)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:618)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:796)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:401)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1271)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3228)
	at org.eclipse.ui.internal.WorkbenchPage.lambda$11(WorkbenchPage.java:3118)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3116)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3086)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3077)
	at org.eclipse.ui.ide.IDE.openEditor(IDE.java:546)
	at org.eclipse.ui.ide.IDE.openEditor(IDE.java:506)
	at org.eclipse.jdt.internal.ui.javaeditor.EditorUtility.openInEditor(EditorUtility.java:377)
	at org.eclipse.jdt.internal.ui.javaeditor.EditorUtility.openInSpecificEditor(EditorUtility.java:176)
	at org.eclipse.jdt.internal.ui.javaeditor.EditorUtility.openInEditor(EditorUtility.java:169)
	at org.eclipse.jdt.ui.actions.OpenAction.run(OpenAction.java:288)
	at org.eclipse.jdt.ui.actions.OpenAction.run(OpenAction.java:254)
	at org.eclipse.jdt.ui.actions.SelectionDispatchAction.dispatchRun(SelectionDispatchAction.java:274)
	at org.eclipse.jdt.ui.actions.SelectionDispatchAction.run(SelectionDispatchAction.java:252)
	at org.eclipse.jdt.internal.ui.navigator.OpenAndExpand.run(OpenAndExpand.java:53)
	at org.eclipse.ui.actions.RetargetAction.run(RetargetAction.java:215)
	at org.eclipse.ui.navigator.CommonNavigatorManager$1.open(CommonNavigatorManager.java:184)
	at org.eclipse.ui.OpenAndLinkWithEditorHelper$InternalListener.open(OpenAndLinkWithEditorHelper.java:48)
	at org.eclipse.jface.viewers.StructuredViewer$2.run(StructuredViewer.java:799)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.fireOpen(StructuredViewer.java:796)
	at org.eclipse.jface.viewers.StructuredViewer.handleOpen(StructuredViewer.java:1110)
	at org.eclipse.ui.navigator.CommonViewer.handleOpen(CommonViewer.java:451)
	at org.eclipse.jface.util.OpenStrategy.fireOpenEvent(OpenStrategy.java:295)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:330)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1617)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1454)
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle org.codehaus.groovy.eclipse.refactoring (2618).
	... 109 more
```
</details>

Eclipse version:

```
eclipse.buildId=4.33.0.20240905-0613
java.version=21.0.4
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product
```

I don't know how Eclipse plugins work in detail, but it seems the `org.codehaus.groovy.eclipse.ui_5.5.0.v202409302019-e2403.jar` is missing `org.codehaus.groovy.eclipse.refactoring.formatter` in OSGI imports (or maybe the refactoring bundle is supposed to be a fragment bundle?):

<details><summary>bnd output for org.codehaus.groovy.eclipse.ui JAR</summary>

```console
$ bnd print org.codehaus.groovy.eclipse.ui_5.5.0.v202409302019-e2403.jar
[MANIFEST org.codehaus.groovy.eclipse.ui_5.5.0.v202409302019-e2403]
Bundle-ActivationPolicy                  lazy;exclude:="org.codehaus.groovy.eclipse.ui,org.codehaus.groovy.eclipse.ui.decorators"
Bundle-Activator                         org.codehaus.groovy.eclipse.GroovyPlugin
Bundle-ManifestVersion                   2                                       
Bundle-Name                              Groovy UI                               
Bundle-RequiredExecutionEnvironment      JavaSE-11                               
Bundle-SymbolicName                      org.codehaus.groovy.eclipse.ui;singleton:=true
Bundle-Vendor                            Pivotal Software, Inc.                  
Bundle-Version                           5.5.0.v202409302019-e2403               
Eclipse-SourceReferences                 scm:git:git://github.com/gitroot/groovy/groovy-eclipse;path="ide/org.codehaus.groovy.eclipse.ui";tag="v5.5.0";commitId=b40cd6a2217cb26278d6a946caf97f9a327f7233
Export-Package                           org.codehaus.groovy.eclipse,org.codehaus.groovy.eclipse.actions,org.codehaus.groovy.eclipse.adapters,org.codehaus.groovy.eclipse.debug.ui,org.codehaus.groovy.eclipse.editor,org.codehaus.groovy.eclipse.editor.actions,org.codehaus.groovy.eclipse.editor.highlighting,org.codehaus.groovy.eclipse.editor.outline,org.codehaus.groovy.eclipse.launchers,org.codehaus.groovy.eclipse.preferences,org.codehaus.groovy.eclipse.refactoring.actions,org.codehaus.groovy.eclipse.search,org.codehaus.groovy.eclipse.ui,org.codehaus.groovy.eclipse.ui.browse,org.codehaus.groovy.eclipse.ui.console,org.codehaus.groovy.eclipse.ui.decorators,org.codehaus.groovy.eclipse.ui.utils,org.codehaus.groovy.eclipse.wizards
Import-Package                           org.codehaus.groovy.frameworkadapter.util,org.eclipse.eclemma.ui.launching;resolution:=optional,org.eclipse.equinox.bidi
Manifest-Version                         1.0                                     
Require-Bundle                           org.codehaus.groovy.eclipse.codebrowsing;bundle-version="5.5.0",org.codehaus.groovy.eclipse.core;bundle-version="5.5.0";visibility:=reexport,org.codehaus.groovy.eclipse.refactoring;bundle-version="5.5.0",org.eclipse.debug.ui,org.eclipse.jdt.debug,org.eclipse.jdt.debug.ui,org.eclipse.jdt.junit,org.eclipse.jdt.launching,org.eclipse.jdt.ui;visibility:=reexport,org.eclipse.jface.text;visibility:=reexport,org.eclipse.search,org.eclipse.ui;visibility:=reexport,org.eclipse.ui.browser,org.eclipse.ui.console,org.eclipse.ui.editors,org.eclipse.ui.ide,org.eclipse.ui.views,org.eclipse.ui.workbench,org.eclipse.ui.workbench.texteditor;visibility:=reexport

[IMPEXP]
Import-Package
  org.codehaus.groovy.frameworkadapter.util 
  org.eclipse.eclemma.ui.launching       {resolution:=optional}
  org.eclipse.equinox.bidi               
Export-Package
  org.codehaus.groovy.eclipse            
  org.codehaus.groovy.eclipse.actions    
  org.codehaus.groovy.eclipse.adapters   
  org.codehaus.groovy.eclipse.debug.ui   
  org.codehaus.groovy.eclipse.editor     
  org.codehaus.groovy.eclipse.editor.actions 
  org.codehaus.groovy.eclipse.editor.highlighting 
  org.codehaus.groovy.eclipse.editor.outline 
  org.codehaus.groovy.eclipse.launchers  
  org.codehaus.groovy.eclipse.preferences 
  org.codehaus.groovy.eclipse.refactoring.actions 
  org.codehaus.groovy.eclipse.search     
  org.codehaus.groovy.eclipse.ui         
  org.codehaus.groovy.eclipse.ui.browse  
  org.codehaus.groovy.eclipse.ui.console 
  org.codehaus.groovy.eclipse.ui.decorators 
  org.codehaus.groovy.eclipse.ui.utils   
  org.codehaus.groovy.eclipse.wizards
```
</details>

<details><summary>bnd output for org.codehaus.groovy.eclipse.refactoring JAR</summary>

```console
$ bnd print org.codehaus.groovy.eclipse.refactoring_5.5.0.v202409302019-e2403.jar 
[MANIFEST org.codehaus.groovy.eclipse.refactoring_5.5.0.v202409302019-e2403]
Bundle-ActivationPolicy                  lazy                                    
Bundle-Activator                         org.codehaus.groovy.eclipse.refactoring.Activator
Bundle-ManifestVersion                   2                                       
Bundle-Name                              Groovy Refactoring                      
Bundle-RequiredExecutionEnvironment      JavaSE-11                               
Bundle-SymbolicName                      org.codehaus.groovy.eclipse.refactoring; singleton:=true
Bundle-Vendor                            Pivotal Software, Inc.                  
Bundle-Version                           5.5.0.v202409302019-e2403               
Eclipse-SourceReferences                 scm:git:git://github.com/gitroot/groovy/groovy-eclipse;path="ide/org.codehaus.groovy.eclipse.refactoring";tag="v5.5.0";commitId=b40cd6a2217cb26278d6a946caf97f9a327f7233
Export-Package                           org.codehaus.groovy.eclipse.refactoring,org.codehaus.groovy.eclipse.refactoring.core.convert,org.codehaus.groovy.eclipse.refactoring.core.extract,org.codehaus.groovy.eclipse.refactoring.core.rename,org.codehaus.groovy.eclipse.refactoring.core.rename.renameLocal,org.codehaus.groovy.eclipse.refactoring.core.rewriter,org.codehaus.groovy.eclipse.refactoring.core.utils,org.codehaus.groovy.eclipse.refactoring.core.utils.astScanner,org.codehaus.groovy.eclipse.refactoring.core.utils.astScanner.predicates,org.codehaus.groovy.eclipse.refactoring.formatter,org.codehaus.groovy.eclipse.refactoring.ui.extract
Manifest-Version                         1.0                                     
Require-Bundle                           org.codehaus.groovy.eclipse.codebrowsing;bundle-version="5.5.0",org.codehaus.groovy.eclipse.core;bundle-version="5.5.0",org.eclipse.jdt.core.manipulation;visibility:=reexport,org.eclipse.jdt.ui,org.eclipse.jface.text,org.eclipse.ltk.core.refactoring;visibility:=reexport,org.eclipse.ltk.ui.refactoring;visibility:=reexport,org.eclipse.ui,org.eclipse.ui.editors

[IMPEXP]
Export-Package
  org.codehaus.groovy.eclipse.refactoring 
  org.codehaus.groovy.eclipse.refactoring.core.convert 
  org.codehaus.groovy.eclipse.refactoring.core.extract 
  org.codehaus.groovy.eclipse.refactoring.core.rename 
  org.codehaus.groovy.eclipse.refactoring.core.rename.renameLocal 
  org.codehaus.groovy.eclipse.refactoring.core.rewriter 
  org.codehaus.groovy.eclipse.refactoring.core.utils 
  org.codehaus.groovy.eclipse.refactoring.core.utils.astScanner 
  org.codehaus.groovy.eclipse.refactoring.core.utils.astScanner.predicates 
  org.codehaus.groovy.eclipse.refactoring.formatter 
  org.codehaus.groovy.eclipse.refactoring.ui.extract
```
</details>

**Comment by pavelhoral** [comment]
Seems like `Require-Bundle` is used instead of `Import-Package` (which is probably preferred in Eclipse)... not sure why I am getting `NoClassDefFaundError` in that case.

**Comment by eric-milles** [comment]
`LanguageSupport` comes from the JDT patch bundle.  This would not be available if you have a mismatched eclipse release and groovy tools update site.  Eclipse 4.33 (2024-09) requires the `e2409` bundles.

**Comment by pavelhoral** [comment]
> `LanguageSupport` comes from the JDT patch bundle. This would not be available if you have a mismatched eclipse release and groovy tools update site. Eclipse 4.33 (2024-09) requires the `e2409` bundles.

It is not that I have installed incorrect versions. I have clicked on "Update" button that presented itself when I started my Eclipse. Everything worked before the Groovy Development Tools update.

After manually changing the Update Site it downloaded the correct artifacts and GDT now works again. Thank you for pointing me in the right direction.

**Comment by eric-milles** [comment]
I'm not sure if there is any mechanism that I can tie into.  Maybe just having a "latest release" update site is required for allowing updates that chase the latest eclipse.
