### ISSUE TITLE
StringIndexOutOfBoundsException parsing warning messages from forked compilation

### ISSUE THREAD

**Issue by firstone** [groovy/groovy-eclipse#167]
This is happening during Jenkins builds. Not sure what Jenkins does differently that causes it. 

Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 120
        at java.lang.String.substring(String.java:1951)
        at org.codehaus.groovy.eclipse.compiler.GroovyEclipseCompiler.parseMessage(GroovyEclipseCompiler.java:540)
        at org.codehaus.groovy.eclipse.compiler.GroovyEclipseCompiler.parseMessages(GroovyEclipseCompiler.java:484)
        at org.codehaus.groovy.eclipse.compiler.GroovyEclipseCompiler.compileOutOfProcess(GroovyEclipseCompiler.java:449)
        at org.codehaus.groovy.eclipse.compiler.GroovyEclipseCompiler.internalCompile(GroovyEclipseCompiler.java:129)
        at org.codehaus.groovy.eclipse.compiler.GroovyEclipseCompiler.performCompile(GroovyEclipseCompiler.java:90)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:825)
        ... 22 more

**Comment by eric-milles** [comment]
Newer batch compilers are available through bintray.  These should not have the same parsing issue.
