### ISSUE TITLE
java.lang.NoClassDefFoundError: org/eclipse/jdt/groovy/search/TypeInferencingVisitorWithRequestor$1Helper

### ISSUE THREAD

**Issue by robertsmieja** [groovy/groovy-eclipse#193]
I've been banging my head against this issue for sometime. I've built a custom distribution of Eclipse, that is essentially GGTS + some extra plugins, and this error message is popping up constantly. I've checked the org.eclipse.jdt.groovy.core jar manually, and the .class file is there.

I'm referencing the Groovy-Eclipse plugin by using the following XML: 
`
   <plugin
      id="org.codehaus.groovy.eclipse"
      download-size="0"
      install-size="0"
      version="0.0.0"/>
`

This issue may end up being related to how the Groovy-Eclipse plugin is being installed in the custom distribution.

We are currently using Groovy 1.8 and Grails 2.1.5

Stack trace and more info below:

```
An error has occurred. See error log for more details.
org/eclipse/jdt/groovy/search/TypeInferencingVisitorWithRequestor$1Helper


eclipse.buildId=4.5.2.M20160212-1500
java.version=1.7.0_80
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product com.phoenix.eclipse.package.lets.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product com.phoenix.eclipse.package.lets.product

org.eclipse.core.jobs
Error
Wed Aug 10 10:02:59 EDT 2016
An internal error occurred during: "Requesting Java AST from selection".

java.lang.NoClassDefFoundError: org/eclipse/jdt/groovy/search/TypeInferencingVisitorWithRequestor$1Helper
                at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.inferGenericMethodType(TypeInferencingVisitorWithRequestor.java:1704)
                at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitMethodCallExpression(TypeInferencingVisitorWithRequestor.java:1683)
                at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:75)
                at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:121)
                at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitExpressionStatement(ClassCodeVisitorSupport.java:236)
                at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
                at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:87)
                at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:206)
                at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitBlockStatement(TypeInferencingVisitorWithRequestor.java:1408)
                at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
                at org.codehaus.groovy.ast.CodeVisitorSupport.visitClosureExpression(CodeVisitorSupport.java:226)
                at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitClosureExpression(TypeInferencingVisitorWithRequestor.java:1319)
                at org.codehaus.groovy.ast.expr.ClosureExpression.visit(ClosureExpression.java:43)
                at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitBinaryExpression(TypeInferencingVisitorWithRequestor.java:1027)
                at org.codehaus.groovy.ast.expr.BinaryExpression.visit(BinaryExpression.java:49)
                at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:121)
                at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitExpressionStatement(ClassCodeVisitorSupport.java:236)
                at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
                at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:87)
                at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:206)
                at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitBlockStatement(TypeInferencingVisitorWithRequestor.java:1408)
                at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
                at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:103)
                at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:114)
                at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitConstructorOrMethod(TypeInferencingVisitorWithRequestor.java:842)
                at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitJDT(TypeInferencingVisitorWithRequestor.java:571)
                at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitJDT(TypeInferencingVisitorWithRequestor.java:404)
                at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitCompilationUnit(TypeInferencingVisitorWithRequestor.java:352)
                at org.codehaus.groovy.eclipse.search.GroovyOccurrencesFinder.internalFindOccurences(GroovyOccurrencesFinder.java:179)
                at org.codehaus.groovy.eclipse.search.GroovyOccurrencesFinder.getOccurrences(GroovyOccurrencesFinder.java:103)
                at org.codehaus.groovy.eclipse.editor.GroovyEditor.updateOccurrenceAnnotations(GroovyEditor.java:1260)
                at org.eclipse.jdt.internal.ui.javaeditor.JavaEditor$6.selectionChanged(JavaEditor.java:3386)
                at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup.calculateASTandInform(SelectionListenerWithASTManager.java:178)
                at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup$3.run(SelectionListenerWithASTManager.java:155)
                at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by robertsmieja** [comment]
I noticed there is a "Non-Locking ClassLoader" bundled. Could that be the reason why the ClassDef for TypeInferencingVisitorWithRequestor$1Helper is not being found, even though it's adjacent to TypeInferencingVisitorWithRequestor?

**Comment by robertsmieja** [comment]
Does anyone have any idea why this is happening? We're also encountering the issue now on Eclipse Neon.1 (4.6.1)

Thanks in advance

**Comment by eric-milles** [comment]
Not sure what revision of Groovy-Eclipse you are picking up.  But I have found support for 1.8 is likely not there in 2.9.2.

**Comment by eric-milles** [comment]
I thought I saw a set of commits to fix Groovy 1.8 support, but I can't find it at the moment.  If that gets in, I could update Groovy to 1.8.9 and further certify the current state of support for it.

**Comment by robertsmieja** [comment]
What's the reason for closing this issue? I'm still having the issue, it hasn't been resolved.

**Comment by eric-milles** [comment]
Have you tried the latest 2.9.2 snapshot?  Should be fixed.

**Comment by robertsmieja** [comment]
Ok, sounds good. I was able to give it a quick look through and it looks like it was fixed. Thanks!
