### ISSUE TITLE
java.lang.NoClassDefFoundError: org/codehaus/jdt/groovy/integration/LanguageSupportFactory

### ISSUE THREAD

**Issue by zosrothko** [groovy/groovy-eclipse#206]
Hi

I am running Eclipse Mars.2 on Fedora and build gradle, I got the exception below. Note also this error message on the log
```
 CompilerOracle: exclude org/eclipse/core/internal/dtree/DataTreeNode.forwardDeltaWith
CompilerOracle: exclude org/eclipse/jdt/internal/compiler/lookup/ParameterizedMethodBinding.<init>
CompilerOracle: exclude org/eclipse/cdt/internal/core/dom/parser/cpp/semantics/CPPTemplates.instantiateTemplate
CompilerOracle: exclude org/eclipse/cdt/internal/core/pdom/dom/cpp/PDOMCPPLinkage.addBinding
CompilerOracle: exclude org/python/pydev/editor/codecompletion/revisited/PythonPathHelper.isValidSourceFile
CompilerOracle: exclude org/eclipse/tycho/core/osgitools/EquinoxResolver.newState
**_## Starting Groovy-Eclipse compiler resolver.  Specified compiler level: unspecified_**
222 2.4.3.xx-201610201739-e45 = STARTING
223 2.3.10.xx-201610201739-e45 = STARTING
```

```
java.lang.NoClassDefFoundError: org/codehaus/jdt/groovy/integration/LanguageSupportFactory
        at org.codehaus.jdt.groovy.internal.compiler.ScriptFolderCompilationParticipant.sanityCheckBuilder(ScriptFolderCompilationParticipant.java:143)
        at org.codehaus.jdt.groovy.internal.compiler.ScriptFolderCompilationParticipant.buildStarting(ScriptFolderCompilationParticipant.java:104)
        at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.notifyParticipants(AbstractImageBuilder.java:568)
        at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:290)
        at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:61)
        at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:256)
        at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:175)
        at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
        at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
        at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
        at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
        at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
        at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
!SUBENTRY 1 org.eclipse.jdt.core 4 75 2016-10-25 19:43:37.627
!MESSAGE Errors running builder 'Java Builder' on project 'distributions'.
```

org.eclipse.jdt.core: 3.11.2.v20160416-2200
org.eclipse.jdt.groovy.core: 2.9.2.xx-201610201739-e45
eclipse: Mars.2 (4.5.2)
buildid: Z20160416-2208
```
[fandre@fedora-x86-idefix gradle]$ java -version
openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)
[fandre@fedora-x86-idefix gradle]$
```

**Comment by zosrothko** [comment]
I was using the prepackaged Fedora eclipse installed with dnf install eclipse. It sucks. Downloading directly the Mars.2 package from Eclipse works fine.
