### ISSUE TITLE
NPE throw with Neon.1a Release (4.6.1) Type Parameter formatting preferences.

### ISSUE THREAD

**Issue by jmax01** [groovy/groovy-eclipse#213]
!ENTRY org.eclipse.jface 4 2 2016-11-01 10:35:11.725
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.jdt.internal.ui.preferences.formatter.LineWrappingTabPage$SelectionState.getMax(LineWrappingTabPage.java:349)
	at org.eclipse.jdt.internal.ui.preferences.formatter.LineWrappingTabPage$SelectionState.updateButton(LineWrappingTabPage.java:336)
	at org.eclipse.jdt.internal.ui.preferences.formatter.LineWrappingTabPage$SelectionState.refreshControls(LineWrappingTabPage.java:284)
	at org.eclipse.jdt.internal.ui.preferences.formatter.LineWrappingTabPage$SelectionState.refreshState(LineWrappingTabPage.java:213)
	at org.eclipse.jdt.internal.ui.preferences.formatter.LineWrappingTabPage$CategoryListener.selectionChanged(LineWrappingTabPage.java:146)
	at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:158)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:155)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2191)
	at org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1229)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1258)
	at org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:242)
	at org.eclipse.jface.util.OpenStrategy.access$4(OpenStrategy.java:236)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:405)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4228)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3816)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.jdt.internal.ui.preferences.formatter.ProfileConfigurationBlock$ButtonController.modifyButtonPressed(ProfileConfigurationBlock.java:228)
	at org.eclipse.jdt.internal.ui.preferences.formatter.ProfileConfigurationBlock$ButtonController.widgetSelected(ProfileConfigurationBlock.java:172)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4228)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3816)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.open(WorkbenchPreferenceDialog.java:211)
	at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:63)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4228)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3816)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

**Comment by eric-milles** [comment]
What were the steps you were taking when this happened?

**Comment by jmax01** [comment]
Fresh install of Neon 1a
Installed http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/
Window->Preferences->Java -> Code Style ->Formatter
Edit (Does not matter which Active Profile)
Line Wrapping Tab
Select Parameterized Types
NPE

**Comment by eric-milles** [comment]
Gotcha.  So no NPE for me; what I suspect is that the JDT patch is 4.6.0 and the rest of your JDT is running at 4.6.1.  I do have all the changes for 4.6.1 in a branch thanks to @felixdo.  I didn't want to take credit for his hard work, but could produce a pull request if necessary.

**Comment by jmax01** [comment]
I suspect DefaultCodeFormatterConstants changes are the root of the issue.

**Comment by eric-milles** [comment]
I have submitted a Pull Request for JDT Core SR1.  It should correct this issue.

**Comment by eric-milles** [comment]
Can you retest with the latest snapshot?

**Comment by jmax01** [comment]
Appears to work.
Thanks for the help!

**Comment by lucasvc** [comment]
@eric-milles Can this fix have broken the formatter key binding?
I've been using the lasts months Groovy editor, and I could format the code with the same Java key binding (<kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>F</kbd>). Since an update I have to select the code I want to format.

**Comment by eric-milles** [comment]
Could be; I altered the formatter front end to allow Correct Indentation to operate on the current line only when no selection is made.  Can you open a separate issue for this so it can be tracked?

**Comment by lucasvc** [comment]
Created #248.
