### ISSUE TITLE
NoSuchMethodException in GroovyExtraInformationHover.extraDocAsHtml

### ISSUE THREAD

**Issue by felixdo** [groovy/groovy-eclipse#301]
Caused by reflective call to private jdt method whose signature has changed two years ago in 0d974018

org.eclipse.jdt.internal.ui.text.javadoc.JavadocContentAccess2.javadoc2HTML(org.eclipse.jdt.core.IMember, java.lang.String)
	at java.lang.Class.getDeclaredMethod(Unknown Source)
	at org.eclipse.jdt.groovy.core.util.ReflectionUtils.executePrivateMethod(ReflectionUtils.java:103)
	at org.codehaus.groovy.eclipse.editor.GroovyExtraInformationHover.extraDocAsHtml(GroovyExtraInformationHover.java:164)
	at org.codehaus.groovy.eclipse.editor.GroovyExtraInformationHover.wrapHTML(GroovyExtraInformationHover.java:148)
	at org.codehaus.groovy.eclipse.editor.GroovyExtraInformationHover.computeHover(GroovyExtraInformationHover.java:133)
	at org.codehaus.groovy.eclipse.editor.GroovyExtraInformationHover.getHoverInfo2(GroovyExtraInformationHover.java:100)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:164)
	at org.eclipse.jdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:130)
	at org.eclipse.jdt.internal.ui.text.java.hover.JavaEditorTextHoverProxy.getHoverInfo2(JavaEditorTextHoverProxy.java:86)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:165)

**Comment by felixdo** [comment]
Current code assumes that the passed GroovyResolvedElement is already an IMember, so I wonder if we could just replace this:

        return (String) ReflectionUtils.executePrivateMethod(JavadocContentAccess2.class, "javadoc2HTML", new Class[] {IMember.class, String.class}, null, new Object[] {elt, extraDoc});

by this:

        return (String) ReflectionUtils.executePrivateMethod(JavadocContentAccess2.class, "javadoc2HTML", new Class[] {IMember.class, IJavaElement.class, String.class}, null, new Object[] {elt, elt, extraDoc});

and hope for the best..

**Comment by eric-milles** [comment]
I can take care of it.  Usually this requires looking for the newer method and falling back if not found.  Eclipse support goes all the way back to 3.7 for now.

**Comment by eric-milles** [comment]
Can you retest with the latest snapshot?

**Comment by felixdo** [comment]
Ok not happening any longer with the latest snapshot.
