### ISSUE TITLE
Groovy-Eclipse Type Inferencing: Error visiting method run in class xxx

### ISSUE THREAD

**Issue by felixdo** [groovy/groovy-eclipse#306]
This is an error that shows up in the error log when when opening a dsld file in my workspace. Here is the full stacktrace:

java.lang.NullPointerException
	at org.eclipse.jdt.internal.compiler.lookup.TypeSystem.getParameterizedType(TypeSystem.java:300)
	at org.eclipse.jdt.internal.compiler.lookup.TypeSystem.getParameterizedType(TypeSystem.java:304)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createParameterizedType(LookupEnvironment.java:1008)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getTypeFromTypeSignature(LookupEnvironment.java:1570)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.createFields(BinaryTypeBinding.java:631)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.cachePartsFrom(BinaryTypeBinding.java:528)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:732)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createBinaryTypeFrom(LookupEnvironment.java:715)
	at org.eclipse.jdt.internal.compiler.Compiler.accept(Compiler.java:310)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:157)
	at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:101)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:217)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:186)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:3035)
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyCompilationUnitScope.lookupClassNodeForSource(GroovyCompilationUnitScope.java:247)
	at org.codehaus.jdt.groovy.internal.compiler.ast.JDTResolver.resolveFromCompileUnit(JDTResolver.java:184)
	at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:353)
	at org.codehaus.jdt.groovy.internal.compiler.ast.JDTResolver.resolve(JDTResolver.java:365)
	at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:318)
	at org.codehaus.jdt.groovy.internal.compiler.ast.JDTResolver.resolve(JDTResolver.java:375)
	at org.codehaus.groovy.eclipse.dsl.lookup.ResolverCache.resolve(ResolverCache.java:76)
	at org.codehaus.groovy.eclipse.dsl.contributions.PropertyContributionElement.ensureReturnType(PropertyContributionElement.java:93)
	at org.codehaus.groovy.eclipse.dsl.contributions.PropertyContributionElement.lookupType(PropertyContributionElement.java:72)
	at org.codehaus.groovy.eclipse.dsl.lookup.DSLDTypeLookup.lookupTypeAndDeclaration(DSLDTypeLookup.java:87)
	at org.eclipse.jdt.groovy.search.AbstractSimplifiedTypeLookup.lookupType(AbstractSimplifiedTypeLookup.java:133)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.lookupExpressionType(TypeInferencingVisitorWithRequestor.java:2266)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.handleSimpleExpression(TypeInferencingVisitorWithRequestor.java:1835)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitVariableExpression(TypeInferencingVisitorWithRequestor.java:1729)
	at org.codehaus.groovy.ast.expr.VariableExpression.visit(VariableExpression.java:72)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitMapEntryExpression(TypeInferencingVisitorWithRequestor.java:1325)
	at org.codehaus.groovy.ast.expr.MapEntryExpression.visit(MapEntryExpression.java:39)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitMapExpression(TypeInferencingVisitorWithRequestor.java:1388)
	at org.codehaus.groovy.ast.expr.MapExpression.visit(MapExpression.java:55)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitListOfExpressions(CodeVisitorSupport.java:278)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitTupleExpression(CodeVisitorSupport.java:183)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitTupleExpression(TypeInferencingVisitorWithRequestor.java:1680)
	at org.codehaus.groovy.ast.expr.TupleExpression.visit(TupleExpression.java:78)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitMethodCallExpression(TypeInferencingVisitorWithRequestor.java:1443)
	at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:66)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:74)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitExpressionStatement(ClassCodeVisitorSupport.java:281)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:42)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:40)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:251)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitBlockStatement(TypeInferencingVisitorWithRequestor.java:939)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:71)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitClosureExpression(CodeVisitorSupport.java:179)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitClosureExpression(TypeInferencingVisitorWithRequestor.java:1062)
	at org.codehaus.groovy.ast.expr.ClosureExpression.visit(ClosureExpression.java:45)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitListOfExpressions(CodeVisitorSupport.java:278)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitTupleExpression(CodeVisitorSupport.java:183)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitTupleExpression(TypeInferencingVisitorWithRequestor.java:1680)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitArgumentlistExpression(TypeInferencingVisitorWithRequestor.java:814)
	at org.codehaus.groovy.ast.expr.ArgumentListExpression.visit(ArgumentListExpression.java:76)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitMethodCallExpression(TypeInferencingVisitorWithRequestor.java:1443)
	at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:66)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:74)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitExpressionStatement(ClassCodeVisitorSupport.java:281)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:42)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:40)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:251)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitBlockStatement(TypeInferencingVisitorWithRequestor.java:939)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:71)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:148)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:159)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitConstructorOrMethod(TypeInferencingVisitorWithRequestor.java:1134)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitJDT(TypeInferencingVisitorWithRequestor.java:521)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitJDT(TypeInferencingVisitorWithRequestor.java:391)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitCompilationUnit(TypeInferencingVisitorWithRequestor.java:350)
	at org.codehaus.groovy.eclipse.editor.highlighting.GatherSemanticReferences.findSemanticHighlightingReferences(GatherSemanticReferences.java:46)
	at org.codehaus.groovy.eclipse.editor.highlighting.GroovySemanticReconciler.reconciled(GroovySemanticReconciler.java:226)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor.reconciled(CompilationUnitEditor.java:1687)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconciled(JavaReconcilingStrategy.java:219)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconciled(JavaCompositeReconcilingStrategy.java:164)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.initialReconcile(JavaCompositeReconcilingStrategy.java:144)
	at org.eclipse.jface.text.reconciler.MonoReconciler.initialProcess(MonoReconciler.java:95)
	at org.eclipse.jdt.internal.ui.text.JavaReconciler.initialProcess(JavaReconciler.java:420)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:174)

**Comment by felixdo** [comment]
![image](https://user-images.githubusercontent.com/179663/26920017-e9b02402-4c37-11e7-80a8-4dcf89dedfe1.png)

this is how the file is highlighted

**Comment by felixdo** [comment]
These are the dsld contents:

```
// this is a DSLD file
// start off creating a custom DSL Descriptor for your Groovy DSL

// Don't need to bind here since currentType is always available in a contribution block
currentType(subType("org.polarsys.capella.core.data.capellacore.CapellaElement")).accept {
    provider = "Groovy-Capella Extra Methods"
    method name:"getPropertyValue", type:Object, isStatic:false, declaringType:currentType, doc:"Get the property value named by key and returns its value"
	method name:"setPropertyValue", type:void, isStatic:false, declaringType:currentType, doc:"Sets and possibly overwrites the property value with the given name to the given value"
}

currentType("org.polarsys.capella.groovy.CapellaScriptBase").accept {
	provider = "Groovy-Capella Extra Methods"
	method name:"diagrams", type:Collection, isStatic:false, declaringType: currentType, doc:"Returns a collection of all diagrams in the current model context"
}

```

**Comment by eric-milles** [comment]
I was not able to recreate.  But it looks like `type:void` should either be `type:'void'` or `type:Void`.

Also, do you have *.dsld as a script filter for you project or workspace?

**Comment by felixdo** [comment]
I'll try with Void or 'void'. What is a script filter? You mean this?
![image](https://user-images.githubusercontent.com/179663/26940013-78e5564c-4c79-11e7-85e8-bb260da0c03c.png)

**Comment by eric-milles** [comment]
Yes, that's correct.  `*.dsld` will not be compiled but will be copied to output folder (not sure if that is needed).

**Comment by eric-milles** [comment]
Is this still an issue with the latest snapshot?  Also, the accept form of DSLD contributions is deprecated.  You can use `contribute(currentType(...))` where you use `correntType(...).accept`.

**Comment by felixdo** [comment]
Uhm not sure. There's always something going on in the console when editing and I seem to care less about every day.. I will try to look if it's still happening.

**Comment by eric-milles** [comment]
Do you have the Error Log view in your install?  That is a better way to keep track of the logged exceptions.  I have been trying to whittle away at the errors during editing.  There is still a lot of room for improvement.
