### ISSUE TITLE
 Could not find jline in class path when Run As Groovy Shell

### ISSUE THREAD

**Issue by btlogy** [groovy/groovy-eclipse#319]
Using v2.9.2.xx-201707132012-e47 with build 20170620-1800 running on java-8-openjdk-amd64 (8u131-b11-1~bpo8+1), I'm not able to run any project using Run As Groovy Shell (see stack trace under).
I've been trying to add this jar everywhere I could without success :-(
Maybe related to 06cd163f18f31c19c711869ae5b8a759b9826f1e ?

!ENTRY org.codehaus.groovy.eclipse.core 4 0 2017-07-14 15:21:26.700
!MESSAGE Error getting extra classpath elements to launch
!STACK 1
org.eclipse.core.runtime.CoreException: Could not find jline-*.jar on the class path.  Please add it manually
        at org.codehaus.groovy.eclipse.core.launchers.GroovyShellLaunchDelegate.getPathTo(GroovyShellLaunchDelegate.java:64)
        at org.codehaus.groovy.eclipse.core.launchers.GroovyShellLaunchDelegate.getExtraClasspathElements(GroovyShellLaunchDelegate.java:54)
        at org.codehaus.groovy.eclipse.launchers.GroovyShellLaunchShortcut.launchGroovy(GroovyShellLaunchShortcut.java:119)
        at org.codehaus.groovy.eclipse.launchers.GroovyShellLaunchShortcut.launch(GroovyShellLaunchShortcut.java:84)
        at org.eclipse.debug.internal.ui.launchConfigurations.LaunchShortcutExtension.launch(LaunchShortcutExtension.java:431)
        at org.eclipse.debug.internal.ui.actions.LaunchShortcutAction.runInternal(LaunchShortcutAction.java:85)
        at org.eclipse.debug.internal.ui.actions.LaunchShortcutAction.runWithEvent(LaunchShortcutAction.java:135)
        at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
        at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5252)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1357)
        at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1142)
        at org.eclipse.jface.action.ActionContributionItem.lambda$8(ActionContributionItem.java:1257)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5252)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4522)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4107)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1044)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1472)

**Comment by eric-milles** [comment]
Sorry, I'm not too familiar with Run as Groovy Shell.  Is the expectation for it that you have Groovy installed to your OS?  I'm thinking the jline.jar is supposed to be coming from ~/.groovy/lib

**Comment by eric-milles** [comment]
Okay, I see the problem.  The launch delegate and shortcut are both looking for jline-*.jar within the Groovy runtime bundle and fail if not found.  Even if you supply it by other means.

I was able to get Run As > Groovy Shell working with some small changes plus the addition of jline.jar and commons-cli.jar to my project's classpath.

![groovy-shell](https://user-images.githubusercontent.com/18193802/28218914-b36794de-687f-11e7-99ea-faa06f9af727.png)
