### ISSUE TITLE
Refresh dependencies failed

### ISSUE THREAD

**Issue by ernesto-castelan** [groovy/groovy-eclipse#322]
Hello,

I'm getting the following error when updating dependencies in a Grails project
![image](https://user-images.githubusercontent.com/28717594/28640036-fde43352-720f-11e7-9d7e-ed183a5292be.png)

Stacktrace
```
java.lang.NoClassDefFoundError: org/codehaus/groovy/frameworkadapter/util/SpecifiedVersion
	at org.grails.ide.eclipse.commands.GroovyCompilerVersionCheck.getRequiredGroovyVersion(GroovyCompilerVersionCheck.java:63)
	at org.grails.ide.eclipse.commands.GroovyCompilerVersionCheck.getRequiredGroovyVersion(GroovyCompilerVersionCheck.java:57)
	at org.grails.ide.eclipse.commands.GroovyCompilerVersionCheck.check(GroovyCompilerVersionCheck.java:50)
	at org.grails.ide.eclipse.commands.GrailsCommandUtils.refreshDependencies(GrailsCommandUtils.java:327)
	at org.grails.ide.eclipse.core.internal.classpath.GrailsClasspathContainerUpdateJob.runInWorkspace(GrailsClasspathContainerUpdateJob.java:89)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

The problem is present with Groovy Compiler version 2.4.12 2.9.2.xx-201707260047-e44 and was not present with previous versions.
I'm using GGGTS Version: 3.6.4.RELEASE with Eclipse Luna SR1 (4.4.2) and with Grails 2.5.5.
The problem persists even with a clean installation of GGTS.

**Comment by eric-milles** [comment]
@ernesto-castelan This should be fixed.  Could you retest with the latest snapshot?

**Comment by ernesto-castelan** [comment]
@eric-milles Hi. Everything is working properly now.
