### ISSUE TITLE
Internal compiler error: java.lang.IllegalArgumentException building mixed Java 8 and Groovy 2.4

### ISSUE THREAD

**Issue by simon-temple** [groovy/groovy-eclipse#325]
I can't get my java compiled in a mixed Java 8 and Groovy project.  I've attached a file with all **details** but, in summary, this is errror:

[INFO] --- maven-compiler-plugin:3.6.2:compile (default-compile) @ a1webapp-service-scripting ---
[INFO] Changes detected - recompiling the module!
[INFO] Using Groovy-Eclipse compiler to compile both Java and Groovy files
[INFO] Classpath: <snip>]
[INFO] 10 files left.
[INFO] 9 files left.
[INFO] 8 files left.
[INFO] 7 files left.
[INFO] 6 files left.
[INFO] 5 files left.
[INFO] 4 files left.
[INFO] 3 files left.
[INFO] 2 files left.
org.eclipse.jdt.internal.compiler.problem.AbortMethod: 
	at org.eclipse.jdt.internal.compiler.ast.SingleNameReference.generatePostIncrement(SingleNameReference.java:775)
	at org.eclipse.jdt.internal.compiler.ast.PostfixExpression.generateCode(PostfixExpression.java:40)
	at org.eclipse.jdt.internal.compiler.ast.Expression.generateOptimizedStringConcatenation(Expression.java:795)
	at org.eclipse.jdt.internal.compiler.codegen.CodeStream.generateStringConcatenationAppend(CodeStream.java:2380)
	at org.eclipse.jdt.internal.compiler.ast.BinaryExpression.generateCode(BinaryExpression.java:142)
	at org.eclipse.jdt.internal.compiler.ast.SingleNameReference.generateAssignment(SingleNameReference.java:353)
	at org.eclipse.jdt.internal.compiler.ast.Assignment.generateCode(Assignment.java:134)
	at org.eclipse.jdt.internal.compiler.ast.Expression.generateCode(Expression.java:705)
	at org.eclipse.jdt.internal.compiler.ast.Block.generateCode(Block.java:80)
	at org.eclipse.jdt.internal.compiler.ast.IfStatement.generateCode(IfStatement.java:195)
	at org.eclipse.jdt.internal.compiler.ast.Block.generateCode(Block.java:80)
	at org.eclipse.jdt.internal.compiler.ast.ForeachStatement.generateCode(ForeachStatement.java:332)
	at org.eclipse.jdt.internal.compiler.ast.SwitchStatement.generateCodeForStringSwitch(SwitchStatement.java:275)
	at org.eclipse.jdt.internal.compiler.ast.SwitchStatement.generateCode(SwitchStatement.java:314)
	at org.eclipse.jdt.internal.compiler.ast.Block.generateCode(Block.java:80)
	at org.eclipse.jdt.internal.compiler.ast.TryStatement.generateCode(TryStatement.java:534)
	at org.eclipse.jdt.internal.compiler.ast.SwitchStatement.generateCode(SwitchStatement.java:411)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:325)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:270)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:566)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:635)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:369)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:838)
	at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:137)
	at java.lang.Thread.run(Thread.java:748)
[INFO] Compilation complete.  Compiled 9 files.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/simont/Documents/git-repo-a1box5/a1webapp-root/a1webapp-service-scripting/src/main/java/com/acme/service/scripting/ScriptingService.java: 1. ERROR in /Users/simont/Documents/git-repo-a1box5/a1webapp-root/a1webapp-service-scripting/src/main/java/com/acme/service/scripting/ScriptingService.java (at line 0)
	package com.acme.service.scripting;
	^
Internal compiler error: java.lang.IllegalArgumentException: info cannot be null at org.eclipse.jdt.internal.compiler.codegen.StackMapFrame.addStackItem(StackMapFrame.java:81)

Is this related to:  https://github.com/groovy/groovy-eclipse/issues/246

[details.txt](https://github.com/groovy/groovy-eclipse/files/1217519/details.txt)

**Comment by simon-temple** [comment]
I just tried the latest groovy-eclipse-batch and it works!:

                   <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-eclipse-batch</artifactId>
                        <version>2.4.12-02</version>
                    </dependency>

So I guess it is related to https://github.com/groovy/groovy-eclipse/issues/246

Please feel free to close this issue...I'll watch 246
