### ISSUE TITLE
StringIndexOutOfBoundsException with clover plugin

### ISSUE THREAD

**Issue by YGDroid** [groovy/groovy-eclipse#354]
using maven 3.5 and my maven pom.xml is below
```java
<build>
    ...
    <plugins>

      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.6.1</version><!-- 3.1 is the minimum -->
        <configuration>
          <compilerId>groovy-eclipse-compiler</compilerId>
          <compilerArgument>indy</compilerArgument><!-- optional; supported by batch 2.4.12-04+ -->
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-eclipse-compiler</artifactId>
            <version>2.9.2-03</version>
          </dependency>
          <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-eclipse-batch</artifactId>
            <version>2.4.12-04</version>
          </dependency>
        </dependencies>
      </plugin>

	<plugin>
		<groupId>org.openclover</groupId>
		<artifactId>clover-maven-plugin</artifactId>
	</plugin>
    </plugins>
    ...
</build>
```
ref : https://github.com/groovy/groovy-eclipse/wiki/Groovy-Eclipse-Maven-plugin

when compiling source with above setting occurs StringIndexOutOfBoundsException 
command : mvn clean clover:setup test clover:aggregate clover:clover -X
```java
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 103
        at java.lang.String.substring(String.java:1963)
        at org.codehaus.groovy.eclipse.compiler.GroovyEclipseCompiler.parseMessage(GroovyEclipseCompiler.java:520)
        at org.codehaus.groovy.eclipse.compiler.GroovyEclipseCompiler.parseMessages(GroovyEclipseCompiler.java:464)
        at org.codehaus.groovy.eclipse.compiler.GroovyEclipseCompiler.compileOutOfProcess(GroovyEclipseCompiler.java:429)
        at org.codehaus.groovy.eclipse.compiler.GroovyEclipseCompiler.internalCompile(GroovyEclipseCompiler.java:123)
        at org.codehaus.groovy.eclipse.compiler.GroovyEclipseCompiler.performCompile(GroovyEclipseCompiler.java:88)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:943)
        ... 23 more
```

help me please!

**Comment by eric-milles** [comment]
Thanks for reporting.  Would you mind sharing the project you are compiling?  Or could you reduce it to the source that reproduces the error only?  I just need to see what message is being parsed so I can recreate and patch the issue.

**Comment by eric-milles** [comment]
For reference, here is the method with the exception; line 520 is the last line.

```java
    /**
     * Construct a CompilerError object from a line of the compiler output
     *
     * @param msgText
     *            output line from the compiler
     * @return the CompilerError object
     */
   private CompilerMessage parseMessage(String msgText, boolean showWarning, boolean force) {
        // message should look like this:
//        1. WARNING in /Users/andrew/git-repos/foo/src/main/java/packAction.java (at line 47)
//            public abstract class AbstractScmTagAction extends TaskAction implements BuildBadgeAction {
//                                  ^^^^^^^^^^^^^^^^^^^^

        // But there will also be messages contributed from annotation processors that will look non-normal
        int dotIndex = msgText.indexOf('.');
        Kind kind;
        boolean isNormal = false;
        if (dotIndex > 0) {
            if (msgText.substring(dotIndex, dotIndex + ". WARNING".length()).equals(". WARNING")) {
```

**Comment by eric-milles** [comment]
I cannot recreate the error without the source that is causing the exception.  My build with Clover runs fine.
