### ISSUE TITLE
Unable to connect to repository http://download.eclipse.org/technology/epp/packages/oxygen/content.xml

### ISSUE THREAD

**Issue by jonny7** [groovy/groovy-eclipse#356]
Hi

I'm new to Groovy and just following the install instructions from https://github.com/groovy/groovy-eclipse/blob/master/docs/Getting-Started-with-Groovy-Eclipse-Source-Code.md. Understand the error, just wondering if it's an eclipse issue with their server **_or_** the paths have changed.

Full error was: 

> ERROR: org.eclipse.equinox.p2.transport.ecf code=1002 Unable to connect to repository http://download.eclipse.org/technology/epp/packages/oxygen/content.xml 
java.net.ConnectException: Connection timed out: connect
  at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
  at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
  at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
  at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
  at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
  at java.net.PlainSocketImpl.connect(Unknown Source)
  at java.net.SocksSocketImpl.connect(Unknown Source)
  at java.net.Socket.connect(Unknown Source)
  at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:120)
  at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
  at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:328)
  at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
  at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
  at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
  at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:263)
  at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

Took 84 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.

**Comment by eric-milles** [comment]
It appears the site is still there because http://download.eclipse.org/technology/epp/packages/oxygen/ shows a boilerplate update site page.

Are you wanting to install Groovy-Eclipse for general development?  Or development of Groovy-Eclipse itself?

**Comment by jonny7** [comment]
For general development in Groovy (Grails actually), but this seemed like a good repo to try out :-)

**Comment by eric-milles** [comment]
It is much simpler to add Groovy-Eclipse to a standard Eclipse distribution.  The getting-started guide you mention is for setting up a PDE workspace suitable for developing Groovy-Eclipse, which requires a bunch of extras.

You can add Groovy-Eclipse to Eclipse using the Help > Install New Software... > Add... and enterring the update site that is appropriate for the Eclipse level you have.  One example would be http://dist.springsource.org/snapshot/GRECLIPSE/e4.7/

**Comment by jonny7** [comment]
Ok thanks!

**Comment by Golubcheck** [comment]
ваш продукт гамно
