### ISSUE TITLE
Can't open Grails views: "Editor could not be initialized"

### ISSUE THREAD

**Issue by rvargas** [groovy/groovy-eclipse#357]
Hi,

I'm having a weird problem since the last update. When I'm try to open a gsp file, I've got this message:

![Editor could not be initialized](https://i.imgur.com/uoLgVPa.png)

Stacktrace is:

```
java.lang.NoSuchMethodError: org.grails.ide.eclipse.editor.groovy.elements.GroovyClassFileWorkingCopy.openWhenClosed(Ljava/lang/Object;Lorg/eclipse/core/runtime/IProgressMonitor;)Ljava/lang/Object;
	at org.grails.ide.eclipse.editor.groovy.elements.GroovyClassFileWorkingCopy.getPerWorkingCopyInfo(GroovyClassFileWorkingCopy.java:169)
	at org.eclipse.jdt.internal.core.CompilationUnit.isWorkingCopy(CompilationUnit.java:1079)
	at org.grails.ide.eclipse.editor.groovy.elements.AbstractGrailsElement.getGroovyClass(AbstractGrailsElement.java:66)
	at org.grails.ide.eclipse.editor.groovy.elements.TagLibClass.getNamespace(TagLibClass.java:290)
	at org.grails.ide.eclipse.editor.gsp.tags.PerProjectTagProvider.initializeTaglibs(PerProjectTagProvider.java:360)
	at org.grails.ide.eclipse.editor.gsp.tags.PerProjectTagProvider.initializeAllTags(PerProjectTagProvider.java:232)
	at org.grails.ide.eclipse.editor.gsp.tags.PerProjectTagProvider.ensureInitialized(PerProjectTagProvider.java:206)
	at org.grails.ide.eclipse.editor.gsp.tags.PerProjectTagProvider.getCorrespondingCMDocument(PerProjectTagProvider.java:473)
	at org.grails.ide.eclipse.editor.gsp.tags.GSPModelQueryCMProvider.getCorrespondingCMDocument(GSPModelQueryCMProvider.java:74)
	at org.eclipse.wst.xml.core.internal.contentmodel.modelqueryimpl.SimpleAssociationProvider.getCorrespondingCMDocument(SimpleAssociationProvider.java:36)
	at org.eclipse.wst.xml.core.internal.contentmodel.modelqueryimpl.SimpleAssociationProvider.getCMElementDeclaration(SimpleAssociationProvider.java:42)
	at org.eclipse.wst.xml.core.internal.contentmodel.modelqueryimpl.ModelQueryImpl.getCMElementDeclaration(ModelQueryImpl.java:116)
	at org.eclipse.jst.jsp.core.internal.modelquery.JSPModelQueryImpl.getCMElementDeclaration(JSPModelQueryImpl.java:49)
	at org.eclipse.wst.xml.core.internal.document.ElementImpl.getDeclaration(ElementImpl.java:360)
	at org.eclipse.wst.xml.core.internal.document.ElementImpl.isContainer(ElementImpl.java:845)
	at org.eclipse.wst.xml.core.internal.document.XMLModelParser.insertStartTag(XMLModelParser.java:1405)
	at org.eclipse.wst.xml.core.internal.document.XMLModelParser.insertStartTag(XMLModelParser.java:1499)
	at org.eclipse.wst.xml.core.internal.document.XMLModelParser.insertStructuredDocumentRegion(XMLModelParser.java:1510)
	at org.eclipse.wst.xml.core.internal.document.XMLModelParser.replaceStructuredDocumentRegions(XMLModelParser.java:2354)
	at org.eclipse.wst.xml.core.internal.document.DOMModelImpl.internalSetNewDocument(DOMModelImpl.java:661)
	at org.eclipse.wst.xml.core.internal.document.DOMModelImpl.setStructuredDocument(DOMModelImpl.java:936)
	at org.grails.ide.eclipse.editor.gsp.model.GSPStructuredModel.setStructuredDocument(GSPStructuredModel.java:97)
	at org.eclipse.wst.sse.core.internal.model.AbstractModelLoader.createModel(AbstractModelLoader.java:127)
	at org.eclipse.wst.sse.core.internal.FileBufferModelManager.getModel(FileBufferModelManager.java:852)
	at org.eclipse.wst.sse.core.internal.model.ModelManagerImpl._getModelFor(ModelManagerImpl.java:639)
	at org.eclipse.wst.sse.core.internal.model.ModelManagerImpl.getModelForEdit(ModelManagerImpl.java:1380)
	at org.eclipse.wst.sse.ui.StructuredTextEditor.tryToGetModel(StructuredTextEditor.java:2004)
	at org.eclipse.wst.sse.ui.StructuredTextEditor.doSetInput(StructuredTextEditor.java:1944)
	at org.eclipse.ui.texteditor.AbstractTextEditor$19.run(AbstractTextEditor.java:3220)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:466)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:374)
	at org.eclipse.ui.internal.WorkbenchWindow$13.run(WorkbenchWindow.java:2157)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2153)
	at org.eclipse.ui.texteditor.AbstractTextEditor.internalInit(AbstractTextEditor.java:3238)
	at org.eclipse.ui.texteditor.AbstractTextEditor.init(AbstractTextEditor.java:3265)
	at org.eclipse.wst.sse.ui.StructuredTextEditor.init(StructuredTextEditor.java:2620)
	at org.eclipse.ui.internal.EditorReference.initialize(EditorReference.java:390)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:305)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:888)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:869)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:120)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:337)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:258)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:104)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:73)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:55)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:127)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:983)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:662)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:766)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$2(PartRenderingEngine.java:737)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$7.run(PartRenderingEngine.java:731)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:715)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$1.handleEvent(PartServiceImpl.java:95)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:187)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:156)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4590)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:218)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:81)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:59)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:171)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:488)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:454)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:705)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:392)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1145)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3210)
	at org.eclipse.ui.internal.WorkbenchPage.access$23(WorkbenchPage.java:3125)
	at org.eclipse.ui.internal.WorkbenchPage$9.run(WorkbenchPage.java:3107)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3102)
```

**Comment by eric-milles** [comment]
What version of Eclipse and Groovy-Eclipse do you have installed?

**Comment by eric-milles** [comment]
For reference, this is from `org.codehaus.jdt.groovy.model.GroovyClassFileWorkingCopy`.  `org.grails.ide.eclipse.editor.groovy.elements.GroovyClassFileWorkingCopy` either inherits or re-implements this.  [openWhenClosed](https://github.com/eclipse/eclipse.jdt.core/blob/master/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/JavaElement.java#L578) accepts 3 parameters.  The [version that accepts 2 params](https://github.com/eclipse/eclipse.jdt.core/blob/R3_5_maintenance/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/JavaElement.java#L510) is from Eclipse 3.5 and earlier.

```java
    public PerWorkingCopyInfo getPerWorkingCopyInfo() {
        if (elementInfo == null) {
            try {
                elementInfo = (CompilationUnitElementInfo) createElementInfo();
                openWhenClosed(elementInfo, true, new NullProgressMonitor());
            } catch (JavaModelException e) {
                elementInfo = null;
                Activator.getDefault().getLog().log(e.getJavaModelStatus());
            }
        }
        return info;
    }
```

**Comment by rvargas** [comment]
Oh, sorry I forgot to post that info.

I'm using Eclipse 3.6.4.RELEASE, Build: 201503100339, Eclipse Luna SR1 (4.4.2 ) (latest GGTS) and Groovy-Eclipse 2.9.2.xx-201710310549-e44 .

**Comment by eric-milles** [comment]
I could reintroduce the legacy compatibility, but really GGTS should not be using this API that was removed 6-7 years ago.

**Comment by eric-milles** [comment]
Should work after the next build.  Just don't update past Eclipse Mars if the GGTS version remains unpatched.

**Comment by rvargas** [comment]
Thanks for your support :)

**Comment by rvargas** [comment]
It worked, thanks!
