### ISSUE TITLE
An internal error occurred during: "Requesting Java AST from selection" using recent 2.9.2 and 2.9.3 with GGTS

### ISSUE THREAD

**Issue by ClemensSchneider** [groovy/groovy-eclipse#450]
Using the Grails/Groovy Tool Suite `3.6.4.RELEASE` (which is no longer maintained) which depends on groovy-eclipse, the following error occurs when opening Grails-artefact classes (services/controllers/...):

```
An internal error occurred during: "Requesting Java AST from selection". org.codehaus.groovy.eclipse.core.compiler.GroovySnippetCompiler.(Lorg/codehaus/groovy/eclipse/core/model/GroovyProjectFacade;)V
```

The stacktrace is as follows:

```
java.lang.NoSuchMethodError: org.codehaus.groovy.eclipse.core.compiler.GroovySnippetCompiler.<init>(Lorg/codehaus/groovy/eclipse/core/model/GroovyProjectFacade;)V
    at org.grails.ide.eclipse.editor.groovy.types.PerProjectTypeCache.setProject(PerProjectTypeCache.java:107)
    at org.grails.ide.eclipse.core.internal.plugins.GrailsCore$PerProjectCacheManager.get(GrailsCore.java:54)
    at org.grails.ide.eclipse.core.internal.plugins.GrailsCore.connect(GrailsCore.java:199)
    at org.grails.ide.eclipse.editor.groovy.elements.GrailsProject.findAllServices(GrailsProject.java:510)
    at org.grails.ide.eclipse.editor.groovy.types.PerProjectServiceCache.ensureInitialized(PerProjectServiceCache.java:108)
    at org.grails.ide.eclipse.editor.groovy.types.PerProjectServiceCache.findServicesFor(PerProjectServiceCache.java:93)
    at org.grails.ide.eclipse.editor.groovy.elements.AbstractGrailsElement.populateInjectedServices(AbstractGrailsElement.java:148)
    at org.grails.ide.eclipse.editor.groovy.elements.ControllerClass.initializeTypeLookup(ControllerClass.java:284)
    at org.grails.ide.eclipse.editor.groovy.types.GrailsTypeLookup.initialize(GrailsTypeLookup.java:100)
    at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitCompilationUnit(TypeInferencingVisitorWithRequestor.java:347)
    at org.codehaus.groovy.eclipse.codebrowsing.requestor.CodeSelectHelper.selectASTNode(CodeSelectHelper.java:126)
    at org.codehaus.groovy.eclipse.search.GroovyOccurrencesFinder.initialize(GroovyOccurrencesFinder.java:181)
    at org.codehaus.groovy.eclipse.search.GroovyOccurrencesFinder.findOccurrences(GroovyOccurrencesFinder.java:209)
    at org.codehaus.groovy.eclipse.editor.GroovyEditor.updateOccurrenceAnnotations(GroovyEditor.java:1317)
    at org.eclipse.jdt.internal.ui.javaeditor.JavaEditor$6.selectionChanged(JavaEditor.java:3380)
    at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup.calculateASTandInform(SelectionListenerWithASTManager.java:178)
    at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup$3.run(SelectionListenerWithASTManager.java:155)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

The issue seems to have started with recent versions of 2.9.2 (same with 2.9.3). The latest known configuration of my GGTS install was using `2.9.2.xx-201706270121-e44` and it broke when upgrading to `2.9.2.xx-201801052226-e44-RELEASE`.

Is there anything that can be fixed to restore compatibility with libraries that depend on 2.9.2?

Also: is there any way to get hold of older versions of the update-site to be able to downgrade in case of incompatibilities?

See also https://stackoverflow.com/questions/48383234/error-in-eclipse-project-grails-groovy/48557343#48557343

**Comment by eric-milles** [comment]
Sorry, not much I can do in terms of 2.9.2.  It was in snapshot for so long that there are not many records of previous builds.  However, I did make sure a maintenance path was retained for 2.9 (hence 2.9.3 snapshots).  So if you find any incompatibilities with Grails tooling, please feel free to create an issue report here.

Also, if https://github.com/spring-projects/grails-ide is still being maintained, that project should be alerted of incompatibilities with groovy-eclipse 3.

**Comment by eric-milles** [comment]
ready to go

**Comment by ClemensSchneider** [comment]
Works like a charm, big thanks!

**Comment by doteo78** [comment]
We are trying to freeze an IDE for maintenance of our old Grails 2.5.6 applications. Whether we use GGTS 3.6.4-e4.5 or Eclipse Neon we encounter this issue after installing the latest Groovy-Eclipse release from the update site appropriate for the Eclipse version. In our case, 4.5 or 4.6.

I believe this is happening because 2.9.2.xx-201801052009-e45-RELEASE and 2.9.2.xx-201801051705-e46-RELEASE contain this bug.

Any chance of getting the 2.9.3 snapshot version which solves the issue from somewhere?

**Comment by eric-milles** [comment]
@doteo78 You can pull down the `2_9_maintenance` branch and run `mvn -Pe46 clean package` to generate an update site archive of 2.9.3-SNAPSHOT.  If you need me to do the work and host the snapshot, I'll need some kind of maintenance contract.

**Comment by doteo78** [comment]
Thank you for the hint! I generated the update site zip and installed in GGTS 3.6.4-e4.5 using jdk8u372-b07. Now we see this error:

`An internal error occurred during: "Requesting Java AST from selection".`

Exception Stack Trace:
```
java.lang.NoSuchFieldError: GROOVY_OBJECT_SUPPORT
	at org.grails.ide.eclipse.editor.groovy.elements.DomainClass$NamedQueryClassNode.<init>(DomainClass.java:75)
	at org.grails.ide.eclipse.editor.groovy.elements.DomainClass.getNamedQueryProxyType(DomainClass.java:409)
	at org.grails.ide.eclipse.editor.groovy.elements.DomainClass.createNamedCriteria(DomainClass.java:401)
	at org.grails.ide.eclipse.editor.groovy.elements.DomainClass.lookupTypeAndDeclaration(DomainClass.java:350)
	at org.grails.ide.eclipse.editor.groovy.types.GrailsTypeLookup.lookupTypeAndDeclaration(GrailsTypeLookup.java:82)
	at org.eclipse.jdt.groovy.search.AbstractSimplifiedTypeLookup.lookupType(AbstractSimplifiedTypeLookup.java:129)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.lookupExpressionType(TypeInferencingVisitorWithRequestor.java:2418)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.handleSimpleExpression(TypeInferencingVisitorWithRequestor.java:1951)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitConstantExpression(TypeInferencingVisitorWithRequestor.java:1127)
	at org.codehaus.groovy.ast.expr.ConstantExpression.visit(ConstantExpression.java:85)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitPropertyExpression(TypeInferencingVisitorWithRequestor.java:1621)
	at org.codehaus.groovy.ast.expr.PropertyExpression.visit(PropertyExpression.java:57)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitMethodCallExpression(TypeInferencingVisitorWithRequestor.java:1494)
	at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:66)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitBinaryExpression(TypeInferencingVisitorWithRequestor.java:912)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitDeclarationExpression(CodeVisitorSupport.java:250)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitDeclarationExpression(ClassCodeVisitorSupport.java:153)
	at org.codehaus.groovy.ast.expr.DeclarationExpression.visit(DeclarationExpression.java:89)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:74)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitExpressionStatement(ClassCodeVisitorSupport.java:280)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:42)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:40)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:250)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitBlockStatement(TypeInferencingVisitorWithRequestor.java:984)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:71)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:147)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:158)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitConstructorOrMethod(TypeInferencingVisitorWithRequestor.java:1212)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitJDT(TypeInferencingVisitorWithRequestor.java:519)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitJDT(TypeInferencingVisitorWithRequestor.java:390)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitCompilationUnit(TypeInferencingVisitorWithRequestor.java:354)
	at org.codehaus.groovy.eclipse.search.GroovyOccurrencesFinder.internalFindOccurences(GroovyOccurrencesFinder.java:156)
	at org.codehaus.groovy.eclipse.search.GroovyOccurrencesFinder.getOccurrences(GroovyOccurrencesFinder.java:84)
	at org.codehaus.groovy.eclipse.search.GroovyOccurrencesFinder.findOccurrences(GroovyOccurrencesFinder.java:210)
	at org.codehaus.groovy.eclipse.editor.GroovyEditor.updateOccurrenceAnnotations(GroovyEditor.java:1317)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaEditor$6.selectionChanged(JavaEditor.java:3386)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup.calculateASTandInform(SelectionListenerWithASTManager.java:178)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup$3.run(SelectionListenerWithASTManager.java:155)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

If we minimize the pop-up error window autocompletion and code suggestion seems to work fine but I'm not sure if this is the best thing to do...

**Comment by eric-milles** [comment]
Can you open a new issue ticket for this?

**Comment by doteo78** [comment]
Done!

#1498
