### ISSUE TITLE
Constent UI freeze - unhandled event loop exception makes editor unusable

### ISSUE THREAD

**Issue by admxiii** [groovy/groovy-eclipse#519]
groovy-eclipse throws this internal error on almost any keyboard action and makes the editor almost unusable. This happens with latest snapshot (Version: 3.0.0.xx-201803062249-e47) and release (2.9.2) versions for Eclipse Oxygen.2 Release (4.7.2). I am using latest groovy 2.4.13 and 2.4.14.

Unhandled event loop exception

java.lang.NullPointerException
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyClassScope.augmentMethodBindings(GroovyClassScope.java:185)
	at org.eclipse.jdt.internal.compiler.lookup.ClassScope.buildMethods(ClassScope.java:387)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.initializeForStaticImports(SourceTypeBinding.java:1397)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.findField(Scope.java:1424)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.findField(Scope.java:1328)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getBinding(Scope.java:2078)
	at org.eclipse.jdt.internal.compiler.lookup.BlockScope.getBinding(BlockScope.java:485)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedNameReference.resolveType(QualifiedNameReference.java:999)
	at org.eclipse.jdt.internal.compiler.ast.ArrayInitializer.resolveTypeExpecting(ArrayInitializer.java:186)
	at org.eclipse.jdt.internal.compiler.ast.MemberValuePair.resolveTypeExpecting(MemberValuePair.java:135)
	at org.eclipse.jdt.internal.compiler.ast.Annotation.resolveType(Annotation.java:862)
	at org.eclipse.jdt.internal.compiler.ast.ASTNode.resolveAnnotations(ASTNode.java:857)
	at org.eclipse.jdt.internal.compiler.ast.ASTNode.resolveAnnotations(ASTNode.java:716)
	at org.eclipse.jdt.internal.compiler.lookup.FieldBinding.getAnnotationTagBits(FieldBinding.java:312)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypeFor(SourceTypeBinding.java:1766)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.getField(SourceTypeBinding.java:1210)
	at org.eclipse.jdt.internal.compiler.lookup.LazilyResolvedMethodBinding.getTypeBinding(LazilyResolvedMethodBinding.java:48)
	at org.eclipse.jdt.internal.compiler.lookup.LazilyResolvedMethodBinding.getReturnTypeBinding(LazilyResolvedMethodBinding.java:65)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesWithSuspendedTempErrorHandlingPolicy(SourceTypeBinding.java:1901)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesFor(SourceTypeBinding.java:1856)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.methods(SourceTypeBinding.java:1546)

**Comment by admxiii** [comment]
it is working now. thanks!
