### ISSUE TITLE
"Path must include project and resource name" when Groovy nature added

### ISSUE THREAD

**Issue by gregg-saffell** [groovy/groovy-eclipse#550]
Recently (within the last week or two I think), I have two eclipse projects that started reporting the above captioned error. If I remove the groovy nature from the project, the error goes away.  I do have other eclipse projects using groovy that do not have this problem.  I can zip up one of the projects and attach it but it has many dependencies so I don't know if that will help you.

Thanks!

**Comment by eric-milles** [comment]
Is there an entry in your Error Log for this?  If you could zip up the project that would be helpful.  If you could reduce it to the smallest that still produces the error, that would also be appreciated.

**Comment by gregg-saffell** [comment]
The error is: 

eclipse.buildId=4.7.3.M20180301-0715
java.version=1.8.0_162
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.jdt.core
Error
Fri Apr 06 12:26:02 EDT 2018
Errors running builder 'Java Builder' on project 'ec_test'.

java.lang.IllegalArgumentException: Path must include project and resource name: /ec_test
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2074)
	at org.eclipse.core.internal.resources.Container.getFile(Container.java:193)
	at org.eclipse.jdt.core.util.CompilerUtils.configureOptionsBasedOnNature(CompilerUtils.java:51)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.newCompiler(AbstractImageBuilder.java:566)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.<init>(AbstractImageBuilder.java:103)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.<init>(BatchImageBuilder.java:34)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:255)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:175)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

I should be on the latest release of the plugin. I have been accepting the updates that seem to be coming out every other day.  I will try to reduce the project as much as possible and zip it.

**Comment by eric-milles** [comment]
The exception is coming out if this sequence:
```java
IProject project = javaProject.getProject();
if (isGroovyNaturedProject(project)) {
    options.groovyExcludeGlobalASTScan = project.getFile(javaProject.getOutputLocation().removeFirstSegments(1)).getRawLocation().toOSString();
```
FYI, this was recently refactored, so I probably introduced a bug in the process.

Does your project "ec_test" output to it's base directory?  All I need at the moment from your project is the ".classpath" file.

**Comment by gregg-saffell** [comment]
Super. Love seeing all this activity on the plugin. Despite the awesomeness of Groovy, I still have to deal with naysayers in my organization so every little bit helps.

Thanks!
