### ISSUE TITLE
After updating Eclipse to 4.7.3a: "An internal error occurred during: "Requesting Java AST from selection"."

### ISSUE THREAD

**Issue by rste79** [groovy/groovy-eclipse#556]
I'm using Groovy-Eclipse 2.9.2 and I've just update Eclipse to 4.7.3a: now, for each action I take in the code editor (edit code, click, undo, ...) a popup appears with the following error

An internal error occurred during: "Requesting Java AST from selection".
java.lang.IllegalArgumentException

Looking at Eclipse logs I can find these errors:

**1. Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ui".**

```
eclipse.buildId=4.7.3.M20180330-0640
java.version=1.8.0_144
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=it_IT
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.jdt.ui
Error
Thu Apr 12 12:31:59 CEST 2018
Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ui".

java.lang.IllegalArgumentException: Unsupported JLS level
	at org.eclipse.jdt.core.dom.AST.<init>(AST.java:762)
	at org.eclipse.jdt.core.dom.AST.newAST(AST.java:325)
	at org.eclipse.jdt.core.dom.AST.convertCompilationUnit(AST.java:286)
	at org.codehaus.jdt.groovy.model.GroovyReconcileWorkingCopyOperation.makeConsistent(GroovyReconcileWorkingCopyOperation.java:102)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:90)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:724)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:790)
	at org.codehaus.jdt.groovy.model.GroovyCompilationUnit.reconcile(GroovyCompilationUnit.java:426)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:128)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.access$0(JavaReconcilingStrategy.java:110)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:90)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:87)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:154)
	at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.reconcile(CompositeReconcilingStrategy.java:89)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconcile(JavaCompositeReconcilingStrategy.java:104)
	at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:73)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:207)
```

**2. An internal error occurred during: "Requesting Java AST from selection".**

```
eclipse.buildId=4.7.3.M20180330-0640
java.version=1.8.0_144
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=it_IT
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.core.jobs
Error
Thu Apr 12 12:31:55 CEST 2018
An internal error occurred during: "Requesting Java AST from selection".

java.lang.IllegalArgumentException
	at org.eclipse.jdt.core.dom.ASTParser.<init>(ASTParser.java:234)
	at org.eclipse.jdt.core.dom.ASTParser.newParser(ASTParser.java:131)
	at org.eclipse.jdt.internal.ui.javaeditor.ASTProvider.createAST(ASTProvider.java:527)
	at org.eclipse.jdt.internal.ui.javaeditor.ASTProvider.getAST(ASTProvider.java:481)
	at org.eclipse.jdt.internal.ui.javaeditor.ASTProvider.getAST(ASTProvider.java:471)
	at org.eclipse.jdt.ui.SharedASTProvider.getAST(SharedASTProvider.java:128)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup.calculateASTandInform(SelectionListenerWithASTManager.java:173)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionListenerWithASTManager$PartListenerGroup$3.run(SelectionListenerWithASTManager.java:158)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**3. Error in JDT Core during reconcile** (different messages but same stacktrace as number 1)

```
eclipse.buildId=4.7.3.M20180330-0640
java.version=1.8.0_144
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=it_IT
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.jdt.ui
Error
Thu Apr 12 12:31:55 CEST 2018
Error in JDT Core during reconcile

java.lang.IllegalArgumentException: Unsupported JLS level
	at org.eclipse.jdt.core.dom.AST.<init>(AST.java:762)
	at org.eclipse.jdt.core.dom.AST.newAST(AST.java:325)
	at org.eclipse.jdt.core.dom.AST.convertCompilationUnit(AST.java:286)
	at org.codehaus.jdt.groovy.model.GroovyReconcileWorkingCopyOperation.makeConsistent(GroovyReconcileWorkingCopyOperation.java:102)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:90)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:724)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:790)
	at org.codehaus.jdt.groovy.model.GroovyCompilationUnit.reconcile(GroovyCompilationUnit.java:426)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:128)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.access$0(JavaReconcilingStrategy.java:110)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:90)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:87)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:154)
	at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.reconcile(CompositeReconcilingStrategy.java:89)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconcile(JavaCompositeReconcilingStrategy.java:104)
	at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:73)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:207)


```
Thanks

**Comment by eric-milles** [comment]
Support for Eclipse Oxygen 4.7.3+ is available in Groovy-Eclipse 3.0.0. You can update using the snapshot site or the Eclipse Marketplace.

**Comment by rste79** [comment]
Thank you Eric, I have updated to 3.0.0 using Marketplace and it works.

**Comment by samized** [comment]
Thanks for the tip. Is this fix also coming to the release branch anytime soon?

**Comment by eric-milles** [comment]
You can track the progress of the 3.0 release here: https://github.com/groovy/groovy-eclipse/milestone/1
