### ISSUE TITLE
Java refactoring leads to OOM

### ISSUE THREAD

**Issue by mpiggott** [groovy/groovy-eclipse#594]
Was not experiencing this with *3.0.0.xx-201804160310-e47* but after upgrading to *3.0.0.xx-201805301411-e47* and subsequently *3.0.0.xx-201806030023-e47* attempts to refactor in Java code never completes before Eclipse goes OOM.

Checking a heap dump:
```
org.codehaus.groovy.ast.ClassNode	11.148833683217271	3,516,234 (11.1%)	910,704,606 (37.2%)
org.codehaus.groovy.ast.Parameter	3.743586914372446	1,180,691 (3.7%)	134,598,774 (5.5%)
java.util.ArrayList	13.026979586880131	4,108,583 (13%)	131,474,656 (5.4%)
java.util.HashMap$Node[]	2.4051310392234635	758,555 (2.4%)	120,868,680 (4.9%)
org.codehaus.groovy.ast.GenericsType	4.3356247798362855	1,367,414 (4.3%)	113,495,362 (4.6%)
java.util.LinkedHashMap$Entry	5.063944579145269	1,597,119 (5.1%)	95,827,140 (3.9%)
org.codehaus.groovy.ast.MethodNode	1.9489534078885749	614,681 (1.9%)	95,275,555 (3.9%)
org.codehaus.groovy.ast.ClassNode$MapOfLists	11.149680253324215	3,516,501 (11.1%)	84,396,024 (3.4%)
```

About twice this number of classes (java string, java collections and groovy classes) trailing down to 1%

Below is the relevant thread, Junit5 isn't on the classpath nor do I believe Groovy code would be affected by the refactoring:

```
"ModalContext" #157 prio=6 os_prio=0 tid=0x0000000029872800 nid=0xa28 runnable [0x000000003f9dd000]
   java.lang.Thread.State: RUNNABLE
        at java.util.HashMap.putVal(HashMap.java:631)
        at java.util.HashMap.put(HashMap.java:612)
        at org.codehaus.groovy.ast.VariableScope.putDeclaredVariable(VariableScope.java:119)
        at org.codehaus.groovy.ast.MethodNode.setParameters(MethodNode.java:160)
        at org.codehaus.groovy.ast.MethodNode.<init>(MethodNode.java:62)
        at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:405)
        at org.codehaus.groovy.ast.ClassNode.lazyClassInit(ClassNode.java:358)
        - locked <0x00000000e4274600> (a java.lang.Object)
        at org.codehaus.groovy.ast.ClassNode.getDeclaredMethods(ClassNode.java:970)
        at org.codehaus.groovy.ast.ClassNode.getMethods(ClassNode.java:985)
        at org.eclipse.jdt.groovy.search.CategoryTypeLookup.lookupType(CategoryTypeLookup.java:56)
        at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.lookupExpressionType(TypeInferencingVisitorWithRequestor.java:2371)
        at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.getMethodCallArgumentTypes(TypeInferencingVisitorWithRequestor.java:2068)
        at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.handleSimpleExpression(TypeInferencingVisitorWithRequestor.java:1836)
        at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitConstantExpression(TypeInferencingVisitorWithRequestor.java:978)
        at org.codehaus.groovy.ast.expr.ConstantExpression.visit(ConstantExpression.java:85)
        at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitMethodCallExpression(TypeInferencingVisitorWithRequestor.java:1385)
        at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:70)
        at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:123)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitExpressionStatement(ClassCodeVisitorSupport.java:280)
        at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:42)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:147)
        at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitConstructorOrMethod(TypeInferencingVisitorWithRequestor.java:1065)
        at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitJDT(TypeInferencingVisitorWithRequestor.java:403)
        at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitJDT(TypeInferencingVisitorWithRequestor.java:277)
        at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitCompilationUnit(TypeInferencingVisitorWithRequestor.java:241)
        at org.codehaus.jdt.groovy.integration.internal.GroovyLanguageSupport.maybePerformDelegatedSearch(GroovyLanguageSupport.java:235)
        at org.codehaus.jdt.groovy.integration.LanguageSupportFactory.maybePerformDelegatedSearch(LanguageSupportFactory.java:114)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1267)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1389)
        at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1506)
        at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:122)
        at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:236)
        at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:583)
        at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:608)
        at org.eclipse.jdt.internal.corext.refactoring.RefactoringSearchEngine.internalSearch(RefactoringSearchEngine.java:143)
        at org.eclipse.jdt.internal.corext.refactoring.RefactoringSearchEngine.search(RefactoringSearchEngine.java:130)
        at org.eclipse.jdt.internal.corext.refactoring.rename.RenameMethodProcessor.getOccurrences(RenameMethodProcessor.java:491)
        at org.eclipse.jdt.internal.corext.refactoring.rename.RenameMethodProcessor.doCheckFinalConditions(RenameMethodProcessor.java:388)
        at org.eclipse.jdt.internal.corext.refactoring.rename.RenameVirtualMethodProcessor.doCheckFinalConditions(RenameVirtualMethodProcessor.java:146)
        at org.eclipse.jdt.internal.corext.refactoring.rename.JavaRenameProcessor.checkFinalConditions(JavaRenameProcessor.java:48)
        at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.checkFinalConditions(ProcessorBasedRefactoring.java:222)
        at org.eclipse.ltk.core.refactoring.Refactoring.checkAllConditions(Refactoring.java:162)
        at org.eclipse.jdt.internal.ui.refactoring.RefactoringExecutionHelper$Operation.run(RefactoringExecutionHelper.java:81)
        at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:39)
        at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:724)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
        at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5680)
        at org.eclipse.jdt.internal.ui.actions.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:105)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

**Comment by eric-milles** [comment]
How much heap space is allocated to Eclipse?  Certainly the change to read DGMs from the runtime caused an increase in memory usage.   What I can't tell is if you allocated 1000m and were running at 950m and this change pushed you over the limit or of you allocated 1000m and were running at 500m.

**Comment by mpiggott** [comment]
> How much heap space is allocated to Eclipse? Certainly the change to read DGMs from the runtime caused an increase in memory usage. What I can't tell is if you allocated 1000m and were running at 950m and this change pushed you over the limit or of you allocated 1000m and were running at 500m.

The *eclipse.ini* has *-Xmx 2048m*

**Comment by eric-milles** [comment]
Is it possible to get a before and after picture?  That is, can you use the 2.9.2 release and the 3.0.0 snapshot to complete the same action and capture memory stats for both?  Otherwise, what do you need to set `-Xmx` to to get it to complete?

Also, how many and how large of project's are you developing?  The refactoring you are performing, is it very localized or does it impact a lot of sources?

**Comment by mpiggott** [comment]
I've recently switched to Photon and bumping the memory to 4096 (didn't try any steps between) allows the refactoring to complete, the builtin Eclipse heap monitor displayed ~2g/3g. A heap dump after the refactoring shows 1.4 million instances of `ClassNode` consuming ~850mib of memory which isn't freed.

While writing this comment I discovered the same issue occurs while finding references to this particular method. The method's signature is `get(Class<T>, String, Map<String, String>, String...)`, post refactoring there are 41 references which are all in source prior to refactoring 410+ are found including many spurious references in dependencies which appear to be references to 1-arg get() methods. The same class also has a `get(Class<T>, String)` method which does not exhibit this issue and has a handful of spurious non-source references.

**Comment by eric-milles** [comment]
ClassNodes are often cached by Groovy runtime.  If you disable auto build and run clean, how much of the 850mb of classnodes is released?  Are there a lot of ModuleNode instances on your heap after the refactor (before running clean)?

Finding referenced (which refactoring does as one of its steps) requires loading a lot of class info, especially for common methods like get.

**Comment by mpiggott** [comment]
> ClassNodes are often cached by Groovy runtime. If you disable auto build and run clean, how much of the 850mb of classnodes is released? Are there a lot of ModuleNode instances on your heap after the refactor (before running clean)?

I'm not sure about the exact steps you intended but starting with a built workspace there are 0 `ModuleNode` and 4k `ClassNode` instances on the heap.  At this point I disabled automatic building and refactored which resulted in 308 instances of `ModuleNode` consuming 53k and 3.4 million instances of `ClassNode` (not sure if I misread previously or if its different for some reason). Running Clean at this point (without triggering a build) seems to have no impact and there the exact same number of instances of both classes on the heap.

If I use git to wipe out my changes and refactor it capturing another heap dump while its thrashing shows the number of instances and memory usage of both those classes doubling.

**Comment by eric-milles** [comment]
In your original post you mention things were well with 3.0.0.xx-201804160310-e47 but after upgrading to 3.0.0.xx-201805301411-e47 this issue began.  What changed was to cache category methods (aka DGMs) with the ModuleNode.  Typically an instance of this is created to parse or compile a groovy source and then should be disposed.  You mentioned that 308 instances are remaining.  I will see if I can understand why these ModuleNodes are being retained after building or refactoring.  If they can be disposed, quire a large data structure will be freed as well.

**Comment by eric-milles** [comment]
I found 2 maps that are holding references after build/clean.  One is `org.codehaus.groovy.ast.tools.GenericsUtils.PARAMETERIZED_TYPE_CACHE` -- it lives on for the life of the IDE and is never cleared.  The other is `org.codehaus.groovy.eclipse.dsl.pointcuts.impl.SubTypePointcut.cachedHierarchies`.  I can make this a `WeakHashMap` so it does not cause retention by itself.  However, I still found the DSLD support holding references to `ModuleNode`s.

If you do not use DLSD support, you can disable it and a lot of the heap usage would decrease.  You can turn it off at _Window > Preferences > Groovy > DSLD_.

**Comment by eric-milles** [comment]
ready for test

**Comment by mpiggott** [comment]
> ready for test

I still see the same issue with *3.0.0.xx-201807030305-e48*. 

> In your original post you mention things were well with 3.0.0.xx-201804160310-e47 but after upgrading to 3.0.0.xx-201805301411-e47 this issue began. 

I'm not sure the lower bound is accurate, the issue may have existed but I hadn't done a refactoring large enough to run out of memory and notice (e.g. refactoring the other `get` I mentioned above only leaves 7m on the heap). 

I wonder if there shouldn't be two different issues considered here - the first being the memory leak and the second being the amount of memory required for some finding references in some instances. Perhaps fixing the leak would also reduce the amount of memory required.

**Comment by eric-milles** [comment]
Since the IDE is a long-running process, it will keep a certain amount of information about the open projects in memory.  I don't think it is a fair expectation to run a refactoring and have the memory usage return to the previous level.  Even after running a clean, there are in-memory indexes that have been exercised from previous operations.

I have taken a look at heap dumps and I think retention of `JDTResolver` is one of the bigger memory users, since it caches a lot of `JDTClassNode`s and a lot of stuff keeps a reference back to it.  If you can walk your heap dumps and find a memory leak, I should be able to patch it.  I have spent a few hours myself looking at dumps and have tried to clean up some references with mixed results.

**Comment by mpiggott** [comment]
> Since the IDE is a long-running process, it will keep a certain amount of information about the open projects in memory. I don't think it is a fair expectation to run a refactoring and have the memory usage return to the previous level. Even after running a clean, there are in-memory indexes that have been exercised from previous operations.

Sure, but shouldn't they be re-used? If it isn't a leak why does re-running the refactoring (or just finding references) consume double the instances of `ClassNode`? 

While not being familiar with jdt/groovy-eclipse internals it also seems very strange to me that 70 groovy classes totalling ~175kb on disk without any references to the method being found/refactored requires 850mb of memory. It makes me wonder if something might be repeatedly creating the `ClassNode` instances within the same refactoring instead of re-using them.

**Comment by eric-milles** [comment]
Re reuse: In general the `ClassNode` instances are not reused.  It seems logical from the outside that they would be.  In fact, one single source unit is parsed and resolved something like 5 times just to show it in the editor.  And this is repeated for every edit/save.  There is a *ton* of inefficient stuff, but the integration with JDT is very complex and the current design attempts to keep things somewhat compartmentalized.

I can't speak for what Eclipse spins up for a refactoring, but Groovy needs to parse and resolve source units and generally investigate all your library dependencies.

I've used GDT for some time now and have not tun into such memory problems when performing refactorings, so I can't say what might be different about your project in general.  If you would be willing to share the project, that may help the investigation.
