### ISSUE TITLE
NPE in TraitHelper.isTrait

### ISSUE THREAD

**Issue by mpiggott** [groovy/groovy-eclipse#619]
Using Eclipse Photon and Groovy *3.0.0.xx-201806290029-e48* building [sonatype/nexus-public](https://github.com/sonatype/nexus-public)

```
java.lang.NullPointerException
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyClassScope$TraitHelper.isTrait(GroovyClassScope.java:528)
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyClassScope$TraitHelper.access$1(GroovyClassScope.java:518)
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyClassScope.augmentMethodBindings(GroovyClassScope.java:77)
	at org.eclipse.jdt.internal.compiler.lookup.ClassScope.buildMethods(ClassScope.java:387)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.initializeForStaticImports(SourceTypeBinding.java:1403)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.findField(Scope.java:1397)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.findField(Scope.java:1344)
	at org.eclipse.jdt.internal.compiler.lookup.MethodScope.findField(MethodScope.java:443)
	at org.eclipse.jdt.internal.compiler.lookup.BlockScope.getBinding(BlockScope.java:554)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedNameReference.resolveType(QualifiedNameReference.java:1015)
	at org.eclipse.jdt.internal.compiler.ast.MemberValuePair.resolveTypeExpecting(MemberValuePair.java:139)
	at org.eclipse.jdt.internal.compiler.ast.Annotation.resolveType(Annotation.java:924)
	at org.eclipse.jdt.internal.compiler.ast.ASTNode.resolveAnnotations(ASTNode.java:865)
	at org.eclipse.jdt.internal.compiler.ast.ASTNode.resolveAnnotations(ASTNode.java:724)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.getAnnotationTagBits(SourceTypeBinding.java:1031)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.retrieveAnnotationHolder(SourceTypeBinding.java:2266)
	at org.eclipse.jdt.internal.compiler.lookup.ReferenceBinding.retrieveAnnotations(ReferenceBinding.java:1742)
	at org.eclipse.jdt.internal.compiler.lookup.ReferenceBinding.getAnnotations(ReferenceBinding.java:1007)
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyClassScope$TraitHelper.isTrait(GroovyClassScope.java:525)
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyClassScope$TraitHelper.access$1(GroovyClassScope.java:518)
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyClassScope.augmentMethodBindings(GroovyClassScope.java:77)
	at org.eclipse.jdt.internal.compiler.lookup.ClassScope.buildMethods(ClassScope.java:387)
	at org.eclipse.jdt.internal.compiler.lookup.ClassScope.buildFieldsAndMethods(ClassScope.java:187)
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyClassScope.buildFieldsAndMethods(GroovyClassScope.java:421)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.buildFieldsAndMethods(CompilationUnitScope.java:98)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:517)
	at org.eclipse.jdt.internal.compiler.Compiler.internalBeginToCompile(Compiler.java:877)
	at org.eclipse.jdt.internal.compiler.Compiler.beginToCompile(Compiler.java:401)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:451)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:433)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:407)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:215)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:339)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:77)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:259)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:182)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:795)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:216)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:259)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:312)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:315)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:367)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:388)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```

**Comment by eric-milles** [comment]
Do you have a small sample project that can be used to recreate?

**Comment by mpiggott** [comment]
> Do you have a small sample project that can be used to recreate?

Nothing small just the project I linked I'm afraid, after updating Eclipse/groovy lately this started happening so I'm not sure what part of the codebase triggers it.

**Comment by eric-milles** [comment]
I think there is an annotation type that cannot be resolved.  Do you have any interfaces or @interfaces that have annotations?  Are any of the annotations not on the project classpath?

This was the recent change:
```
diff --git a/base/org.eclipse.jdt.groovy.core/src/org/codehaus/jdt/groovy/internal/compiler/ast/GroovyClassScope.java b/base/org.eclipse.jdt.groovy.core/src/org/codehaus/jdt/groovy/internal/compiler/ast/GroovyClassScope.java
index 044b2b6..972c979 100644
--- a/base/org.eclipse.jdt.groovy.core/src/org/codehaus/jdt/groovy/internal/compiler/ast/GroovyClassScope.java
+++ b/base/org.eclipse.jdt.groovy.core/src/org/codehaus/jdt/groovy/internal/compiler/ast/GroovyClassScope.java
@@ -74,7 +74,7 @@
     protected MethodBinding[] augmentMethodBindings(MethodBinding[] methodBindings) {
         // don't add these methods to annotations
         SourceTypeBinding binding = referenceContext.binding;
-        if (binding != null && (binding.isAnnotationType() || binding.isInterface())) {
+        if (binding != null && (binding.isAnnotationType() || binding.isInterface()) && !traitHelper.isTrait(binding)) {
             return methodBindings;
         }
```

**Comment by eric-milles** [comment]
Okay, I imported nexus-public (quite massive) and here is what I found:
```groovy
public @Path(ScriptClient.RESOURCE_URI) @Produces({APPLICATION_JSON}) @Consumes({APPLICATION_JSON}) interface ScriptClient {
```

This source type is parsing with 3 null annotation bindings.  These cause the NPE.  I'll try and backtrack to see if I can create a small unit test.

**Comment by eric-milles** [comment]
I am able to recreate with just this:
```groovy
@SuppressWarnings(Issue619.VALUE)
interface Issue619 {
  String VALUE = 'unchecked'
}
```

**Comment by mpiggott** [comment]
The latest version appears to have entirely fixed the issue for me.
