### ISSUE TITLE
Compiler errors with OpenJDK 9/10

### ISSUE THREAD

**Issue by etatara** [groovy/groovy-eclipse#631]
I get compile errors on a very simple Groovy project When using OpenJDK 9 or 10 with Eclipse 4.8 and groovy-eclipse 3.0.0.xx-201807091850-e48.  The project compiles fine when using JRE 8.  The Eclipse error log is filled with a large number of NPEs all leading back to

` org.codehaus.jdt.groovy.internal.compiler.ast.GroovyClassScope.buildFieldsAndMethods(GroovyClassScope.java:430)
`

```
java.lang.NullPointerException
	at org.eclipse.jdt.internal.compiler.lookup.Scope.findDirectMemberType(Scope.java:1266)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3327)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:3009)
	at org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.getTypeBinding(SingleTypeReference.java:54)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:512)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:618)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:614)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesWithSuspendedTempErrorHandlingPolicy(SourceTypeBinding.java:1991)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesFor(SourceTypeBinding.java:1874)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.methods(SourceTypeBinding.java:1562)
	at org.codehaus.jdt.groovy.internal.compiler.ast.GroovyClassScope.buildFieldsAndMethods(GroovyClassScope.java:430)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.buildFieldsAndMethods(CompilationUnitScope.java:98)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:517)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:546)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.accept(CompilationUnitProblemFinder.java:134)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:331)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:259)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3300)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:3009)
	at org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.getTypeBinding(SingleTypeReference.java:54)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:512)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:618)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:614)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesWithSuspendedTempErrorHandlingPolicy(SourceTypeBinding.java:1991)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesFor(SourceTypeBinding.java:1874)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.methods(SourceTypeBinding.java:1562)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.internalFaultInTypeForFieldsAndMethods(SourceTypeBinding.java:910)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.faultInTypesForFieldsAndMethods(SourceTypeBinding.java:905)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:583)
	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1061)
	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1113)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:295)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:364)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:190)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:91)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:733)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:799)
	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1333)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:128)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.access$0(JavaReconcilingStrategy.java:110)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:90)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:87)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.initialReconcile(JavaReconcilingStrategy.java:185)
	at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.initialReconcile(CompositeReconcilingStrategy.java:119)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.initialReconcile(JavaCompositeReconcilingStrategy.java:136)
	at org.eclipse.jface.text.reconciler.MonoReconciler.initialProcess(MonoReconciler.java:95)
	at org.eclipse.jdt.internal.ui.text.JavaReconciler.initialProcess(JavaReconciler.java:420)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:174)

```

```
eclipse.buildId=4.8.0.I20180611-0500
java.version=9
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.committers.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.committers.product
```

**Comment by eric-milles** [comment]
Could you share the project?  I have done light testing against Java 9 and 10.

**Comment by eric-milles** [comment]
This originally came in as #616.  From what I can gather, you have a * import (like `import java.lang.Thread.*`) that is not found.  This results in a null type binding for the import.  And eventually can NPE within JDT's `Scope.findDirectMemberType`.

Can you search your code for something like that?  I put breakpoints where the imports are resolved and haven't hit them in a week of testing.  Also, can you be sure you are running Eclipse with the highest JDK/JRE you plan on targeting?

**Comment by etatara** [comment]
[GroovyTest.zip](https://github.com/groovy/groovy-eclipse/files/2185064/GroovyTest.zip)

My simple project is attached.  It looks like it's related to imports as you suggest.  In MyGroovySet.groovy I originally did not explicitely import java.util.Collection, which compiles fine with Java 8 but not with Java 9/10.  If I include the import, it compiles with Java 9.  Is this a designed change in the groovy-eclipse compiler, or will the automatic imports eventually work as before?

**Comment by etatara** [comment]
As a followup I'd also ask what is the workaround for including non-static * imports?

**Comment by eric-milles** [comment]
It should work as with Java 8. I just need to be able to recreate to understand how it got into Scope without being able to resolve. I think the JDT assumption is that the imports have a non-null `resolvedType`

**Comment by eric-milles** [comment]
Your project is very similar to the test projects I have tried.  I cannot see the same error...

Does your project look like this?  Or do you see some difference?
![untitled](https://user-images.githubusercontent.com/18193802/42601444-4640c21c-852b-11e8-88ce-85de3db7102a.png)

**Comment by eric-milles** [comment]
Okay, when I changed compliance to 9 in Window > Preferences > Java > Compiler the error is reproduced.  If I set it to 1.8 there is no error.  So, you could try that as a short-term fix.

**Comment by etatara** [comment]
The project structure appears the same, aside from the build error on Utility.java.

![image](https://user-images.githubusercontent.com/11462868/42601977-273f3324-852d-11e8-90fd-86efbe5319b2.png)

**Comment by etatara** [comment]
Thanks the help.  The compiler level change to 1.8 fixes the error.  I'm still working through how the installed JDK and compiler level will translate to working with newer Java releases, but at least for now my projects will build.

**Comment by eric-milles** [comment]
Issue 616 can be followed or supplemented with additional info.  I will try to understand the cause of the NPE today.
