### ISSUE TITLE
Groovy eclipse batch compiler Java 9 Intellji

### ISSUE THREAD

**Issue by kkuo** [groovy/groovy-eclipse#694]
We have a spring-boot 1.5 project with java 8 and the following groovy-eclipse settings in our pom:

            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                
                <version>3.6.1</version>
                <configuration>
                    <compilerId>groovy-eclipse-compiler</compilerId>
                    <compilerArgument>${maven.compiler.source}</compilerArgument>
                    <compilerArgs>
                        <arg>-J--add-modules</arg>  // add java.xml module!
                        <arg>-Jjava.xml</arg>
                    </compilerArgs>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-eclipse-compiler</artifactId>
                        <version>2.9.2-01</version>
                    </dependency>
                    
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-eclipse-batch</artifactId>
                        <version>2.4.3-01</version>
                    </dependency>
                </dependencies>
            </plugin>

        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.4.12</version>
        </dependency>

We're trying to move to java 9 but the compiler we are using above does not support it. For now I have downloaded groovy-compiler-batch 2.4.15-01 and pointed Intellij to it. When I ask intellij to run a unit test I get the following:

```
Error:Groovy-Eclipse: Error: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jetbrains.jps.incremental.groovy.GreclipseBuilder.performCompilation(GreclipseBuilder.java:237)
	at org.jetbrains.jps.incremental.groovy.GreclipseBuilder.build(GreclipseBuilder.java:181)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1314)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:991)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1063)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:954)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:787)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:376)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:183)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:308)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:137)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:235)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/processing/RoundEnvironment
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:292)
	at org.eclipse.jdt.internal.compiler.batch.Main.initializeAnnotationProcessorManager(Main.java:4595)
	at org.eclipse.jdt.internal.compiler.batch.Main.performCompilation(Main.java:4713)
	at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1775)
	... 23 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.processing.RoundEnvironment
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 28 more
```

If I try to use groovy-eclipse-batch 2.5.2 I just get "Compiler error" and no other message.

I'm not exactly sure if there is a guide on how to migrate to Java 9.

I also passed in "-J--add-modules -Jjava.xml" in the field "Additional command line parameters" And it hasn't helped.

Really stuck and hoping that we can find a solution. Thanks.

**Comment by eric-milles** [comment]
If you are running in a Java 9+ JVM, you may need to add the APT annotations module (aka "java.compiler").

**Comment by kkuo** [comment]
Here is the call stack:

Error:Groovy-Eclipse: Error: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jetbrains.jps.incremental.groovy.GreclipseBuilder.performCompilation(GreclipseBuilder.java:237)
	at org.jetbrains.jps.incremental.groovy.GreclipseBuilder.build(GreclipseBuilder.java:181)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1314)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:991)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1063)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:954)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:787)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:376)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:183)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:308)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:137)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:235)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/processing/RoundEnvironment
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:292)
	at org.eclipse.jdt.internal.compiler.batch.Main.initializeAnnotationProcessorManager(Main.java:4599)
	at org.eclipse.jdt.internal.compiler.batch.Main.performCompilation(Main.java:4717)
	at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1780)
	... 23 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.processing.RoundEnvironment
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 28 more

**Comment by eric-milles** [comment]
The module you need to add is "java.compiler", not "java.xml".  I don't know how IntelliJ invokes the batch compiler.  If it creates a new process, surely there is a way to pass arguments to the VM.  You'll need to check with JetBrains on that.

**Comment by kkuo** [comment]
@eric-milles Is there documentation on what command line arguments the batch compiler takes?

**Comment by eric-milles** [comment]
The batch compiler extends the JDT compiler.  It's command line options are listed here: https://help.eclipse.org/photon/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_batch_compiler.htm

The GDT version adds configscript and indy options.  See: https://github.com/groovy/groovy-eclipse/blob/master/jdt-patch/e48/org.eclipse.jdt.core/batch/org/eclipse/jdt/internal/compiler/batch/Main.java#L2081
