### ISSUE TITLE
SecurityException in code completion

### ISSUE THREAD

**Issue by DarioArena87** [groovy/groovy-eclipse#702]
Hi, i was writing a test for an Hibernate Entity and i really havent understood why when i try to create one initializing some fields with the "named parameter constructor" when i trigger code completion on some field i get this exception.

The code that triggers this exception is this:

>        final Fgpstorend fgpstorend = new Fgpstorend(
>                id: new FgpstorendId(sredata: 20171229),
>                sreval1mov: 20171127,
>                sreggann: 32,
>                sreggsem: 32,
>                sreggtri: 32,
>                sreggmes: 29,
>                srepatdat: 49990.45,
>                srepatann: 0,
>                srepreann: 0,
>                sreconann: 50000.00,
>                srecinann: -7.84,
>                srecbaann: 0,
>                srepfiann: -0.99,
>                srecgeann: 0,
>                sreritann: 0
>        ).

(Fgpstorend is the entity). 
When i try to add some other field i get this exception:

eclipse.buildId=4.7.3.M20180330-0640
java.version=10
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=it_IT
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -data file:/C:/Dev2016/source/WorkspaceEFFE2Work/ -product org.eclipse.epp.package.jee.product

org.eclipse.jdt.groovy.core
Error
Mon Sep 03 16:10:56 CEST 2018
Groovy-Eclipse Type Inferencing: Error visiting method test createRendPortTipoPeriodo in class FgpstorendTest
```
java.lang.SecurityException: Prohibited package name: java.sql
	at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:891)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1007)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:545)
	at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:83)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:453)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:446)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:890)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3119)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2268)
	at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:401)
	at org.codehaus.groovy.ast.ClassNode.lazyClassInit(ClassNode.java:358)
	at org.codehaus.groovy.ast.ClassNode.getDeclaredMethods(ClassNode.java:970)
	at org.codehaus.groovy.ast.ClassNode.getMethods(ClassNode.java:985)
	at org.eclipse.jdt.groovy.search.CategoryTypeLookup.lookupType(CategoryTypeLookup.java:56)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.lookupExpressionType(TypeInferencingVisitorWithRequestor.java:2368)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitMapExpression(TypeInferencingVisitorWithRequestor.java:1318)
	at org.codehaus.groovy.ast.expr.MapExpression.visit(MapExpression.java:55)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitListOfExpressions(CodeVisitorSupport.java:327)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitTupleExpression(CodeVisitorSupport.java:231)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitTupleExpression(TypeInferencingVisitorWithRequestor.java:1670)
	at org.codehaus.groovy.ast.expr.TupleExpression.visit(TupleExpression.java:82)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitConstructorCallExpression(CodeVisitorSupport.java:192)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitConstructorCallExpression(TypeInferencingVisitorWithRequestor.java:988)
	at org.codehaus.groovy.ast.expr.ConstructorCallExpression.visit(ConstructorCallExpression.java:46)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitBinaryExpression(TypeInferencingVisitorWithRequestor.java:746)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitDeclarationExpression(CodeVisitorSupport.java:298)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitDeclarationExpression(ClassCodeVisitorSupport.java:150)
	at org.codehaus.groovy.ast.expr.DeclarationExpression.visit(DeclarationExpression.java:89)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:122)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitExpressionStatement(ClassCodeVisitorSupport.java:266)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:42)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:88)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:236)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitBlockStatement(TypeInferencingVisitorWithRequestor.java:818)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:71)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:145)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitConstructorOrMethod(TypeInferencingVisitorWithRequestor.java:1053)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitMethodInternal(TypeInferencingVisitorWithRequestor.java:617)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitJDT(TypeInferencingVisitorWithRequestor.java:458)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitJDT(TypeInferencingVisitorWithRequestor.java:349)
	at org.eclipse.jdt.groovy.search.TypeInferencingVisitorWithRequestor.visitCompilationUnit(TypeInferencingVisitorWithRequestor.java:255)
	at org.codehaus.groovy.eclipse.editor.highlighting.GatherSemanticReferences.findSemanticHighlightingReferences(GatherSemanticReferences.java:45)
	at org.codehaus.groovy.eclipse.editor.highlighting.GroovySemanticReconciler.reconciled(GroovySemanticReconciler.java:236)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor.reconciled(CompilationUnitEditor.java:1688)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconciled(JavaReconcilingStrategy.java:219)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconciled(JavaCompositeReconcilingStrategy.java:164)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.initialReconcile(JavaCompositeReconcilingStrategy.java:144)
	at org.eclipse.jface.text.reconciler.MonoReconciler.initialProcess(MonoReconciler.java:95)
	at org.eclipse.jdt.internal.ui.text.JavaReconciler.initialProcess(JavaReconciler.java:420)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:174)
```
Is it maybe because i'm using java 10 to run eclipse? Is it possible to fix it?

**Comment by DarioArena87** [comment]
I tried using java 8 (1.8.161) and the exception is not thrown but no code completion suggestion is shown in the tooltip.

**Comment by eric-milles** [comment]
Is the project that contains this source a Java 9+ module?  What is happening is Groovy-Eclipse is reading the registered extension classes (aka Groovy Category classes; aka DGM types), one of which is `DateGroovyMethods`.  This type makes reference to `java.sql.Timestamp` and your classloader has been configured to reject access to this package.

You may be able to disable this warning by adding `--add-modules=java.sql` or `--add-modules=ALL-SYSTEM` to your `eclipse.ini` file (after the `-vmargs` line).

**Comment by eric-milles** [comment]
If your project is built using JDK 1.6, I would strongly recommend using JDK 1.8 for running eclipse.  Java 9+ support is still finding its feet.  Modulepath support is indeed the big missing piece.

**Comment by padamson-r7** [comment]
If your eclipse is running on a different version of java than the one on the project build path, then groovy will be prevented from accessing java.* classes from the build path java because they were not loaded as part of the running JVM.

**Comment by eric-milles** [comment]
@padamson-r7 Do you have any more details?  Can you open a new issue instead of commenting on 2 closed issues?
