### ISSUE TITLE
Serious issue with one Groovy class

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#715]
I have a serious issue with the latest Greclipse snapshot, I don' know exactly when it was introduced, but it surely happens with 3.1.0.xx-201809101914-e48.

I have a Groovy class that apparently compiles, but for this class sometimes the following error is given (I can't remember exactly after doing what, probably the first time I try to open it through the Project Explorer):

```noformat
The following will be send to: Eclipse


REPORT

eclipseBuildId      4.8.0.I20180611-0500
eclipseProduct      org.eclipse.platform.ide
javaRuntimeVersion  1.8.0_181-b13
osgiWs              win32
osgiOs              Windows10
osgiOsVersion       10.0.0
osgiArch            x86_64
severity            UNKNOWN


STATUS

pluginId            org.eclipse.jdt.core
pluginVersion       3.14.0.xx-201809101914-e48
code                4
severity            4
message             Problem with build structure for GenericServicePurchaseBean.groovy
fingerprint         06f4f97c34b7038a0386427a018cfa0d

Exception:java.lang.NullPointerException: null
	 at java.lang.System.arraycopy(null:-2)
	 at org.eclipse.jdt.internal.core.CompilationUnitStructureRequestor.exitField(CompilationUnitStructureRequestor.java:703)
	 at org.eclipse.jdt.internal.compiler.SourceElementNotifier.notifySourceElementRequestor(SourceElementNotifier.java:543)
	 at org.eclipse.jdt.internal.compiler.SourceElementNotifier.notifySourceElementRequestor(SourceElementNotifier.java:733)
	 at org.eclipse.jdt.internal.compiler.SourceElementNotifier$LocalDeclarationVisitor.visit(SourceElementNotifier.java:81)
	 at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1417)
	 at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.traverse(QualifiedAllocationExpression.java:686)
	 at org.eclipse.jdt.internal.compiler.SourceElementNotifier.visitIfNeeded(SourceElementNotifier.java:888)
	 at org.eclipse.jdt.internal.compiler.SourceElementNotifier.notifySourceElementRequestor(SourceElementNotifier.java:541)
	 at org.eclipse.jdt.internal.compiler.SourceElementNotifier.notifySourceElementRequestor(SourceElementNotifier.java:733)
	 at org.eclipse.jdt.internal.compiler.SourceElementNotifier.notifySourceElementRequestor(SourceElementNotifier.java:469)
	 at org.codehaus.jdt.groovy.integration.internal.MultiplexingSourceElementRequestorParser.parseCompilationUnit(MultiplexingSourceElementRequestorParser.java:119)
	 at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:286)
	 at org.codehaus.jdt.groovy.model.GroovyCompilationUnit.buildStructure(GroovyCompilationUnit.java:312)
	 at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:265)
	 at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:599)
	 at org.eclipse.jdt.internal.core.BecomeWorkingCopyOperation.executeOperation(BecomeWorkingCopyOperation.java:40)
	 at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:733)
	 at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:799)
	 at org.eclipse.jdt.internal.core.CompilationUnit.becomeWorkingCopy(CompilationUnit.java:98)
	 at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitDocumentProvider.createFileInfo(CompilationUnitDocumentProvider.java:1031)
	 at org.eclipse.ui.editors.text.TextFileDocumentProvider.connect(TextFileDocumentProvider.java:478)
	 at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitDocumentProvider.connect(CompilationUnitDocumentProvider.java:1274)
	 at org.eclipse.ui.texteditor.AbstractTextEditor.doSetInput(AbstractTextEditor.java:4203)
	 at org.eclipse.ui.texteditor.StatusTextEditor.doSetInput(StatusTextEditor.java:257)
	 at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.doSetInput(AbstractDecoratedTextEditor.java:1473)
	 at org.eclipse.jdt.internal.ui.javaeditor.JavaEditor.internalDoSetInput(JavaEditor.java:2570)
	 at org.eclipse.jdt.internal.ui.javaeditor.JavaEditor.doSetInput(JavaEditor.java:2543)
	 at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor.doSetInput(CompilationUnitEditor.java:1420)
	 at org.codehaus.groovy.eclipse.editor.GroovyEditor.doSetInput(GroovyEditor.java:824)
	 at org.eclipse.ui.texteditor.AbstractTextEditor$5.run(AbstractTextEditor.java:3165)
	 at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:437)
	 at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:353)
	 at org.eclipse.ui.internal.WorkbenchWindow$14.run(WorkbenchWindow.java:2212)
	 at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:71)
	 at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2208)
	 at org.eclipse.ui.texteditor.AbstractTextEditor.internalInit(AbstractTextEditor.java:3183)
	 at org.eclipse.ui.texteditor.AbstractTextEditor.init(AbstractTextEditor.java:3208)
	 at org.eclipse.ui.internal.EditorReference.initialize(EditorReference.java:362)
	 at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:342)
	 at sun.reflect.GeneratedMethodAccessor90.invoke(null:-1)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(null:-1)
	 at java.lang.reflect.Method.invoke(null:-1)
	 at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	 at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:1005)
	 at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:970)
	 at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:137)
	 at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:412)
	 at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:331)
	 at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:190)
	 at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:105)
	 at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:74)
	 at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:56)
	 at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:129)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:1012)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:672)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:778)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:749)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:743)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:727)
	 at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.showTab(StackRenderer.java:1277)
	 at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.lambda$0(LazyStackRenderer.java:72)
	 at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
	 at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:233)
	 at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:144)
	 at org.eclipse.swt.widgets.Display.syncExec(Display.java:4567)
	 at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:212)
	 at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
	 at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:201)
	 at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:196)
	 at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	 at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	 at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	 at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	 at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	 at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	 at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:52)
	 at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:60)
	 at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	 at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:174)
	 at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:634)
	 at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:598)
	 at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:788)
	 at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:401)
	 at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1238)
	 at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3277)
	 at org.eclipse.ui.internal.WorkbenchPage.access$26(WorkbenchPage.java:3192)
	 at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:3174)
	 at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:71)
	 at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3169)
	 at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3133)
	 at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3123)
	 at org.eclipse.jdt.internal.ui.javaeditor.EditorUtility.openInEditor(EditorUtility.java:373)
	 at org.eclipse.jdt.internal.ui.javaeditor.EditorUtility.openInEditor(EditorUtility.java:179)
	 at org.eclipse.jdt.ui.actions.OpenAction.run(OpenAction.java:284)
	 at org.eclipse.jdt.ui.actions.OpenAction.run(OpenAction.java:249)
	 at org.eclipse.jdt.ui.actions.SelectionDispatchAction.dispatchRun(SelectionDispatchAction.java:271)
	 at org.eclipse.jdt.ui.actions.SelectionDispatchAction.run(SelectionDispatchAction.java:249)
	 at org.eclipse.jdt.internal.ui.navigator.OpenAndExpand.run(OpenAndExpand.java:50)
	 at org.eclipse.ui.actions.RetargetAction.run(RetargetAction.java:216)
	 at org.eclipse.ui.navigator.CommonNavigatorManager$1.open(CommonNavigatorManager.java:180)
	 at org.eclipse.ui.OpenAndLinkWithEditorHelper$InternalListener.open(OpenAndLinkWithEditorHelper.java:46)
	 at org.eclipse.jface.viewers.StructuredViewer$2.run(StructuredViewer.java:850)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	 at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	 at org.eclipse.jface.viewers.StructuredViewer.fireOpen(StructuredViewer.java:847)
	 at org.eclipse.jface.viewers.StructuredViewer.handleOpen(StructuredViewer.java:1162)
	 at org.eclipse.ui.navigator.CommonViewer.handleOpen(CommonViewer.java:451)
	 at org.eclipse.jface.util.OpenStrategy.fireOpenEvent(OpenStrategy.java:273)
	 at org.eclipse.jface.util.OpenStrategy.access$2(OpenStrategy.java:268)
	 at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:308)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3931)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3534)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	 at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	 at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	 at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	 at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	 at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	 at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(null:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(null:-1)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(null:-1)
	 at java.lang.reflect.Method.invoke(null:-1)
	 at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	 at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	 at org.eclipse.equinox.launcher.Main.run(Main.java:1498)


BUNDLES

name                org.codehaus.groovy.eclipse
version             3.1.0.xx-201809101914-e48

name                org.codehaus.groovy
version             2.4.15.xx-201809101914-e48

name                org.eclipse.core.databinding.observable
version             1.6.200.v20180424-1922

name                org.eclipse.core.databinding
version             1.6.200.v20180509-1517

name                org.eclipse.core.runtime
version             3.14.0.v20180417-0825

name                org.eclipse.e4.core.contexts
version             1.7.0.v20180514-1409

name                org.eclipse.e4.core.di
version             1.7.0.v20180427-1454

name                org.eclipse.e4.ui.services
version             1.3.100.v20180403-0945

name                org.eclipse.e4.ui.workbench
version             1.6.0.v20180516-2019

name                org.eclipse.e4.ui.workbench.renderers.swt
version             0.14.200.v20180516-2019

name                org.eclipse.e4.ui.workbench.swt
version             0.14.200.v20180516-2019

name                org.eclipse.emf.common
version             2.14.0.v20180527-1134

name                org.eclipse.emf
version             2.7.0.v20180123-1048

name                org.eclipse.equinox.app
version             1.3.500.v20171221-2204

name                org.eclipse.equinox.event
version             1.4.200.v20180426-0845

name                org.eclipse.equinox.launcher
version             1.5.0.v20180512-1130

name                org.eclipse.jdt
version             3.14.0.v20180611-0500

name                org.eclipse.jdt.core
version             3.14.0.xx-201809101914-e48

name                org.eclipse.jdt.ui
version             3.14.0.v20180529-1023

name                org.eclipse.jface
version             3.14.0.v20180423-0714

name                org.eclipse.osgi
version             3.13.0.v20180409-1500

name                org.eclipse.swt
version             3.107.0.v20180611-0422

name                org.eclipse.ui
version             3.109.100.v20180426-0903

name                org.eclipse.ui.editors
version             3.11.100.v20180512-1137

name                org.eclipse.ui.ide.application
version             1.2.100.v20180416-2050

name                org.eclipse.ui.ide
version             3.14.0.v20180517-1842

name                org.eclipse.ui.navigator
version             3.7.100.v20180524-1240
```

Now, when I try to open that class (`GenericServicePurchaseBean`) with Ctrl+Shift+T, I get the following error:

![immagine](https://user-images.githubusercontent.com/1742494/45543331-9563c300-b814-11e8-9885-f6de1e0e22ee.png)

When I open it through the Project Explorer it seems like it's opening fine. However, if I look at another Groovy class that imports this one I get a red line on the import statement saying "unable to resolve class ...GenericServicePurchaseBean". By the way, this error is reported within the editor, but it is not floating on the file in the Project Explorer (but this is probably an unrelated problem).

This is a blocking problem, because I can't work with that Groovy class.

**Comment by eric-milles** [comment]
CompilationUnitStructureRequestor is trying to copy the source chars of a field initializer.  The offsets must be incorrectly set.  Can you send me the source file (via slack if you wish to keep private)?

**Comment by eric-milles** [comment]
Seems like this is enough to reproduce:
```groovy
class Issue715 {
  Face<String> face = new Face<String>() {
    private static final long serialVersionUID = 1L;

    @Override
    String run() {
    }
  }
}

interface Face<T> extends Serializable {
  T run()
}
```

**Comment by eric-milles** [comment]
Ready to test
