### ISSUE TITLE
Getting Started guide instructions lead to errors

### ISSUE THREAD

**Issue by basil** [groovy/groovy-eclipse#719]
I followed [the Getting Started guide](https://github.com/groovy/groovy-eclipse/blob/master/docs/Getting-Started-with-Groovy-Eclipse-Source-Code.md) to set up my development environment using the Eclipse Installer, hoping to contribute a change to this project.

After downloading the Eclipse Installer (version: 1.9.0 Build 3652), I selected "Eclipse IDE for Eclipse Committers" and "Groovy-Eclipse" as the instructions stated. Under "Target Platform" I selected "Eclipse Oxygen - 4.7" and followed the remaining instructions. After clicking "Finish" the installation failed with this error:

```
Executing bootstrap tasks
Java(TM) SE Runtime Environment 1.8.0_121-b13
Product org.eclipse.products.epp.package.committers.latest.released
Workspace /Users/basil/groovy-eclipse/Groovy-Eclipse-master11/ws
Project com.github.Groovy-Eclipse.master
Bundle org.eclipse.oomph.setup 1.10.0.v20180828-0705, build=3652, branch=fddd6edb5a235aea831fecf04547579693a78a4e
Bundle org.eclipse.oomph.setup.core 1.10.0.v20180714-0556, build=3652, branch=fddd6edb5a235aea831fecf04547579693a78a4e
Bundle org.eclipse.oomph.setup.installer 1.10.0.v20180722-1342, build=3652, branch=fddd6edb5a235aea831fecf04547579693a78a4e
Bundle org.eclipse.oomph.setup.p2 1.10.0.v20180706-1242, build=3652, branch=fddd6edb5a235aea831fecf04547579693a78a4e
Performing Workspace /Users/basil/groovy-eclipse/Groovy-Eclipse-master11/ws
Performing P2 Director (Eclipse IDE for Eclipse Committers (Photon))
Offline = false
Mirrors = true
Resolving 54 requirements from 7 repositories to /Users/basil/groovy-eclipse/Groovy-Eclipse-master11/Eclipse.app/Contents/Eclipse
Requirement org.codehaus.groovy.m2eclipse.feature.feature.group
Requirement org.eclipse.jdt.source.feature.group
Requirement org.eclipse.pde.source.feature.group
Requirement org.eclipse.platform.source.feature.group
Requirement org.eclipse.m2e.feature.feature.group
Requirement org.eclipse.oomph.setup.sdk.feature.group
Requirement org.eclipse.pde.api.tools.ee.feature.feature.group
Requirement com.ifedorenko.m2e.mavendev.feature.feature.group
Requirement net.sf.eclipsecs.feature.group (optional)
Requirement epp.package.committers [4.8.0,4.9.0)
Requirement org.eclipse.platform.feature.group [4.8.0,4.9.0)
Requirement org.eclipse.rcp.feature.group [4.8.0,4.9.0)
Requirement org.eclipse.buildship.feature.group
Requirement org.eclipse.cvs.feature.group
Requirement org.eclipse.e4.core.tools.feature.feature.group
Requirement org.eclipse.eclemma.feature.feature.group
Requirement org.eclipse.egit.feature.group
Requirement org.eclipse.egit.gitflow.feature.feature.group
Requirement org.eclipse.egit.mylyn.feature.group
Requirement org.eclipse.jdt.feature.group
Requirement org.eclipse.jgit.http.apache.feature.group
Requirement org.eclipse.mylyn.bugzilla_feature.feature.group
Requirement org.eclipse.mylyn.builds.feature.group
Requirement org.eclipse.mylyn.commons.feature.group
Requirement org.eclipse.mylyn.commons.identity.feature.group
Requirement org.eclipse.mylyn.commons.notifications.feature.group
Requirement org.eclipse.mylyn.commons.repositories.feature.group
Requirement org.eclipse.mylyn.commons.repositories.http.feature.group
Requirement org.eclipse.mylyn.discovery.feature.group
Requirement org.eclipse.mylyn.gerrit.dashboard.feature.feature.group
Requirement org.eclipse.mylyn.gerrit.feature.feature.group
Requirement org.eclipse.mylyn.git.feature.group
Requirement org.eclipse.mylyn.hudson.feature.group
Requirement org.eclipse.mylyn.monitor.feature.group
Requirement org.eclipse.mylyn.reviews.feature.feature.group
Requirement org.eclipse.mylyn.team_feature.feature.group
Requirement org.eclipse.mylyn.versions.feature.group
Requirement org.eclipse.mylyn.wikitext_feature.feature.group
Requirement org.eclipse.mylyn_feature.feature.group
Requirement org.eclipse.pde.feature.group
Requirement org.eclipse.rcp.source.feature.group
Requirement org.eclipse.recommenders.mylyn.rcp.feature.feature.group
Requirement org.eclipse.recommenders.news.rcp.feature.feature.group
Requirement org.eclipse.recommenders.rcp.feature.feature.group
Requirement org.eclipse.recommenders.snipmatch.rcp.feature.feature.group
Requirement org.eclipse.wst.json_ui.feature.feature.group
Requirement org.eclipse.wst.xml_ui.feature.feature.group
Requirement org.eclipse.oomph.setup.feature.group
Requirement org.eclipse.oomph.setup.jdt.feature.group
Requirement org.eclipse.oomph.setup.git.feature.group
Requirement org.eclipse.oomph.setup.projects.feature.group
Requirement org.eclipse.oomph.targlets.feature.group
Requirement org.eclipse.oomph.setup.targlets.feature.group
Requirement org.eclipse.oomph.setup.workingsets.feature.group
Repository http://dist.springsource.org/snapshot/GRECLIPSE/e4.7
Repository http://ifedorenko.github.com/m2e-extras
Repository https://checkstyle.github.io/eclipse-cs/update
Repository http://download.eclipse.org/technology/epp/packages/photon
Repository http://download.eclipse.org/releases/photon/201806271001
Repository http://download.eclipse.org/oomph/updates/milestone/latest
Repository http://download.eclipse.org/egit/updates
Adding repository http://download.eclipse.org/technology/epp/packages/photon
Adding repository http://download.eclipse.org/oomph/updates/milestone/latest
Adding repository http://dist.springsource.org/snapshot/GRECLIPSE/e4.7
Adding repository http://ifedorenko.github.com/m2e-extras
Adding repository http://download.eclipse.org/releases/photon/201806271001
Adding repository http://download.eclipse.org/egit/updates
Adding repository https://checkstyle.github.io/eclipse-cs/update
Calculating requirements and dependencies.
Cannot complete the request.  Generating details.
ERROR: org.eclipse.equinox.p2.director code=10054 Cannot complete the install because of a conflicting dependency.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:425)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:337)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:733)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3334)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3262)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3243)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3143)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:575)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:701)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1537205343656
  ERROR: org.eclipse.equinox.p2.director code=1 Only one of the following can be installed at once: 
    ERROR: org.eclipse.equinox.p2.director code=0 Java Development Tools Core 3.14.0.v20180528-0519 (org.eclipse.jdt.core 3.14.0.v20180528-0519)
    ERROR: org.eclipse.equinox.p2.director code=0 Java Development Tools Core 3.13.102.xx-201809160115-e47 (org.eclipse.jdt.core 3.13.102.xx-201809160115-e47)
    ERROR: org.eclipse.equinox.p2.director code=0 Object Teams Development Tooling Core 3.14.0.OTDT_r270_201806120901 (org.eclipse.jdt.core 3.14.0.OTDT_r270_201806120901)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1537205343656
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.m2eclipse.feature.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1537205343656
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Groovy-Eclipse Compilerless feature 3.1.0.xx-201809160115-e47 (org.codehaus.groovy.compilerless.feature.feature.group 3.1.0.xx-201809160115-e47)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.headless.feature.feature.group [3.1.0.xx-201809160115-e47,3.1.0.xx-201809160115-e47]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Groovy Development Tools 3.1.0.xx-201809160115-e47 (org.codehaus.groovy.eclipse.feature.feature.group 3.1.0.xx-201809160115-e47)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.compilerless.feature.feature.group [3.1.0.xx-201809160115-e47,3.1.0.xx-201809160115-e47]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Groovy-Eclipse Headless feature 3.1.0.xx-201809160115-e47 (org.codehaus.groovy.headless.feature.feature.group 3.1.0.xx-201809160115-e47)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.jdt.patch.feature.group [3.1.0.xx-201809160115-e47,3.1.0.xx-201809160115-e47]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Groovy-Eclipse M2E integration 3.1.0.xx-201809160115-e47 (org.codehaus.groovy.m2eclipse.feature.feature.group 3.1.0.xx-201809160115-e47)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.eclipse.feature.feature.group 3.1.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Java Annotation Processing UI 3.6.0.v20180417-0931 (org.eclipse.jdt.apt.ui 3.6.0.v20180417-0931)
    ERROR: org.eclipse.equinox.p2.director code=0 To: osgi.bundle; org.eclipse.jdt.core [3.14.0,4.0.0)
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Java Development Tools 3.14.0.v20180611-0500 (org.eclipse.jdt.feature.group 3.14.0.v20180611-0500)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.apt.ui [3.6.0.v20180417-0931,3.6.0.v20180417-0931]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From Patch: org.codehaus.groovy.jdt.patch.feature.group 3.1.0.xx-201809160115-e47 Eclipse Java Development Tools 3.14.0.v20180611-0500 (org.eclipse.jdt.feature.group 3.14.0.v20180611-0500)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.jdt.core [3.13.102.xx-201809160115-e47,3.13.102.xx-201809160115-e47]

Took 4 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.
```

I got similar errors after trying other combinations of choices in the installer, such as "Eclipse IDE for Java Developers" as the product and "Eclipse Photon - 4.8", "Eclipse Oxygen - 4.7", and "Eclipse Neon - 4.6" as the Target Platform.

I don't really know how to proceed in debugging this issue. Do you have any suggestions on where to start?

**Comment by eric-milles** [comment]
In you error message, it states it is loading the Eclipse Photon update site: "Performing P2 Director (Eclipse IDE for Eclipse Committers (Photon))".  This is in conflict with Eclipse Oxygen for Groovy-Eclipse.

Is your goal to do Groovy development in general, or development of the Groovy-Eclipse tooling?

**Comment by basil** [comment]
My goal is to work on an improvement to the Groovy formatter [here](https://github.com/groovy/groovy-eclipse/blob/master/ide/org.codehaus.groovy.eclipse.refactoring/src/org/codehaus/groovy/eclipse/refactoring/formatter/DefaultGroovyFormatter.java) and to be able to run the tests [here](https://github.com/groovy/groovy-eclipse/blob/master/ide-test/org.codehaus.groovy.eclipse.refactoring.test/src/org/codehaus/groovy/eclipse/refactoring/test/formatter/GroovyFormatterTests.groovy).

**Comment by eric-milles** [comment]
Were you able to get set up using Oxygen for both Eclipse and Groovy-Eclipse?  Or Photon for both?

**Comment by basil** [comment]
Thanks for following up. I was eventually able to get set up by going through the instructions again and selecting "Photon" as the product version in the **Product** page of the installer. Using "Latest Release (Photon)" as suggested in [the Getting Started guide](https://github.com/groovy/groovy-eclipse/blob/master/docs/Getting-Started-with-Groovy-Eclipse-Source-Code.md) led to dependency errors later, for inscrutable reasons.

**Comment by basil** [comment]
I've now successfully run `GroovyFormatterTests`. Thanks for your help!
