### ISSUE TITLE
Groovy compiler error: exception in phase 'class generation' in source unit

### ISSUE THREAD

**Issue by boris-petrov** [groovy/groovy-eclipse#771]
I've been using groovy-eclipse fine. Today I updated the Groovy compiler from 2.4.x to 2.5.4 and I started getting this error. It doesn't happen when I build my project with Gradle (which also has 2.5.4). I'm using Eclipse Version: 2018-09 (4.9.0) and the snapshot build of groovy-eclipse. Any ideas?

**Comment by eric-milles** [comment]
@boris-petrov You'll need to provide more information to understand this error.  Is it possible to provide the project that you are trying to compile?  Can you reduce the project to a minimal number of files that still exhibit the problem?

**Comment by boris-petrov** [comment]
Just a quick note - I think this has something to do with `org.spockframework:spock-core:1.2-groovy-2.5`. When using `org.spockframework:spock-core:1.2-groovy-2.4` and Groovy 2.4.x it works fine.

**Comment by boris-petrov** [comment]
I cannot seem to do anything meaningful. I try removing a bunch of stuff, modifying things, this error doesn't go away. It changes between files, but is always there even if I remove half our code. There's also another very strange error: `Groovy:The method public volatile java.lang.Object next()  { ... } duplicates another method of the same signature`
Also no idea where this comes from and why... only happens on 2.5. Not sure how to proceed from here...?

**Comment by eric-milles** [comment]
Can you reduce the project to something shareable that exhibits the error or an error?  When compiling the whole project, often the first source unit receives the error for the entire compilation batch.  This is likely why you are seeing the error move around when you delete stuff.

Have you tried opening the Groovy Event Console, cleaning and rebuilding?  There may be more information in there is terms of a compilation problem.

**Comment by boris-petrov** [comment]
So when I remove *all* of our Spock tests, the project compiles fine. When I just have one empty Spock test like:

```groovy
package somepackage

import spock.lang.Specification

class SomeSpec extends Specification {
}
```

Then I get that error. This is with `org.spockframework:spock-core:1.2-groovy-2.5` as I said. I think that should be enough for reproduction. Please tell me if I can do something more.

**Comment by eric-milles** [comment]
I'm not having any problem compiling with spock-core-1.2-groovy-2.5.  Can you send a small project that demonstrates the error?  I can't tell what other settings and dependencies you have that may be part of the problem.

**Comment by boris-petrov** [comment]
OK, [here you go](https://github.com/boris-petrov/groovy-2.5-compiler-error). Checkout the repo, run `gradle eclipse`, open the project in Eclipse. Clean/rebuild the project - you'll see the error. Be sure to be using the 2.5 compiler. It took me quite a while to do this, you owe me a beer! :)

**Comment by eric-milles** [comment]
@boris-petrov Is this the error you are seeing?
```
BUG! exception in phase 'class generation' in source unit 'C:\Users\U0076777\pde-workspaceg\eclipse-space\backend1\src\seed\groovy\foobar\Util.groovy' foobar.BaseObjectCodecProvider
	at org.codehaus.groovy.control.CompilationUnit$20.getClassNode(CompilationUnit.java:916)
	...
Caused by: java.lang.ClassNotFoundException: foobar.BaseObjectCodecProvider
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:762)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:637)
	at org.codehaus.groovy.control.CompilationUnit$20.getClassNode(CompilationUnit.java:913)
	... 22 more
```
