### ISSUE TITLE
Fix type inferencing and syntax highlighting for anon. inner in with block

### ISSUE THREAD

**Issue by eric-milles** [groovy/groovy-eclipse#927]
Consider the following:
```groovy
void meth() {
  org.xml.sax.helpers.XMLReaderFactory.createXMLReader().with {
    contentHandler = new org.xml.sax.helpers.DefaultHandler() {
      private Stack<StringBuilder> chars = []

      @Override
      void characters(char[] text, int offset, int length)
      {
        if (chars) chars.peek().append(text, offset, length)
      }
    }
  }
}
```

The variable expressions "chars" within the "characters" method are showing as unknown (underlined).

**Comment by eric-milles** [comment]
Looks like the anon. inner class does not have access to the enclosing closure's variable resolution.

```groovy
class Foo {
  String string = 'foo'
}
new Foo().with {
  def bar = new Object() {
    String toString() { string }
  }
  println bar
}
```

```
groovy.lang.MissingPropertyException: No such property: string for class: Script1
	at Script1$1.toString(Script1.groovy:8)
	at Script1$_run_closure1.doCall(Script1.groovy:10)
	at Script1.run(Script1.groovy:5)
```
