### ISSUE TITLE
Exception in phase 'semantic analysis' in source unit 'builder_transform.dsld' zip file closed during DSLD scripts refresh

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#940]
After recently upgrading to Eclipse 4.12 and Greclipse 3.5.0 snapshot, I got the following exception a couple of times at startup:

```
eclipse.buildId=4.12.0.I20190605-1800
java.version=1.8.0_221
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=it_IT
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/D:/ws/rolling/DCS-SHOP-trunk/

org.eclipse.core.jobs
Error
Mon Aug 12 09:26:39 CEST 2019
An internal error occurred during: "Refresh DSLD scripts".

BUG! exception in phase 'semantic analysis' in source unit 'builder_transform.dsld' zip file closed
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:967)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:636)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:586)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:401)
	at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:89)
	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:341)
	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:338)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:147)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:336)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:320)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:262)
	at org.codehaus.groovy.eclipse.dsl.script.DSLDScriptExecutor.executeScript(DSLDScriptExecutor.java:78)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob.refreshProject(RefreshDSLDJob.java:193)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob.run(RefreshDSLDJob.java:118)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(Unknown Source)
	at java.util.zip.ZipFile.access$200(Unknown Source)
	at java.util.zip.ZipFile$ZipEntryIterator.hasNext(Unknown Source)
	at java.util.zip.ZipFile$ZipEntryIterator.hasMoreElements(Unknown Source)
	at java.util.jar.JarFile$JarEntryIterator.hasNext(Unknown Source)
	at java.util.jar.JarFile$JarEntryIterator.hasMoreElements(Unknown Source)
	at sun.misc.URLClassPath$JarLoader.validIndex(Unknown Source)
	at sun.misc.URLClassPath$JarLoader.getResource(Unknown Source)
	at sun.misc.URLClassPath$JarLoader.getResource(Unknown Source)
	at sun.misc.URLClassPath$JarLoader.findResource(Unknown Source)
	at sun.misc.URLClassPath.findResource(Unknown Source)
	at java.net.URLClassLoader$2.run(Unknown Source)
	at java.net.URLClassLoader$2.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findResource(Unknown Source)
	at java.lang.ClassLoader.getResource(Unknown Source)
	at java.lang.ClassLoader.getResource(Unknown Source)
	at org.apache.xbean.classloader.MultiParentClassLoader.getResource(MultiParentClassLoader.java:252)
	at java.lang.ClassLoader.getResource(Unknown Source)
	at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:248)
	at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
	at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
	at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
	at org.codehaus.groovy.control.ResolveVisitor.resolveToOuter(ResolveVisitor.java:971)
	at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:499)
	at org.codehaus.groovy.control.ResolveVisitor.resolveFromStaticInnerClasses(ResolveVisitor.java:652)
	at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:498)
	at org.codehaus.groovy.control.ResolveVisitor.visitClass(ResolveVisitor.java:1597)
	at org.codehaus.groovy.control.ResolveVisitor.startResolving(ResolveVisitor.java:247)
	at org.codehaus.groovy.control.CompilationUnit$1.call(CompilationUnit.java:695)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:958)
	... 14 more
```

**Comment by eric-milles** [comment]
Is this still happening?

**Comment by mauromol** [comment]
Hard to say, it happened only sometimes. For sure it did not happen during the last couple of days.

**Comment by Mrodent** [comment]
I'm getting this, having just installed Eclipse "2019-09" on W10. 

Eclipse Enterprise, Version 2019-09 R (4.13.0).
Eclipse Groovy  Dev Tools 3.6.0.v201910072105... <-- this is probably the culprit.

**Comment by eric-milles** [comment]
Is it the same exception?

**Comment by Re-Offender** [comment]
We're seeing a similar error here when refreshing projects.

![grafik](https://user-images.githubusercontent.com/11608482/66477281-074e2080-ea98-11e9-9909-04c35afef8cb.png)

eclipse.buildId=4.13.0.I20190916-1045

java.version=1.8.0_152
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_AT
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

org.eclipse.core.jobs
Error
Wed Oct 09 13:17:24 CEST 2019
An internal error occurred during: "Refresh DSLD scripts".

java.lang.NullPointerException
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob.isFile(RefreshDSLDJob.java:99)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob.isDSLD(RefreshDSLDJob.java:89)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob$DSLDResourceVisitor.visit(RefreshDSLDJob.java:235)
	at org.eclipse.core.internal.resources.Resource.lambda$1(Resource.java:117)
	at org.eclipse.core.internal.resources.Resource.lambda$0(Resource.java:85)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:85)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:135)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:55)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:117)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:105)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob$DSLDResourceVisitor.findFiles(RefreshDSLDJob.java:247)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob.refreshProject(RefreshDSLDJob.java:182)
	at org.codehaus.groovy.eclipse.dsl.RefreshDSLDJob.run(RefreshDSLDJob.java:123)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by JacquesLeRoux** [comment]
Similar here: 
An internal error occurred during: "Refresh DSLD scripts".
org.codehaus.groovy.runtime.memoize.EvictableCache.getAndPut(Ljava/lang/Object;Lorg/codehaus/groovy/runtime/memoize/MemoizeCache$ValueProvider;)Ljava/lang/Object;

**Comment by JacquesLeRoux** [comment]
I think this should be reopened or should we create another issue?

**Comment by eric-milles** [comment]
Could you open a new issue with the specifics of your situation?
