### ISSUE TITLE
Formatter does not inherit whitespaces settings from Java fromatter

### ISSUE THREAD

**Issue by abialas** [groovy/groovy-eclipse#941]
I have the Groovy Eclipse version 4.12 (2019-06) from https://dist.springsource.org/release/GRECLIPSE/e4.12

I have Java formatter settings which should format the following:

`def dummyMethod() {
    def doIt=false
    if(doIt) {
        return null
    }
}`

into:

`def dummyMethod() {
    def doIt = false
    if (doIt) {
        return null
    }
}`

However, when I run format on the groovy file it does not add the additional spaces defined by formatter. It works perfectly for Java files.

**Comment by mojo2012** [comment]
Also multiple whitespaces  are not collapsed into one space:
```groovy
final def userClone =   (UserData) user.clone()
                      ^^
```

**Comment by mojo2012** [comment]
I've been trying to setup a proper eclipse IDE/build system - but I haven't got far up till now. It's there a simple way to just get to the point where I can run the `GroovyFormatterTest` without doing rocket-science-y stuff?
The guide here doesn't work: https://github.com/groovy/groovy-eclipse/blob/master/docs/Getting-Started-with-Groovy-Eclipse-Source-Code.md
Or more precisely the installer itself doesn't work.

So I download eclipse for committers. I somehow managed to import groovy-eclipse and also managed to make it build (or so it seams).
But a lot of projects have problems (groovy 2.4 set instead of 2.5, but inconsistent in the projects). Some projects are not detected as maven projects. Some need dependencies that only god knows where to find.

I think that the actual fix is not too hard to implement, but the setup is just crazy.

Sorry for the rant, but it's really frustrating. Imho if setting up a workspace is that complex, something very "basic" has gone wrong.

**Comment by eric-milles** [comment]
How far did the installer run?  What error(s) did you encounter?  The automated install should work, but I have not run it for a while.  There is a [manual setup guide](https://github.com/groovy/groovy-eclipse/blob/master/docs/Manual-Setup.md) that may or may not be current.

If you have the right plug-ins added to the IDE, it is a matter of switching to the right Groovy compiler version and importing the projects (most are not maven projects).  You should not need any other projects (like `org.eclipse.ant.optionl.junit`, etc.).

This should be all you need:
![image](https://user-images.githubusercontent.com/18193802/71930411-30e31a80-3161-11ea-9c71-33fbd70e51f8.png)

If you do not wish to use the IDE, you can run from command line with commands like: `mvn -Pe4.14 package verify`

**Comment by mojo2012** [comment]
The installer crashes with the following error log:
```
Executing bootstrap tasks
OpenJDK Runtime Environment 13.0.1+9
Product org.eclipse.products.epp.package.committers.latest.released
Workspace /Applications/Development/Groovy-Eclipse-master/ws
Project com.github.Groovy-Eclipse.master
Bundle org.eclipse.oomph.setup 1.15.0.v20191116-1146, build=4434, branch=3a9f8ff482882029c027d32dc59d8b0436598aa8
Bundle org.eclipse.oomph.setup.core 1.15.0.v20191103-0619, build=4434, branch=3a9f8ff482882029c027d32dc59d8b0436598aa8
Bundle org.eclipse.oomph.setup.installer 1.15.0.v20191204-1132, build=4434, branch=3a9f8ff482882029c027d32dc59d8b0436598aa8
Bundle org.eclipse.oomph.setup.p2 1.13.0.v20191019-1424, build=4434, branch=3a9f8ff482882029c027d32dc59d8b0436598aa8
Performing Workspace /Applications/Development/Groovy-Eclipse-master/ws
Performing P2 Director (Eclipse IDE for Eclipse Committers (2019-12))
Offline = true
Mirrors = false
Resolving 49 requirements from 6 repositories to /Applications/Development/Groovy-Eclipse-master/Eclipse.app/Contents/Eclipse
Requirement org.codehaus.groovy.m2eclipse.feature.feature.group
Requirement org.eclipse.jdt.source.feature.group
Requirement org.eclipse.pde.source.feature.group
Requirement org.eclipse.platform.source.feature.group
Requirement org.eclipse.m2e.feature.feature.group
Requirement org.eclipse.oomph.setup.sdk.feature.group
Requirement org.eclipse.pde.api.tools.ee.feature.feature.group
Requirement com.ifedorenko.m2e.mavendev.feature.feature.group
Requirement net.sf.eclipsecs.feature.group (optional)
Requirement epp.package.committers [4.14.0,5.0.0)
Requirement org.eclipse.platform.feature.group [4.14.0,5.0.0)
Requirement org.eclipse.rcp.feature.group [4.14.0,5.0.0)
Requirement org.eclipse.buildship.feature.group
Requirement org.eclipse.e4.core.tools.feature.feature.group
Requirement org.eclipse.eclemma.feature.feature.group
Requirement org.eclipse.egit.feature.group
Requirement org.eclipse.egit.gitflow.feature.feature.group
Requirement org.eclipse.egit.mylyn.feature.group
Requirement org.eclipse.epp.mpc.feature.group
Requirement org.eclipse.jdt.feature.group
Requirement org.eclipse.jgit.http.apache.feature.group
Requirement org.eclipse.mylyn.bugzilla_feature.feature.group
Requirement org.eclipse.mylyn.builds.feature.group
Requirement org.eclipse.mylyn.commons.feature.group
Requirement org.eclipse.mylyn.commons.identity.feature.group
Requirement org.eclipse.mylyn.commons.notifications.feature.group
Requirement org.eclipse.mylyn.commons.repositories.feature.group
Requirement org.eclipse.mylyn.commons.repositories.http.feature.group
Requirement org.eclipse.mylyn.discovery.feature.group
Requirement org.eclipse.mylyn.gerrit.dashboard.feature.feature.group
Requirement org.eclipse.mylyn.gerrit.feature.feature.group
Requirement org.eclipse.mylyn.git.feature.group
Requirement org.eclipse.mylyn.hudson.feature.group
Requirement org.eclipse.mylyn.monitor.feature.group
Requirement org.eclipse.mylyn.reviews.feature.feature.group
Requirement org.eclipse.mylyn.team_feature.feature.group
Requirement org.eclipse.mylyn.versions.feature.group
Requirement org.eclipse.mylyn.wikitext_feature.feature.group
Requirement org.eclipse.mylyn_feature.feature.group
Requirement org.eclipse.pde.feature.group
Requirement org.eclipse.rcp.source.feature.group
Requirement org.eclipse.wildwebdeveloper.feature.feature.group
Requirement org.eclipse.oomph.setup.feature.group
Requirement org.eclipse.oomph.setup.jdt.feature.group
Requirement org.eclipse.oomph.setup.git.feature.group
Requirement org.eclipse.oomph.setup.projects.feature.group
Requirement org.eclipse.oomph.targlets.feature.group
Requirement org.eclipse.oomph.setup.targlets.feature.group
Requirement org.eclipse.oomph.setup.workingsets.feature.group
Repository https://dist.springsource.org/snapshot/GRECLIPSE/e4.14
Repository https://ifedorenko.github.com/m2e-extras
Repository https://checkstyle.github.io/eclipse-cs/update
Repository http://download.eclipse.org/technology/epp/packages/2019-12
Repository http://download.eclipse.org/releases/2019-12/201912181000
Repository http://download.eclipse.org/oomph/updates/milestone/latest
Adding repository http://download.eclipse.org/technology/epp/packages/2019-12
Adding repository http://download.eclipse.org/releases/2019-12/201912181000
Adding repository https://dist.springsource.org/snapshot/GRECLIPSE/e4.14
Adding repository https://checkstyle.github.io/eclipse-cs/update
Adding repository http://download.eclipse.org/oomph/updates/milestone/latest
Adding repository https://ifedorenko.github.com/m2e-extras
ERROR: org.eclipse.equinox.p2.metadata.repository code=1000 No repository found at https://ifedorenko.github.com/m2e-extras.
  at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:396)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:567)
  at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:117)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.fail(CachingRepositoryManager.java:353)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:244)
  at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Metadata.loadRepository(CachingRepositoryManager.java:476)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:110)
  at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:105)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl$RepositoryLoader$Worker.perform(ProfileTransactionImpl.java:1581)
  at org.eclipse.oomph.util.WorkerPool$Worker.run(WorkerPool.java:434)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Took 2 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.
```

Regarding the groovy compiler version: I switched to 2.4 but then some of the project showed the inverse message, that the workspace level is 2.4 and the projects expects 2.5.

**Comment by eric-milles** [comment]
I removed the "Maven Development Tools" feature (ifedorenko.github.com/m2e-extras).  I think it takes a day for the installer metadata to be deployed.

None of the required projects should target Groovy 2.5.  It is likely that one of the other imported projects had .settings generated and it used the current groovy compiler version.

**Comment by mojo2012** [comment]
I openen a PR: https://github.com/groovy/groovy-eclipse/pull/1031
